### ISSUE TITLE
Using nifty.setLocale(Locale locale) "at runtime" (after it was loaded from an xml file) does not have an effect

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#100]
As the title already says it all, setting nifty's locale before loading the .xml file works well, but after letting nifty load, setting the locale with nifty.setLocale(...) will change nifty's locale variable, but seemingly not update anything, as the texts remain the same ones. So the user is forced to use work-arounds like letting nifty load all over again or by updating it all manually like here: http://jmonkeyengine.org/forum/topic/nifty-resourcebundle/
Either way this seems somewhat ugly to me, so I would recommend looking on this issue.

**Comment by void256** [comment]
This might be difficult to do but I'll look into it and consider this for 1.4.

**Comment by relu91** [comment]
I think that we could use EventBus to achieve a nice behavior without so much changes. Nifty publish a changeLocale event on eventBus and each element ( who has locale sensitive content ) subribe it self or an inner class to that event . When the event is raised the element will simply re-init the text-renderer , because the special value replace process is called inside that method. :smile:  . What do you think? . Also there are some other content that could be effected by language changes ? I think that text is the only thing that cares about that. isn't it ?

**Comment by relu91** [comment]
It isn't so easy , nifty replace all the special values on ElementType level , so it's not possible to know if the element has bundle keys at Element.class level . I think that this is the right behavior and we shouldn't modify it . We need some other data structure to collect locale sensible data , store them in the element class , and each time that locale is changed update the element with call initializeFromAttributes with a new instance of attributes that has the special values correctly replaced . What do you think ?

**Comment by void256** [comment]
yes, I already started - I think I have some code stashed somewhere. Will take a look soon :wink: thanks for the suggestions!

**Comment by relu91** [comment]
Glad to hear that :) I built an example for testing , maybe it is useful also for you . I'm sending a pull request , if you don't need it feel free to discard it! .

**Comment by void256** [comment]
Anyone able to review / test this? I'm aware that this does not solve everything that we might want to localize on the fly but for the moment I'm happy that it seems to work at least for text :wink:

**Comment by relu91** [comment]
Tested with the nifty-example, it works perfectly  ! I've not some other use case to test it though , so I think we should wait some other feed-back.

**Comment by void256** [comment]
I think we've waited long enough :smile: If there is a problem with it a new issue should be created.
