### ISSUE TITLE
No Textures Displaying

### ISSUE THREAD

**Issue by coldfusion01** [nifty-gui/nifty-gui#103]
I'm using Eclipse IDE with nifty 1.3.2, with nifty integrated into my own render engine (uses LWJGL).

Everything seems to be working fine, except textures. Backgrounds, icons, etc are just blank white boxes. No warnings or errors have been reported by the logger.

Examples in the nifty example library have worked fine, displaying texture.

Any suggestions on where to look to solve this issue?

Here are the OpenGL states I use for 3D rendering and 2D nifty rendering respectively:

```
public void set3DRenderStates(){

shaderModule.enableShader();   //Enable Vert, Geo, and Frag shaders

    GL11.glViewport(0, 0, 1024, 768);
    GL11.glMatrixMode(GL11.GL_PROJECTION);
    GL11.glLoadIdentity();
    Project.gluPerspective(45.0f,1024.0f/768.0f,0.1f,-500.0f);
    GL11.glMatrixMode(GL11.GL_MODELVIEW);
    GL11.glLoadIdentity();

    GL11.glShadeModel(GL11.GL_SMOOTH); //GL_SMOOTH GL_FLAT
    GL11.glEnable(GL11.GL_DEPTH_TEST);
    GL11.glDepthFunc(GL11.GL_LEQUAL);
    GL11.glHint(GL11.GL_PERSPECTIVE_CORRECTION_HINT, GL11.GL_NICEST);
    GL11.glCullFace(GL11.GL_BACK);
    GL11.glDisable(GL11.GL_CULL_FACE);
    GL11.glFrontFace(GL11.GL_CCW);  //default is GL_CCW
GL11.glDepthFunc(GL11.GL_LESS);
    GL11.glEnable(GL11.GL_DEPTH_TEST);
    GL11.glEnable(GL11.GL_LIGHTING);

    //Lighting Values
    FloatBuffer globalAmbient = BufferUtils.createFloatBuffer(4).put(new float [] {0.3f, 0.3f, 0.3f, 1.0f});

    //Flip buffer
    globalAmbient.flip();

    //Global Ambient Light Level
    GL11.glLightModel(GL11.GL_LIGHT_MODEL_AMBIENT, globalAmbient);
    GL11.glLightModeli(GL11.GL_LIGHT_MODEL_LOCAL_VIEWER, GL11.GL_TRUE);

    GL11.glEnable(GL11.GL_TEXTURE_2D);   
GL11.glTexParameteri(GL11.GL_TEXTURE_2D,GL11.GL_TEXTURE_MIN_FILTER,GL11.GL_LINEAR);     // Linear Texture Filtering
    GL11.glTexParameteri(GL11.GL_TEXTURE_2D,GL11.GL_TEXTURE_MAG_FILTER,GL11.GL_LINEAR);     // Linear Texture Filtering

    GL11.glDisable(GL11.GL_TEXTURE_2D); 
}

public void set2DRenderStates(){

shaderModule.disableShader();   //Disable Vert, Geo, and Frag shaders

    GL11.glMatrixMode(GL11.GL_PROJECTION);
    GL11.glLoadIdentity();
    GL11.glOrtho(0, 1024,768, 0, -1, 1);
    GL11.glDisable(GL11.GL_LIGHTING);
    GL11.glMatrixMode(GL11.GL_MODELVIEW);
    GL11.glLoadIdentity();

    GL11.glDisable(GL11.GL_DEPTH_TEST);
    GL11.glDisable(GL11.GL_CULL_FACE);
    GL11.glDisable(GL11.GL_BLEND);
    GL11.glDisable(GL11.GL_LIGHTING);
    GL11.glEnable(GL11.GL_ALPHA_TEST);
    GL11.glAlphaFunc(GL11.GL_NOTEQUAL, 0);
    GL11.glEnable(GL11.GL_TEXTURE_2D);
}
```

**Comment by void256** [comment]
Do you use multiple texture units eventually? Maybe a glActiveTexture(GL_TEXTURE0); call is missing before you call nifty.render()? And what exactly does shaderModule.disableShader() do?

The remaining code looks reasonable. So I'm not sure what else could be missing. Would it be possible that you let render Nifty isolated from your other code? With the initial GL state in place only?

**Comment by coldfusion01** [comment]
Ok tracked down the problem. During the render process I set the following in my lighting routine: 

GL11.glTexEnvi(GL11.GL_TEXTURE_ENV,GL11.GL_TEXTURE_ENV_MODE,GL11.GL_ADD);

I'm guessing GL11.GL_ADD was over saturating the colors. Switching to another mode prior to the nifty.render() routine solved by issues. Thanks for the help!

**Comment by magicgoose** [comment]
@coldfusion01 Not directly related to the problem, but you are using deprecated OpenGL functionality, which is generally bad. You should use your own matrix math and programmable pipeline.

**Comment by void256** [comment]
Thanks for posting what you've found @coldfusion01 I'm sure it can help others! :+1:
