### ISSUE TITLE
Nested controls

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#104]
Recently I'm figuring out how to make a custom control, which is ok to dive in with the Missing Manual and continous looks on the default xmls. One thing is bugging me though, which is the use of nested controls.
I have one as follows in my controls xml: (Had to switch the "<>"s to "[]"s because some dark interpreter magic made them invisible otherwise)
  [controlDefinition name="intField" focusable="true" visibleToMouse="true" controller="controls.IntFieldControl"]
    [control id="textField" name="textfield" /] 
  [/controlDefinition]
That is embedded in the main .xml file:
[control id="testControl" name="intField" focusable="true" /]
The central Controller code looks this way (though I think that code is slightly irrelevant to the core problem):
public class IntFieldControl implements Controller {
    ...
    @Override
    public void bind(Nifty nifty, Screen screen, Element element, Properties parameter, Attributes controlDefinitionAttributes) {
        ...
    }

```
@Override
public void init(Properties parameter, Attributes controlDefinitionAttributes) {

}

@Override
public void onStartScreen() {

}

@Override
public void onFocus(boolean getFocus) {

}

@Override
public boolean inputEvent(NiftyInputEvent inputEvent) { 
    System.out.println("InputEvent: " + inputEvent);
    return false;
}

@NiftyEventSubscriber(pattern="textField.*") //so I'm sure to be listening
public void onTextFieldChange(String id, TextFieldChangedEvent event) { 
    System.out.println("OnTextFieldChange: " + event.getText());
}
```

}

The first issue I noticed is that the mouse cursor looks really weird when he's hovering the textfield control, he has some black lines attached on the top and a black filled rectangle attached on its bottom (that also goes for non-nested textfield controls).

So hovering and clicking on the textfield is possible. But it does not become actually usable!
I can rage-click as much as I want, but there is no text cursor daring to appear on the textfield. Key input is also just being ignored. The IntFieldControl prints me the corresponding events. but the desired TextFieldChangedEvents are not being delivered at all. Non-nested textfields work regarding that matter, though.

My question is, if nested controls are even possible or if there are some rules I am not aware of atm? After all, I would hate to switch my planed custom controls to some unholy panel pattern that is copied wildly around my xmls just to have some working controls inside of them...

**Comment by void256** [comment]
The key here is this quote from the manual:

> When Nifty parses a Nifty XML file and it finds a control, it looks up a matching control definition using the control name. If a corresponding control definition is found the content of the control definition actually replaces the control tag.

So in your case when you use

```
<control name="intField" />
```

somewhere the **content** of your "intField" controlDefinition will be added, actually replacing the control tag. In your case this means the textField control will be added. So far so good BUT since you have specified a controller **YOUR** controller will overwrite the standard textfield controller and since your Controller doesn't behave like a real Textfield controller you end up with a textfield that is not responding.

This is usally solved with an extra panel inside the controlDefinition, something like:

```
<controlDefinition name="intField" focusable="true" visibleToMouse="true" controller="controls.IntFieldControl">
  <panel>
    <control id="textField" name="textfield" />
  </panel>
</controlDefinition>
```

This way the

```
<control name="intField" />
```

will be replaced with the panel and not directly with the textfield control. Just imagine that extra panel as the root element of your control.

**Comment by HariboTer** [comment]
Thanks a lot, that makes sense! Thanks for the detailed explanation (which really helped my understanding of controls, I had thought the controlDefinition would already represent some kind of root element, to which its child elements are attached), now I can get back to coding :)
