### ISSUE TITLE
buttonStepSize / pageStepSize for scrollPanel and listBox

### ISSUE THREAD

**Issue by coldfusion01** [nifty-gui/nifty-gui#107]
Are the buttonStepSize / pageStepSize (or similar) attributes available for scrollPanels and listBoxes? They would be pretty helpful when browsing through larger data sets (i.e. large grid of tiles, library listings, spreadsheets).

Didn't find anything in the documentation.

-cf01

**Comment by void256** [comment]
You could probably try to element.findControl() the scrollbars inside of the scrollPanel and listBox and change the values there. But I agree that this should be a part of the regular API as well.

**Comment by coldfusion01** [comment]
Ok, thanks. I'll give that a try later this week.

**Comment by relu91** [comment]
I think that a solution will be to make public getVerticalScrollBar getHorizontalScrollBar public :) , I'll add it when my last pull request will be merged or if not I will make a general pull request with these changes :+1:

**Comment by relu91** [comment]
This should be closed feel free to re-open if there's something that I've missed
