### ISSUE TITLE
Issue with running slick2d example

### ISSUE THREAD

**Issue by dionysius** [nifty-gui/nifty-gui#110]
Hello

I tried to run AllDemoMain in the slick example package, but I'm struck with the following stack trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.newdawn.slick.Font.getWidth(Ljava/lang/String;)I
    at de.lessvoid.nifty.slick2d.render.font.AbstractSlickRenderFont.getWidth(AbstractSlickRenderFont.java:80)
    at de.lessvoid.nifty.elements.render.TextRenderer.initText(TextRenderer.java:166)
    at de.lessvoid.nifty.elements.render.TextRenderer.setText(TextRenderer.java:136)
    [...]
```

I found a forum post (http://slick.javaunlimited.net/viewtopic.php?p=31527) reporting this issue. The current workaround there is using an older version of slick. But this link there does not work.

My question is now, how I could continue? Does someone maybe have a compatible build of slick with nifty 1.3.2?

**Comment by dionysius** [comment]
I think the link there does not work because http://slick.cokeandcode.com seems to be down currently.

Debugging and trying further: Went ahead and configured project using slick from here: http://nifty-gui.sourceforge.net/nifty-maven-repo/slick/slick/20101219/ and worked. Finally I can continue ;)

Slick from there seems to be very old (Dec 2010). The current version (build 264) is from (Oct 2012)

So meanwhile hoping a fix for latest slick coming soon.

**Comment by dionysius** [comment]
I'm relatively new to java, but I was able to solve it - I just don't know exactly why ^^ So, just for understandig, can someone provide me a reference why this way worked to compile and use without any source modification?

In short:
To fix it just build nifty-slick-renderer yourself against newest slick jar.

In detail:
I went ahead and downloaded all relevant builds for nifty 1.3.2 from http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/. All packages as jars except for nifty-slick-renderer the source. I have setup a separate project using the source of nifty-slick-renderer to try to fix it myself. But as I freshly built it against newest slick.jar the example just worked without any modification.

**Comment by void256** [comment]
The Slick2d renderer of Nifty is build against a (old) version of Slick as you've discovered.

To use the binary of that Nifty Slick2d renderer jar you'll need the exact same Slick2d jar that was used to build the renderer - to be safe at least.

`Exception in thread "main" java.lang.NoSuchMethodError: org.newdawn.slick.Font.getWidth(Ljava/lang/String;)`means that Nifty couldn't find the method `getWidth()` on the `org.newdawn.slick.Font` class that takes a `java.lang.String` as its only parameter.

The link [on the Slick forum](http://slick.javaunlimited.net/viewtopic.php?p=31527) you've posted explains that in newer versions of Slick "String" has been replaced with "CharSequence". Although this is compile-time compatible (String implements CharSequence) it is not binary compatible. In other words: in the Slick jar that Nifty expects it requires a method that takes a String and not a CharSequence but it can't find it and therefore has to complain and crash. Recompiling fixes this because now Nifty will use the method with the CharSequence which exists in newer versions of Slick :smile: 

If you had no other problems with a newer Slick2d version we could use the newer version in the project too. The only problem is, that I don't know if and where newer Slick2d build are available for Maven. Which is kinda a side-problem of Issue #115.

Anyone knows of a working Slick2d Maven repo for newer builds? Or do we have to install them manually in the Nifty maven repo again as we've done before? :wink:

**Comment by void256** [comment]
According to @mkaring newer Slick2D versions are not available as Maven artifacts anymore :cry: 

Therefore I've uploaded the latest Slick2D version to the Nifty Maven repo hosted at sf.net: http://nifty-gui.sourceforge.net/nifty-maven-repo/slick/slick/20121001-264/

I'll update the nifty-slick-renderer with this version as soon as I can too.

**Comment by dionysius** [comment]
Thank you for explaining me the differences. At least here's described how to do it manually so there's no need to stress ;)

Edit: And by the way, I had no other problems with the newer slick so far yet. Except a bug (I think) when using NiftyOverlayBasicGameState. But I'll post that issue when I'm done with the current project, which will be in a week or two.

**Comment by void256** [comment]
Updated to latest Slick2d in both 1.3 and 1.4 branches :smile: 

Now I'll need someone to confirm that this actually works so that I can close this Issue :wink:

**Comment by Banbury** [comment]
Sorry to disappoint, but it doesn't work for me. I get the same error message as the OP.

**Comment by void256** [comment]
@Banbury Did you use the latest SNAPSHOT build of Nifty from the maven repo or did you try building it from the source?

I've just compiled and run it successfully using the following commands on Mac OS X:

```
cd /tmp
git clone git://github.com/void256/nifty-gui.git
cd nifty-gui/
git checkout 1.3
mvn clean install
cd nifty-examples-slick2d/
export MAVEN_OPTS=-Djava.library.path=target/natives/
mvn exec:java -Dexec.mainClass="de.lessvoid.nifty.examples.slick2d.all.AllDemoMain"
```

I don't see the message or any other errors and got it running.

**Comment by void256** [comment]
And just for good measure I tried the same with the 1.4 branch and it works there as well.

**Comment by Banbury** [comment]
I just tried it with 1.3.2-SNAPSHOT and 1.3.3-SNAPSHOT from your repo and it doesn't work. I'm on Win7 and JAVA 6 if that does make any difference.

I will have a look at your example to see, if I'm doing something wrong.

**Comment by dionysius** [comment]
I made a little test using my existing nifty-examples testing project. I confirm that examples run with nifty-slick-renderer-1.3.3-20130517.231239-25.jar and will fail with nifty-slick-renderer-1.3.3-20130408.222542-21.jar with the exception as described above

**Comment by Banbury** [comment]
The version number helped me sort out my problems. Whad'ya know, with the right version it actually works :).

**Comment by void256** [comment]
Excellent! Thanks for confirming! :smile:

**Comment by RyanQuackenbush** [comment]
@dionysius 
Would you be able to explain:

`To fix it just build nifty-slick-renderer yourself against newest slick jar.`

I've cloned the repo via @void256 post

```
cd /tmp
git clone git://github.com/void256/nifty-gui.git
cd nifty-gui/
git checkout 1.3
mvn clean install
```

And now have all the source for 1.3/1.4, but am not sure how you went about "building" nifty-renderer-slick into your project from source. I'm also getting the `getWidth` error as mentioned in the OP. 

What I have tried to no avail:
- My default setup was the latest slick2d with nifty-slick-renderer-1.3.3.jar
- Downloading slick-20101219.jar and replacing my latest slick jar
- Replacing nifty-slick-renderer-1.3.3 with 1.3.4-SNAPSHOT (and trying the latest slick.jar with this again)
- Adding the source for nifty-renderer-slick to my project's lib folder and building, as well as trying the entire nifty-gui source. 

Essentially I'm not sure how I would build against my newest slick jar .

**Comment by dionysius** [comment]
@RyanQuackenbush 
Have you checked, that you took a snapshot later than 17-May-2013 (at least for 1.3.3)? fix should been directly included to 1.3.4. But generally, you should go fine when using latest snapshot.

With building I've setup a an eclipse project using the source of nifty-slick-renderer, adding all dependencies jars, and after successful compilation, exported as jar again. But since I think you just took the wrong jar, take the snapshot.

If you're unsure, you can just take the snapshot version described in this https://github.com/void256/nifty-gui/issues/110#issuecomment-18168482

**Comment by dionysius** [comment]
Strange, I don't get it working with the snapshots, even the snapshot I used some time ago. But after compiling nifty-slick-renderer freshly works just fine. oO

Maybe this seems easiest way to explain how I compiled:
![screenshot from 2013-10-07 09 48 30](https://f.cloud.github.com/assets/1341084/1278795/0183dee0-2f25-11e3-82ed-b9ab7752c4e0.png)

and set nifty-slick-renderer as reference to nifty-example (or build jar from it and then add to build path)

**Comment by RyanQuackenbush** [comment]
That screen shot was golden for helping to understand, but I copied verbatim all the 1.3.4-20130922 jar files (including the examples which shouldn't be needed). Compiled the jar against the same slick version as my project, as well as tried adding the slick-renderer project to my projects build path. Still getting the same error as OP. 

I ended up having to revert my slick version back to the [post](https://github.com/void256/nifty-gui/issues/110#issuecomment-18036547) void referenced earlier and then recompile the slick-renderer off that version of slick. Thanks for the help on that. I'll have to try 1.4 and see how that goes with the latest version of slick.

**Comment by RyanQuackenbush** [comment]
I went ahead and tried to use the 1.4-SNAPSHOT (compiled / packaged from source) with the latest slick and was able to get that up and running as well using the same method as above. 

@void256 
I'm getting a NiftyEventBusalready exists though when using initNifty( container, game) in more than one GameState.  Is there a simple fix to this? I read [this post](http://sourceforge.net/p/nifty-gui/discussion/807893/thread/fa37ca5f#a6e7) and saw you metioned a fix, but it may not be what I was looking for.

**Comment by mkaring** [comment]
I am not sure if you solved it already or not. How ever the solution is to use the second parameter of the NiftyStateBasedGame constructor that controls if there are multiple or a single Nifty instance. In case you use multiple instances, you can't avoid this error as every instance tries to initialize the EventBus.

In case you use a single instance (and I really suggest you do), you won't get this error. How ever due the fact that you have only one instance of the Nifty-GUI you have to make sure that that the screen names across all states are unique.
