### ISSUE TITLE
Pasting text into a textfield ignores maxLength setting

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#113]
## Expected Behavior:

Pasting text into a textfield with the maxLength setting set will truncate pasted text to ensure that maxLength is not violated, or will at least prevent pasting altogether if the paste operation would result in the total length of the textfield text to be greater than maxLength.
## Actual Behavior:

Pasting text into a textfield with the maxLength setting set will ignore the maxLength setting and paste all of the text, regardless of length.
## Steps to Reproduce:
1. Run either the default controls or standard examples web start for nifty gui 1.3.2.
2. Go to the textfield demonstration.
3. Ensure maxLength is set and enabled.
4. Ensure the textfield is not already full to maxLength (it can have maxLength - 1 characters or less). It doesn't occur if  the textfield text is already at maxLength.
5. Paste text longer than maxLength into the textfield, or paste text such that the total length of the text in the textfield will be greater than maxLength.
## System:

Nifty Gui 1.3.2
Java 1.6.0_43
2006 Intel Core 2 Duo MacBook
2 GB RAM
Intel GMA 950 Integrated Graphics Chipset
OS X 10.6.8 Snow Leopard

**Comment by void256** [comment]
Not sure why it took me a year to fix that :wink:

**Comment by ghost** [comment]
Thank you! =D
