### ISSUE TITLE
Textfield cursor corruption with LWJGL 2.9.0

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#115]
I know. Another textfield issue ;). I'm not sure if this one is nifty or lwjgl or some combination of both. But I'm betting this one only happens on OS X, as lwjgl got a complete OS X rewrite, including mouse cursors. I tried to take a screenshot, but the mouse cursor isn't included in the resulting image for some reason.

I also tried to test this with the nifty standard controls / standard examples demos, but I couldn't figure out how. I cloned into 1.4 and updated lwjgl to 2.9.0 in the nifty-renderer-lwjgl pom. Then I did `mvn clean install` but got some errors:

[ERROR] Failed to execute goal on project nifty-slick-renderer: Could not resolve dependencies for project lessvoid:nifty-slick-renderer:jar:1.4.0-SNAPSHOT: Failed to collect dependencies for [lessvoid:nifty:jar:1.4.0-SNAPSHOT (compile), slick:slick:jar:274 (compile), junit:junit:jar:4.3.1 (test), org.easymock:easymock:jar:2.4 (test), org.easymock:easymockclassextension:jar:2.4 (test)]: Failed to read artifact descriptor for slick:slick:jar:274: Could not transfer artifact slick:slick:pom:274 from/to slick-maven-repo (http://slick.cokeandcode.com/mavenrepo): Failed to transfer file: http://slick.cokeandcode.com/mavenrepo/slick/slick/274/slick-274.pom. Return code is: 504, ReasonPhrase:Gateway Time-out. -> [Help 1]

Do I need to manually install those artifacts? Do you not get these errors because you're using Nexus or something?

Is there a better way to go about this? I'd like to work with 1.3.3 or 1.4 if practical...
## Expected Behavior:

When the mouse cursor hovers over a textfield, the text cursor image looks normal.
## Actual Behavior:

When the mouse cursor hovers over a textfield, the text cursor image is corrupted / garbled.
## Steps to Reproduce:
1. Upgrade to LWJGL 2.9.0
2. Hover the mouse cursor over a nifty textfield.
## System:

Nifty Gui 1.3.2
LWJGL 2.9.0
Java 1.6.0_43
2006 Intel Core 2 Duo MacBook
2 GB RAM
Intel GMA 950 Integrated Graphics Chipset
OS X 10.6.8 Snow Leopard

**Comment by HariboTer** [comment]
If you're referring to a weird line and a black box near the cursor, this is not such a new thing. I see it in the most current Slick2D nifty build too (LWJGL 2.8.5).

**Comment by ghost** [comment]
No, the cursor itself is corrupted. And it worked perfectly for me on
2.8.5. And, I'm not using Slick.

**Comment by void256** [comment]
I see the same odd pixels on Mac OS X using lwjgl 2.9.0 :/ I've just asked on irc://freenode/lwjgl if this is a known problem and I'll eventually post a bug report on the forum later. When I do I'll post the link here. Maybe just something in the image format has been changed but it looks like a bug in lwjgl 2.9.0 to me.

The other problem mentioned with Slick: Yes, it seems like the slick maven repo that Nifty used is broken and because I already have the missing artifact in my local repository it still works for me.

I'm not sure if and where Slick2d Maven artifacts are now hosted but I'll bug @mkaring about it :smile:

**Comment by ghost** [comment]
@void256 Thanks for the reply. I'm looking forward to getting these bugs resolved, but especially being able to build nifty 1.3.3 or 1.4 from source without any errors. :D

**Comment by void256** [comment]
According to @mkaring the reason for these rendering artifacts could be the size used for the textcursor image. The size of the cursor that the OS supports is kinda limited and might be restricted to be a power of two.

I haven't had any time yet to investigate this further but I think this might be the problem. Maybe earlier LWJGL versions did correct the image size automatically and it has been removed on 2.9.x?

I'll check this as soon as I can.

There are news on the Slick2d front as well but see the Issue #110 for details on this :smile:

**Comment by void256** [comment]
I didn't find any issue with the size of the cursor image and filed a bug report on the LWJGL Forum here: http://lwjgl.org/forum/index.php/topic,5007.0.html

**Comment by ghost** [comment]
@void256 I'm impressed - it looks like you singlehandedly fixed the LWJGL / OS X cursor bug - good job! I've been traveling, but I'll test the fix as soon as I can, as well as building nifty 1.3.3 / 1.4 with the latest slick from your maven repo. Thanks!

**Comment by void256** [comment]
Updating LWJGL to 2.9.1 fixed that issue.

Here are the relevant commits for the 1.3.x and 1.4.x branches:

c2b633c99eb91b4b80504648ae5f958bc5ac1350
2cdcecf208afcbe77ea788841e131653afd1464d

I'll close this issue now.
