### ISSUE TITLE
ScrollPanels invalidate each other when used with popups

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#119]
I have been evaluating this problem for quite some time now and I am pretty sure it is a bug in the nifty library. The problem is that I have a first popup with a scrollpanel. When I lay another popup over it that contains another scrollpanel and close that second popup, the first popup's scrollpanel is sort of invalidated, that means it still shows its content and is responding to mouse events, but it does not scroll its content panel any more (it can still be layouted from the code, but won't move although I tried calling reactivate() and/or similar methods), even though the bars on the sides are moved.
This seems to be a severe issue to me, especially since I can't find a workaround for this.

**Comment by HariboTer** [comment]
It seems to me as this problem arises everytime a default nifty scrollpanel control is overlayed by a popup - its vertical slider (have not used the horizontal one in the respective context yet) is still interactive, but does not move the content any more.
I would be grateful for a response regarding this issue, as it is effectively reducing my game's functionality :S

**Comment by void256** [comment]
I'm sorry for that issue but I've not been able to reproduce it. iirc I tried it with the standard controls demo where I displayed a popup above a scrollpanel but didn't have any issues and then, I'm afraid, I forgot to reply to you here :/

Can you isolate the problem and send a code snippet so that I can try it here with the exact same setup?

**Comment by HariboTer** [comment]
Unfortunately I won't have the time for that until thursday, but then I should (hopefully) be able to provide the problematic code :-)

**Comment by HariboTer** [comment]
Ok, I isolated the problem with the stacked popups corrupting scrollpanels in overlayed popups (at least it seems so to me):

``` xml
<screen id="testScreen" controller="main.TestState$TestScreenController" >
    <layer childLayout="center" >
      <panel width="50%" childLayout="vertical" >
        <control name="scrollPanel" id="testScrollPanel" width="100%" height="300px" horizontal="false" >
          <panel id="contentPanel" width="100%" childLayout="vertical" >
            <panel height="200px" backgroundColor="#f00f" />
            <panel height="200px" backgroundColor="#0f0f" />
            <panel height="200px" backgroundColor="#00ff" />
          </panel>
        </control>
        <control name="button" label="Open the infamous popup" width="160px" align="center" >
          <interact onPrimaryClick="openTestPopup()" />
        </control>
      </panel>
    </layer>
  </screen>

  <popup id="testPopup" childLayout="center" backgroundColor="#fffa" controller = "main.TestState$TestPopupController" >
    <panel width="40%" height="50%" childLayout="vertical" style="nifty-panel" >
      <control name="scrollPanel" id="scrollPanel" horizontal="false" stepSizeY="25" pageSizeY="32">
        <panel id="filePanel" width="100%" childLayout="vertical" >
          <panel width="100%" height="200px" backgroundColor="#ff0f" />
          <panel width="100%" height="200px" backgroundColor="#f0ff" />
        </panel>
      </control>
      <control name="button" label="Click me away!" width="160px" align="center" >
        <interact onPrimaryClick="closeTestPopup()" />
      </control>
      <control name="button" label="Or open the second popup!" width="160px" align="center">
        <interact onPrimaryClick="openTestPopup()" />
      </control>
    </panel>
  </popup>
```

And the code:

``` code
    public static class TestScreenController implements ScreenController {
        private Nifty nifty; private Screen screen;
        private Element testPopup0 = null, testPopup1 = null;

        @Override
        public void bind(Nifty nifty, Screen screen) {
            this.nifty = nifty; this.screen = screen;
        }

        @Override
        public void onStartScreen() {}

        @Override
        public void onEndScreen() {}

        public void openTestPopup() {
            if(testPopup0 == null) {
                testPopup0 = nifty.createPopupWithId("testPopup", "someTestId");
                nifty.showPopup(screen, testPopup0.getId(), null);
            } else if(testPopup1 == null) {
                testPopup0.disable();
                testPopup1 = nifty.createPopupWithId("testPopup", "someOtherTestId");
                nifty.showPopup(screen, testPopup1.getId(), null);
            }
        }

        public void closeATestPopup() {
            if(testPopup1 != null) {
                nifty.closePopup(testPopup1.getId());
                testPopup1 = null;
                testPopup0.enable();
            } else if(testPopup0 != null) {
                nifty.closePopup(testPopup0.getId());
                testPopup0 = null;
            }
        }
    }

    public static class TestPopupController implements Controller {
        private TestScreenController test_etc;
        @Override
        public void bind(Nifty nifty, Screen screen, Element element, Properties parameter, Attributes controlDefinitionAttributes) {
            test_etc = (TestScreenController)screen.getScreenController();
        }

        @Override
        public void init(Properties parameter, Attributes controlDefinitionAttributes) {}

        @Override
        public void onStartScreen() {}

        @Override
        public void onFocus(boolean getFocus) {}

        @Override
        public boolean inputEvent(NiftyInputEvent inputEvent) {
            return false;
        }
        public void closeTestPopup() {
            test_etc.closeATestPopup();
        }
    }
```

Which causes the problem described in the OP.
As for the other ScrollPanel problem, I'm still trying to get a code snippet to reproduce it. Though I hope it can be found with help of the already provided code ;-)
Anyway, thank you for looking over this! :-)

Edit: Some further extensive testing (and some random changes) made me find out that this problem is mostly caused by conflicting IDs. Though in that is a point I would call critical, as having two scrollPanels controls without id at the sime time causes them to conflict in a sort of contra-productive way, whereas the same issue in overlayed popups is caused by scrollpanels that DO have an id (even although I tried setting them unique afterwads in the code, it didn't work)...
So I apologize about my mistake, and thank you for still being open to my (probably over the time enerving) "reports" ^^

**Comment by void256** [comment]
Thanks for the example. I can reproduce the issue now and I agree that this is a bug.

However there exists a workaround that lets you keep the main popup-id the same. Using the "#id" syntax that is actually only meant to be used in the controlDefinition-Tag can be used in a popup as well:

```
  <popup id="testPopup" childLayout="center" backgroundColor="#fffa" controller = "de.lessvoid.nifty.examples.helloworld.HelloWorldExampleMain$TestPopupController" >
    <panel width="40%" height="50%" childLayout="vertical" style="nifty-panel" >
      <control name="scrollPanel" id="#scrollPanel" horizontal="false" stepSizeY="25" pageSizeY="32">
        <panel id="#filePanel" width="100%" childLayout="vertical" >
...
```

This way the ids **inside** of the popup don't conflict with themself anymore :)

Btw: If you leave out the id attribute altogether it will work as well! You'll only need to add id to elements that you want to access by code. Which I assume is the case in your example.

**Comment by HariboTer** [comment]
Yeah, I added the id first because I was not sure if I would need to access the control per code and then forgot about it later as I didn't need to access it anyway.
So I returned to that id just recently (meaning today) when I had accidentally discovered that removing it solved the problem :D
Also thanks for your explanations, I think this topic is finished now :-)
