### ISSUE TITLE
Nifty GUI thread access

### ISSUE THREAD

**Issue by philipwhiuk** [nifty-gui/nifty-gui#130]
I'm writing a client-server game and trying to understand how Nifty works with threads in practice.

I have the following render loop (simplified slightly)

``` java
        nifty = new Nifty(new LwjglRenderDevice(), new OpenALSoundDevice(),
                inputSystem, new AccurateTimeProvider());
        loginScreen = new LoginScreen(this);
        nifty.registerScreenController(loginScreen);
        nifty.fromXml("loginScreen.xml", "start");
        openNetworkConnection();  //Asynchronously opens a network connection
        boolean done = false;
        while (!Display.isCloseRequested() && !done) {

            // Future - render OpenGL here
            Display.update();
            if (nifty.update()) {
                done = true;
            }
            nifty.render(true);
            int error = GL11.glGetError();
            if (error != GL11.GL_NO_ERROR) {
                String glerrmsg = GLU.gluErrorString(error);
                LOGGER.warn("OpenGL Error: (" + error + ") " + glerrmsg);
            }
        }
```

I receive network messages on another thread and handle them there currently. So on the network thread I currently have the following:

``` java
        lobbyScreen = new LobbyScreen(this, account);
        nifty.registerScreenController(lobbyScreen);
        nifty.fromXml("lobbyScreen.xml", "lobby");
```

Given that this is not on the initial thread that I initialised Nifty, this generates 
"No OpenGL context found in the current thread."

What is the recommended solution, #111 talks about the Swing EDT thread - is this the thread Nifty GUI renders on? Should I be storing a reference to the main thread and using that to dispatch Nifty GUI calls to it?

Advice appreciated.

**Comment by philipwhiuk** [comment]
I have an imperfect solution to this now involving queuing runnables which are executed during the render loop.

``` java
    /**
     * Run any queued events on the Nifty thread.
     */
    private void runQueuedNiftyEvents() {
        while (!queuedNiftyEvents.isEmpty()) {
            Runnable runnable = queuedNiftyEvents.poll();
            runnable.run();
        }
    }
```

**Comment by void256** [comment]
Yes at the moment your solution is the way to go. In general you have to make sure that all changes to Nifty (as well as the calls to render it) will occur on the same Thread. It has to be the Thread that initially created the OpenGL context.

The Swing EDT-Thread was meant as an example since there is a similar situation. Nifty does not use or has any Swing dependencies though.
