### ISSUE TITLE
findElementByName is confusing

### ISSUE THREAD

**Issue by philipwhiuk** [nifty-gui/nifty-gui#131]
In: `de.lessvoid.nifty.elements.Element`
There is:

``` java
  /**
   * find an element by name.
   *
   * @param name the name of the element (id)
   * @return the element or null
   */
  public Element findElementByName(final String name) {
```

It would make a lot more sense if this was called `findElementById`

**Comment by void256** [comment]
This was fixed in the 1.4 branch by issue #82 and commit 2bf94cba6353cb3a7feadd20c9670e730b3dba72. There are no plans to backport this to 1.3.x at the moment.
