### ISSUE TITLE
[1.4] childClip inside childClip does not work correctly

### ISSUE THREAD

**Issue by void256** [nifty-gui/nifty-gui#138]
Thinking about [this thread](http://hub.jmonkeyengine.org/forum/topic/nifty-gui-scrollpanel-problem/) at the jme forum I've found the following code:

``` java
public void enableClip(final int x0, final int y0, final int x1, final int y1) {
    // in case there already is a clipping area set we can't override it. not sure if this is correct tho but it
    // fixes issues when some parent element has set a clipping area in which child elements should not be able to override the area.
    if (clipEnabled) {
      return;
    }
    updateClip(true, x0 + getX(), y0 + getY(), x1 + getX(), y1 + getY());
  }
```

I think the right way to solve that is to clip the new clip rectangle to the existing one so that we can make sure nothing is drawn outside the existing clipping rectangle and still be able to further restrict the clipping. Please note that it's still not possible to override an existing clipping rectangle. But thats ok since that's what this comment tries to do anyway.

PS: We can get the code to intersect rectangles from the batched renderer where we already solved that.

**Comment by relu91** [comment]
I don't know if I should open a new issue but I comment here first. The implementation that was done prevent final user do dynamically change the clipArea of nifty. I don't know if this would be a common user case , but it is mine :-) . For example if I simply want to move the clipped area around after a increment of a scrollbar , the clip becomes littler and littler instead of move at desired position. My suggestion is to add a method to force the clip instead of using enableClip , you could use setClip to force a clip without cropping it . This is also Java2d approach see : http://docs.oracle.com/javase/7/docs/api/java/awt/Graphics2D.html#clip(java.awt.Shape) and http://docs.oracle.com/javase/7/docs/api/java/awt/Graphics.html#setClip(java.awt.Shape) .

**Comment by void256** [comment]
Yes, that would be possible :smile: We would need a way to enable something like "absoluteClip" at the element and find a way to route that information down until the NiftyRenderDevice. Once at NiftyRenderDevice level it's easy because when that "absoluteClip" information is present all of the default behaviour would be overwritten and the new clip rectangle is used as-is :D

I would suggest not using the Java2d API directly but find something similar that fits better into the existing "clipChild" attribute - because I would left the default behaviour as-is. Maybe introduce a separate attribute for that, like "clipChildAbsolute" or so?

**Comment by relu91** [comment]
Sorry maybe I wasn't clear. I don't need a new attribute from elements that could active this "absoluteClip" , I simply want to interact with nifty renderEngine from java . See here : 

``` java
public void myRenderLoop(){
          nifty.update();
           int x = getScrollBarX();
           int y = getScrollBarY();
          //I want to enable clip here so the entire gui will be clipped
           nifty.render(true);
}
```

What I currently do is : 

``` java
public void myRenderLoop(){
          nifty.update();
           int x = getScrollBarX();
           int y = getScrollBarY();
           int w = getViewportW();
           int h = getViewportH();
           nifty.getRenderEngine().enableClip(x,y,x+w,y+h); //here set the clip
           nifty.render(true);
}
```

but as I said due to this changes in nifty-gui , it not change the clip as I aspected . So my proposed implementation for this is : add a new method in RenderEngine called as you said setAbsoluteClip and the code would became : 

``` java
public void myRenderLoop(){
          nifty.update();
           int x = getScrollBarX();
           int y = getScrollBarY();
           int w = getViewportW();
           int h = getViewportH();
           nifty.getRenderEngine().setAbsoluteClip (x,y,x+w,y+h); 
           nifty.render(true);
}
```

Maybe this is not the standard use of render engine... I'm aware of this , but I don't know if an attribute in Element class is worth it.. I mention the java2d api only as a reference of implementation sice it use two different methods to set a clip. Is it clearer now ? 

Thank you for your fast answer void ^^

**Comment by relu91** [comment]
Also I wlli pay attention to not break the apis! But if that method will only called before the render method , should no effect the current behavior

**Comment by void256** [comment]
OK, I get it. That would work! One final note though:

Are you aware that inside the nifty.render() call it's still possible that you have elements with childClip=true which will further reduce _your_ absolute clipping rectangle? I guess, you're cool with that, right?

Or do you expect that _your_ absolute clipping rectangle will be the only active clipping rectangle and that other attempts to modify it will be ignored?

Considering the API I would suggest to add the "setAbsoluteClip()" method directly to the Nifty class. Accessing the RenderEngine directly (like in your examples) is done in some places but it's really supposed to be an implementation detail that is not supposed to be exposed to the public. I guess it was a mistake to make it public :wink: but I guess it was required by some Nifty controls or something.

**Comment by relu91** [comment]
"Are you aware that inside the nifty.render() call it's still possible that you have elements with childClip=true which will further reduce your absolute clipping rectangle? I guess, you're cool with that, right?"

Yes , I looked into the code and I have an overall idea on how things are going there . :smile:  I'll do some test before to submit my pull request . 

About the implementation I'm ok to add the method direct to nifty but I assume that you won't to change NiftyRenderEngine interface right? So i should add the low level method to NiftyRenderEngineImpl . To be clear :

``` java
 //In Nifty.java
public void setAbsoluteClip(int x,int y,int w,int h){
        //Safty cast the renderEngine instance to renderEngineImpl and then use the method
}

// in NiftyRenderEngineImp.java
public void setAbsoluteClip(int x,int y,int w,int h){
        //set the actual clip
}
```

seem fine ?

**Comment by void256** [comment]
You can change NiftyRenderEngine too not only the Impl!

In the past there was a NiftyRenderEngineProxy implementation that recorded certain state changes when rendering elements BUT we later realized that it is completely unecessary and so it was removed again :wink: Therefore the NiftyRenderEngine interface doesn't add that much value anymore so I guess in the future it will be removed anyway.

But yes, add the new setAbsoluteClip() method to both, the interface and the impl! That will make the cast unnecessary and is much 'cleaner' that way!

**Comment by relu91** [comment]
Ok ! I thought you did not want make the absoluteClip accessible also from NiftyRenderEngine interface :smile: . Pull request soon!

**Comment by void256** [comment]
Yes :smile: but actually I meant that - in general - I don't want to allow access to the **whole** NiftyRenderEngine via getNiftyRenderEngine() and not only your new method :wink: because the whole thing should really be hidden and not be part of Niftys Public API. But currently there is nothing we can do about that without breaking a lot of code so it's okay to add your new method to the Interface as well!

**Comment by relu91** [comment]
It not so easy as I expected . The other renders ( slick2d and LWJGL ) clear the clip area every beginFrame() call . This causes that the absolute clip is force overridden and it doesn't work . I have try some workarounds but none of this is a clear solution : 

``` java
//NiftyRenderEngineImp
public void setAbsoluteClip(int x,int y,int w,int h){
        this.absoluteClip = new Clip(x,y,x+w,h+y);
}

@Override
  public void beginFrame() {
    renderDevice.beginFrame();
    colorChanged = false;
    this.updateClip(true, absoluteClip.x0, absoluteClip.y0, absoluteClip.x1, absoluteClip.y1);
  }
```

This works but as you can see if a new clip is set and is littler than the first the screen will not clear the area outside it ( sice it only clears the screen inside the clip ). So i could put a call to clear method like this.

``` java
//NiftyRenderEngineImp
public void setAbsoluteClip(int x,int y,int w,int h){
        this.absoluteClip = new Clip(x,y,x+w,h+y);
}

@Override
  public void beginFrame() {
    renderDevice.beginFrame();
    colorChanged = false;
 this.clear();
    this.updateClip(true, absoluteClip.x0, absoluteClip.y0, absoluteClip.x1, absoluteClip.y1);

  }
```

But this is not the intended behavior of beginFrame method. I don't know an other possibility would be this : 

``` java
@Override
// now nifty render method only call beginFrame 
  public void beginFrame(boolean clear) {
    renderDevice.beginFrame();
    colorChanged = false;
if(clear){
    this.clear(); 
   }
    this.updateClip(true, absoluteClip.x0, absoluteClip.y0, absoluteClip.x1, absoluteClip.y1);

  }
```

Honestly I don't like these solutions very much... what do you think ? By the way with java2d render works ( sice it not reset the clip each beginFrame() ) and nifty-editor soon will have a nice resolution control and zoom in and zoom out feature . :smile:

**Comment by void256** [comment]
clear() should always work without clip. So when clear() is being called you have to (temporarily) disable the clipping rectangle?

And if someone sets an absoluteClip() then this clip rectangle will automatically be the default clipping rectangle even when it is being reset in beginFrame(). I mean it will not be reset to nothing when someone has called setAbsoluteClip() before but it will be set to the absolute clipping rectangle automatically in this case.

**Comment by relu91** [comment]
> And if someone sets an absoluteClip() then this clip rectangle will automatically be the default clipping rectangle even when it is being reset in beginFrame(). I mean it will not be reset to nothing when someone has called setAbsoluteClip() before but it will be set to the absolute clipping rectangle automatically in this case.

Yes but to achieve that we need or change each render to know what is the current absolute clip or change nifty.render(true) method like this :

``` java
 public void render(final boolean clearScreen){
renderEngine.beginFrame();
    if (clearScreen) {
      renderEngine.clear();
    }
    renderEngine.applyAbsoluteClip();//Need to apply the clip here 

    if (currentScreen != null) {
      currentScreen.renderLayers(renderEngine);
    }

    if (exit) {
      renderEngine.clear();
    }
    renderEngine.endFrame();

    // now that the frame is complete we can reset the render device in case of the resolution change
    if (resolutionChanged) {
      resolutionChanged = false;
      displayResolutionChanged();
    }
}
```

This is the solution that i prefer , I'm trying to do less changes that I can. Other things like uses the enableClip method will simply not work because of the begin frame implementation in the renders.
Hope this is clearer now :confused:
