### ISSUE TITLE
TabControl BUG: Checkboxes are shown incorrectly  if they were changed on inactive Tab.

### ISSUE THREAD

**Issue by mifth** [nifty-gui/nifty-gui#139]
Hi Void256! 

I found a bug. If change a checkbox on inactive Tab so the checkbox will be shown with incorrect effect. For example:
CheckBox cb;  // is checked and a Tab is not active
cb.uncheck; // i unchecked the checkbox with my code when the Tab was inactive

Then when is switch the Tab on, i'll get checked checkbox. This is the bug.
I hope I explained it pretty clear. If you have questions just ask.

Tested with nifty 1.3.3.

Thanks.

**Comment by mifth** [comment]
Or possibly this is CheckBox bug. If i make check()/uncheck() to the checkBox on inactive Tab/Panel, then i'll get incorrect Checkbox Effect.

**Comment by void256** [comment]
@mifth Thanks for pointing that out. That was indeed a bug in the Checkbox :smile: Can you confirm that this works now better with 1.3.4-SNAPSHOT or 1.4.0-SNAPSHOT? Thanks!

**Comment by mifth** [comment]
@void256  hello, thanks a lot! I can test it but i need a compiled niftyGui lib. 
Can you point me into compiled SNAPSHOT?

**Comment by void256** [comment]
You can find them in the Maven repository: http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/nifty/1.3.4-SNAPSHOT/

**Comment by mifth** [comment]
@void256 i tried these builds:
nifty-1.3.4-20130922.123309-8.jar   22-Sep-2013 12:33   525K  
nifty-1.4.0-20130922.124754-67.jar  22-Sep-2013 12:48   526K     

But it seems they have no this fix https://github.com/void256/nifty-gui/commit/1513a2e8f77ec420ac8febda30a68555279cba0e
I need more new builds.. :(

**Comment by void256** [comment]
Ah, crap! My mistake! :smile: The fix is not in the core nifty jar but in the nifty-default-controls jar since it was a bug in the CheckBox control which lives there. You'll need the latest of these: http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/nifty-default-controls/1.3.4-SNAPSHOT/ of course.

Sorry about that :sunglasses:

**Comment by mifth** [comment]
@void256 Fixed!
I tested this build nifty-default-controls-1.3.4-20130922.123512-8.jar  22-Sep-2013 12:35   263K

Thank you a lot!

**Comment by void256** [comment]
Excellent! Thanks for reporting, testing and confirming! :smile:
