### ISSUE TITLE
tabGroup.removeTab

### ISSUE THREAD

**Issue by fbucur** [nifty-gui/nifty-gui#143]
Hey Void,

It seems the removeTab method removes the right panel but the wrong button. It actually removes the previous button instead the right one. Of course if you remove the first tab, no button is removed, but the first panel is!

Thanks for checking this out!

fbucur

**Comment by fbucur** [comment]
It seems after jumping to a different screen and back it is displayed correctly. Maybe this helps.

EDIT: unless it's the first tab removed, in which case you get a ghost tab at the end captioned same as the last tab and of course with no panel attached.

**Comment by void256** [comment]
@mkaring want to take a look? :smile:

**Comment by mkaring** [comment]
I fixed this with the last pull request I send you.

**Comment by void256** [comment]
Oh, great! I couldn't relate the two things. Great work again @mkaring !

@fbucur any chance you can test this with a nightly build of Nifty 1.4 so that you can confirm it works now?

**Comment by fbucur** [comment]
I'll try and let you know. Thanks guys!

fbucur
