### ISSUE TITLE
Simple example Nifty JOGL

### ISSUE THREAD

**Issue by elect86** [nifty-gui/nifty-gui#163]
Hi, I am trying to get a simple example with Nifty working, but I can't

/*
- To change this template, choose Tools | Templates
- and open the template in the editor.
  */
  package test;

import com.jogamp.opengl.util.FPSAnimator;
import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.batch.BatchRenderDevice;
import de.lessvoid.nifty.nulldevice.NullSoundDevice;
import de.lessvoid.nifty.renderer.jogl.input.JoglInputSystem;
import de.lessvoid.nifty.renderer.jogl.render.batch.JoglBatchRenderBackendCoreProfile;
import de.lessvoid.nifty.spi.render.RenderDevice;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.media.opengl.GL3;
import javax.media.opengl.GLAutoDrawable;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLEventListener;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLCanvas;
import de.lessvoid.nifty.spi.time.TimeProvider;

/**
 *
- @author gbarbieri
  */
  public class Test2 implements GLEventListener {
  
  private GLCanvas canvas;
  private int imageWidth;
  private int imageHeight;
  private Nifty nifty;
  private JoglInputSystem inputSystem;
  private RenderDevice renderDevice;
  
  /**
  - @param args the command line arguments
    */
    public static void main(String[] args) {
    
    Test2 test2 = new Test2();
    
    Frame frame = new Frame("Test2");
    
    frame.add(test2.canvas);
    
    frame.setSize(test2.canvas.getWidth(), test2.canvas.getHeight());
    
    final FPSAnimator fPSAnimator = new FPSAnimator(test2.canvas, 30);
    
    frame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent windowEvent) {
            fPSAnimator.stop();
            System.exit(0);
        }
    });
    
    fPSAnimator.start();
    
    frame.setVisible(true);
    }
  
  public Test2() {
  
  ```
  initGL();
  ```
  
  }
  
  private void initGL() {
  
  ```
  imageWidth = 800;
  imageHeight = 600;
  
  GLProfile profile = GLProfile.get(GLProfile.GL3);
  
  GLCapabilities capabilities = new GLCapabilities(profile);
  
  canvas = new GLCanvas(capabilities);
  
  canvas.setSize(imageWidth, imageHeight);
  
  canvas.addGLEventListener(this);
  ```
  
  }
  
  @Override
  public void init(GLAutoDrawable drawable) {
  
  ```
  renderDevice = new BatchRenderDevice(new JoglBatchRenderBackendCoreProfile(), 2048, 2048);
  
  inputSystem = new JoglInputSystem();
  ```

//        canvas.addMouseListener(inputSystem);

```
    nifty = new Nifty(renderDevice, new NullSoundDevice(), inputSystem, new TimeProvider() {

        @Override
        public long getMsTime() {

            return System.currentTimeMillis();
        }
    });

    nifty.fromXmlWithoutStartScreen("test/helloworld.xml");

    canvas.setAutoSwapBufferMode(true);
}

@Override
public void dispose(GLAutoDrawable drawable) {
}

@Override
public void display(GLAutoDrawable drawable) {
    System.out.println("display");

    GL3 gl3 = drawable.getGL().getGL3();

    gl3.glClearColor(1.0f, 1.0f, 1.0f, 1.0f);
    gl3.glClearDepthf(1.0f);
    gl3.glClear(GL3.GL_COLOR_BUFFER_BIT | GL3.GL_DEPTH_BUFFER_BIT);

    nifty.render(true);
}

@Override
public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {

    GL3 gl3 = drawable.getGL().getGL3();

    gl3.glViewport(x, y, width, height);
}
```

}

Caused by: java.lang.NoClassDefFoundError: org/jglfont/spi/BitmapFontRenderer
        at test.Test2.init(Test2.java:90)

Am I doing it right? If yes, where can I find the missing jar?

I am trying to figure it out from this hello world example

http://sourceforge.net/apps/mediawiki/nifty-gui/index.php?title=Hello_World_Example

In addition in the "examples for JOGL", he does something like

window.addMouseListener(inputSystem);
    window.addKeyListener(inputSystem);

Where

window = GLWindow.create(new GLCapabilities(getProfile(mode)));

But if I try to do

canvas.addMouseListener(inputSystem);

It returns error..

**Comment by elect86** [comment]
Forget, I solved everything (multiple problems in cascade)

here you can find a minimale working example in JOGL

```
    /*
     * To change this template, choose Tools | Templates
     * and open the template in the editor.
     */
    package test;

    import com.jogamp.newt.opengl.GLWindow;
    import com.jogamp.opengl.util.FPSAnimator;
    import de.lessvoid.nifty.Nifty;
    import de.lessvoid.nifty.batch.BatchRenderDevice;
    import de.lessvoid.nifty.nulldevice.NullSoundDevice;
    import de.lessvoid.nifty.renderer.jogl.input.JoglInputSystem;
    import de.lessvoid.nifty.renderer.jogl.render.batch.JoglBatchRenderBackendCoreProfile;
    import de.lessvoid.nifty.spi.render.RenderDevice;
    import javax.media.opengl.GL3;
    import javax.media.opengl.GLAutoDrawable;
    import javax.media.opengl.GLCapabilities;
    import javax.media.opengl.GLEventListener;
    import javax.media.opengl.GLProfile;
    import de.lessvoid.nifty.spi.time.TimeProvider;

    /**
     *
     * @author gbarbieri
     */
    public class Test2 implements GLEventListener {

        private GLWindow glWindow;
        private int imageWidth;
        private int imageHeight;
        private Nifty nifty;
        private JoglInputSystem inputSystem;
        private RenderDevice renderDevice;

        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {

            Test2 test2 = new Test2();
        }

        public Test2() {

            initGL();
        }

        private void initGL() {

            imageWidth = 1024;
            imageHeight = 768;

            GLProfile profile = GLProfile.get(GLProfile.GL3);
            GLCapabilities capabilities = new GLCapabilities(profile);
            glWindow = GLWindow.create(capabilities);

            glWindow.setAutoSwapBufferMode(true);
            glWindow.setSize(imageWidth, imageHeight);

            glWindow.addGLEventListener(this);

            FPSAnimator animator = new FPSAnimator(glWindow, 60, false);

            glWindow.setTitle("Test2");
            glWindow.setVisible(true);

            animator.start();
        }

        @Override
        public void init(GLAutoDrawable drawable) {

            renderDevice = new BatchRenderDevice(new JoglBatchRenderBackendCoreProfile(), 2048, 2048);

            inputSystem = new JoglInputSystem();

            glWindow.addMouseListener(inputSystem);
            glWindow.addKeyListener(inputSystem);

            nifty = new Nifty(renderDevice, new NullSoundDevice(), inputSystem, new TimeProvider() {
                @Override
                public long getMsTime() {

                    return System.currentTimeMillis();
                }
            });

            nifty.fromXml("test/helloworld.xml", "start");
        }

        @Override
        public void dispose(GLAutoDrawable drawable) {
            System.exit(0);
        }

        @Override
        public void display(GLAutoDrawable drawable) {

            nifty.update();
            nifty.render(true);
        }

        @Override
        public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {

            GL3 gl3 = drawable.getGL().getGL3();

            gl3.glViewport(x, y, width, height);
        }
    }
```

helloworld.xml

```
 <?xml version="1.0" encoding="UTF-8"?>
 <nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
 www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
 sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
     <screen id="start">
         <layer childLayout="center">
             <text font="aurulent-sans-16.fnt" color="#ffff"
       text="Hello World!" />
         </layer>
     </screen>
 </nifty>
```

**Comment by void256** [comment]
Nice. Great that you found the problem yourself ;)

There are more Jogl-examples here: https://github.com/void256/nifty-gui/tree/1.4/nifty-examples-jogl/src/main/java/de/lessvoid/nifty/examples/jogl
