### ISSUE TITLE
Text wrapping in the Chat / ListBox control

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [nifty-gui/nifty-gui#169]
In [nifty-chat-control.xml](https://github.com/void256/nifty-gui/blob/1.4/nifty-controls/src/main/resources/nifty-controls/nifty-chat-control.xml#L33) I see the line:

``` xml
<control id="#chat-line-text" name="label" align="left" textHAlign="left" height="$chatLineHeight" wrap="true" />
```

Note the wrap=true
Now if I give #chatBox horizontal=off, the scroll bar is hidden, but the text does not wrap.

I am trying to understand why this is not working, what I am guessing is:
1. Even though the scroll bar is hidden, the width of the label is still just as large as its text. And thus the only effect horizontal=off has, is making the scroll bar invisible
2. The code that does the wrapping is not able to determine the width

Now even if above would work, it appears that the "displayItems" attribute in the ListBox control is used to create the given number of controls that the text then cycles through. Aka there is no "real" scrolling.

Would it be possible to get wrapping to work using ListBox, or would I be better off implementing some kind of scrollable text control myself? 
This would basically be a big <text/> element that displays its text at an offset and clips lines that are scrolled half way (glScissor?).

**Comment by void256** [comment]
Yes, that's not supported. There are only displayItems number of controls created internally which have the same height each: http://hub.jmonkeyengine.org/forum/topic/nifty-gui-chat-builder-control-word-wrapping/#post-189242

You would be better of to use your own solution for the time being.
