### ISSUE TITLE
can't find xml schema

### ISSUE THREAD

**Issue by ogli81** [nifty-gui/nifty-gui#171]
The file "http://nifty-gui.sourceforge.net/nifty-1.3.xsd" is not available. How can I find it?

Inside Nifty.java, what does this mean ?
<code> loader.loadNiftyXml("nifty.nxs", </code>

I cannot find information on this (schema?), I assume it might be in the .xsd?

Thanks,
Ogli

**Comment by void256** [comment]
The namespace for 1.4 has now been changed to "http://nifty-gui.lessvoid.com/nifty-gui" and this URL is actually available - and it contains a great explanation of what's going on :sunglasses:

The "nifty.nxs" is Niftys build-in do-it-yourself poor-mans version of XML-Schema (XSD) which Nifty uses to connect to the XPP3 parser in a somewhat flexible way. It's used to simplify parsing of XML internally. At the time I invented it it seemed like a great idea but in retrospect that was a mistake. It's too complicated and it kinda duplicates the information already available in the XSD. The XSD is the more relevant information.

The nxs is only for hardcore Nifty hackers ... well, I hope I never have to modify any of it though! Heh :smile:

**Comment by ogli81** [comment]
Hm, I'm using 1.3.3 with the jME SDK (a frozen stable version of jME with Netbeans plugins).
Also I'm reading the 1.3.2 manual and the git repo that I checked out is the 1.3 branch too.

If you can give me that old .xsd, I won't ask any 1.3 questions here anymore. Promise.

Hopefully the next SDK bundle doesn't have 1.3, but 1.4 support for Nifty.
And I also hope that the interface will only have more functions, not drop any of that 1.3.2 / 1.3.3?

**Comment by ogli81** [comment]
Nevermind, I found it in the nifty.jar for jME.
There is a "nifty-1.3.xsd" and a "nifty.nxs".

**Comment by ogli81** [comment]
By the way, I would like to review the English of the next manual version.
My English is very good and I found some grammar and spelling errors in the current version.
Also I'm a native German speaker so that I could translate any of your original German sentences quite easily.

**Comment by void256** [comment]
Sorry, forgot to answer you ^^

The manual is available in the github repo: https://github.com/void256/nifty-gui/tree/1.4/nifty-core/manual as .pdf and as .pages document. Yes, currently you would require Apple pages to edit it.

There is not yet a manual for 1.4
