### ISSUE TITLE
ListBox.addAllItems() should use Collection instead of List argument type.

### ISSUE THREAD

**Issue by smirnovegorv** [nifty-gui/nifty-gui#177]
Currently this method requires a java.util.List parameter, however it does not use any list-specific functionality. This is slightly inconvenient when a user needs to show contents of some other collection, as requires additional wrapping.

**Comment by void256** [comment]
Changed to Collection now. See commit 7f68593185c4aa91581aa68a2bac21fd20dbedd1 for details.
