### ISSUE TITLE
MouseMoved/Hover broken in JoglInputSystem

### ISSUE THREAD

**Issue by telamon** [nifty-gui/nifty-gui#18]
I was playing around with some effects late night and noticed that the hover effect didn't act on mouse-hover but on mouse-click.
I ended up tracing the  mouse hover and mouse moved events and realized that they're not sent as they should be.

As of writing no mouse events are delegated to nifty unless mousebutton 1 is down in the JoglInputSystem.
Having had a quick peek at the source I figured it's [line 53](https://github.com/void256/nifty-gui/blob/1.3/nifty-renderer-jogl2/src/main/java/de/lessvoid/nifty/renderer/jogl/input/JoglInputSystem.java#L53) that prevents plain mouse movement events
to reach Nifty unless mouse button 1 is down. 

I've noticed that there is a commit that explicitly adds that behaviour to the MouseMoved handler:
[Commit 894a8195](https://github.com/void256/nifty-gui/commit/894a81951d081a241439e362c255c0965f7740a9)

Could it be a  bug in that commit or will MouseDragged gestures break if the If-case were to be omitted? 
I'll check it out later this evening.

**Comment by telamon** [comment]
I managed to squeeze in some time and adderess this issue

```
if (mouseEvent.getButton() == MouseEvent.BUTTON1) {
    mouseEvents.add(new MouseEventData(mouseEvent.getX(), mouseEvent.getY(), true, 0));
}
```

When i disabled the above if-statement, the "drag'n'drop" indeed stopped working(as mentioned by the blamed commit) but my hover elements came to life!
I belive the problem is that there's an unintentional `true` parameter there.
So i simply added an else block that contained a `false` an that did the trick!

Both DragNDrop and Hover works flawlessly! :)
And suddenly all controls felt more responsive as they came to life, can't imagine why i did't notice the lack of hover events until-now.

Here's my patch/fix:
[Commit fb67ee27](https://github.com/telamon/nifty-gui/commit/fb67ee279ab511959621858ec0687b849190f8e3)

**Comment by void256** [comment]
Looks good! :) Do you need to send a merge request or can I somehow merge it on my own?

**Comment by telamon** [comment]
I can send a merge request, merging it on your own would require you to add my fork as a remote location on your local git repo and then merge my patch branch into yours. Pull requests are simply neater =D
Closing this, will open a pullrequest.
