### ISSUE TITLE
Remove AWT references from JoglMouseCursor

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#206]
Use GLWindow.setPointerIcon() and remove any AWT references from JoglMouseCursor as I did here:
https://github.com/Renanse/Ardor3D/blob/79afcc91c733f9f2cdd8a29d738b8ae185883d98/ardor3d-jogl/src/main/java/com/ardor3d/input/jogl/JoglNewtMouseManager.java#L47

**Comment by bgroenks96** [comment]
I will try to get this fixed ASAP. It has been open for quite some time.

Thanks Julien.

**Comment by ghost** [comment]
You're welcome.
