### ISSUE TITLE
setConstraint to default won't have any effects

### ISSUE THREAD

**Issue by relu91** [nifty-gui/nifty-gui#218]
If you set a constraint with SizeValue.def() the layout doesn't take care about it. For example in absolute layout if you setConstraintY(SizeValue.px(200)) and then setConstraintY(SizeValue.def()) the excepted behavior should be to see the element in y=0 location but it isn't even if you call layoutElements() in the parent of element. 

the problem could be in these line on absolutelayoutManager : 

 if (cons.getY().hasValue()) {
        box.setY(rootBoxY + cons.getY().getValueAsInt(rootBoxHeight));
  }

Maybe I'll try to change these :+1:

**Comment by void256** [comment]
looks good! thanks for the fix too :smile:
