### ISSUE TITLE
Alternative to XML

### ISSUE THREAD

**Issue by sirinath** [nifty-gui/nifty-gui#224]
Is it possible to to have a alternative to XML perhaps using Groovy Builders or pure Java DSL

**Comment by void256** [comment]
There is a whole chapter about that in the manual. See chapter "Java GUI" on Page 21 here: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/manual/nifty-gui-the-manual-1.3.2.pdf

Does that answer your question? :smile:

**Comment by void256** [comment]
I'll close this for now - feel free to re-open if you're not happy with the answer! Thanks!

**Comment by sirinath** [comment]
This is pretty good.
