### ISSUE TITLE
Avoid currentTimeMillis() in the source code

### ISSUE THREAD

**Issue by Zubnix** [nifty-gui/nifty-gui#226]
When calculating delta times in Java currentTimeMillis() is considered bad practice as it is tied the actual date time of the OS, ie when the date time is changed on OS level, currentTimeMillis() will yield different values.

Instead use nanoTime(), this will not only give more accurate timing but relies on OS kernel time which is independent of the user OS date time.

If the goal is to remain java 1.4 compatible then of course nanoTime() is not an option.

**Comment by void256** [comment]
For the most part this was already handled very well in Nifty with the [TimeProvider](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/spi/time/TimeProvider.java) interface. When you construct a new Nifty instance you have to provide a TimeProvider instance. Using a [AccurateTimeProvider](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/spi/time/impl/AccurateTimeProvider.java) will already use System.nanoTime(). [FastTimeProvider](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/spi/time/impl/FastTimeProvider.java) will use `System.currentTimeMillis();` - so it's really up to you what kind of Time you use :smile:

However, there were a couple of places in Nifty remaining that used System.currentTimeMillis() directly. I've changed them to use AccurateTimeProvider instead with commit d75e0d2.

Thanks for pointing that out! I'll close this issue now.
