### ISSUE TITLE
Java2D Renderer Effect Issues

### ISSUE THREAD

**Issue by fbnz156** [nifty-gui/nifty-gui#229]
Focusing on a control with an effect, e.g. pulsate will for some reason give this same effect to the next element on the tree. For example, instead of the | flickering in the text box control, the | AND the entire next control in the tree flickers. This happens with all effects.

**Comment by fbnz156** [comment]
I can't be bothered submitting a pull request, but could somebody submit the following changes:
In RenderDeviceJava2dImpl

Find
graphics.setComposite(AlphaComposite.getInstance(
                AlphaComposite.SRC_OVER, color.getAlpha()));
(There'll be 2 of them)
For each one:
Above add
Composite comp = graphics.getComposite();
Below add
graphics.setComposite(comp);

This fixes the issue.

**Comment by relu91** [comment]
Thanks! I've just sent the pull request r :+1:  . This was an annoying bug that also effected nifty-editor but I didn't find any solution ! So yeah really thanks :smile:
