### ISSUE TITLE
Creating a custom control ImageButton

### ISSUE THREAD

**Issue by WeirdAlien** [nifty-gui/nifty-gui#234]
I have an easy one here. I want to make a custom ImageButton that will switch image when clicked. It shows up but it did not react to the mouse click, only to a keyEvent under the inputEvent() function. 

I would have to pass a  NiftyMousePrimaryClickedEvent as an argument to the function but then, it wouldn't implement the Controller class... I dont want to use the @NiftyEventSubscriber either because I want to keep this action internal to my button since they will all behave this way. What am I doing wrong?

``` java
public class ImageButtonControl implements Controller {

    private Nifty nifty;
    private Screen screen;
    private Element img1;
    private Element img2;
    private Properties properties;
    private boolean isPressed = false;
    private ImageRenderer render1;
    private NiftyImage imageNifty1;
    private NiftyImage imageNifty2;
    private FocusHandler focusHandler;

    @Override
    public void bind(
      final Nifty nifty,
      final Screen screenParam,
      final Element element,
      final Properties parameter,
      final Attributes controlDefinitionAttributes) {
        this.nifty = nifty;
        this.screen = screenParam;
        this.properties = parameter;
        img1 = element.findElementByName("image-1");
        img2 = element.findElementByName("image-2");
        initImages(this.nifty, this.screen, properties.getProperty("img-1"),properties.getProperty("img-2"));
        //focusHandler = screenParam.getFocusHandler();
        System.out.println("Initialisation completed."); }

    @Override
    public void init(Properties prprts, Attributes atrbts) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onStartScreen() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onFocus(final boolean getFocus) {
        //super.onFocus(getFocus);
         System.out.println("---Clicked event focus---");
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean inputEvent(NiftyInputEvent inputEvent) {
        System.out.println("---Clicked event focus---");
        return false;
    }


    public void switchImage(){
       //ImageRenderer imageRenderer = img1.getRenderer(ImageRenderer.class);
        if(isPressed){
            isPressed = false;
            //img1.show();
            //img2.hide();
            System.out.println("Clicked event");
        }else{
            isPressed = true;
            //img1.hide();
            //img2.show();
            System.out.println("Clicked event");
        }
    }

    private void initImages(Nifty nifty, Screen screen, String imgPath1, String imgPath2) {
        NiftyRenderEngine renderEngine = nifty.getRenderEngine();
        imageNifty1 = renderEngine.createImage(screen,imgPath1,false);
        imageNifty2 = renderEngine.createImage(screen,imgPath2,false);
    }
  }
```

**Comment by relu91** [comment]
If I don't misunderstood , subscribing with @NiftyEventSubscriber it's ok , because you're not actually tell to the world what is your inner event . With that annotation you are simply saying to nifty intance :" hey instead to call the screen controller, call this method when the button is clicked" . Since nifty will automatically subscribe your method I dont see any "visibility" problem . Otherwise if you use xml to define your control you could use the interact tag and specify which method nifty should be call , but It's actually equivalent to annotation way  .

**Comment by WeirdAlien** [comment]
Ahh thank you!! I was using the interact on the panel instead of the actual image on the XML...

**Comment by WeirdAlien** [comment]
I close this too fast... I'm now stuck because I don't know how to hide an actual image from an image element of the XML... What am I doing wrong in the switchImage function?  

Because I get this error:
May 23, 2014 9:21:33 AM de.lessvoid.nifty.NiftyMethodInvoker callMethod
WARNING: Exception: java.lang.reflect.InvocationTargetException
May 23, 2014 9:21:33 AM de.lessvoid.nifty.NiftyMethodInvoker logException
WARNING: sun.reflect.NativeMethodAccessorImpl invoke0 (NativeMethodAccessorImpl.java:-2)
May 23, 2014 9:21:33 AM de.lessvoid.nifty.NiftyMethodInvoker logException
WARNING: sun.reflect.NativeMethodAccessorImpl invoke (NativeMethodAccessorImpl.java:57)
May 23, 2014 9:21:33 AM de.lessvoid.nifty.NiftyMethodInvoker logException
WARNING: sun.reflect.DelegatingMethodAccessorImpl invoke

**Comment by WeirdAlien** [comment]
Awe nevermind, I passed the name attribute to the findElementByName() instead of the Id attribute... It's weird that they name the function like that since you have to pass the ID... I'll let this open until they read it :P

**Comment by relu91** [comment]
yep , it actually is bit ambiguous since controls have the name attribute , but I'm glad to hear that finally it works!

**Comment by void256** [comment]
Just for the record this question was posted at Stackoverflow as well. See my answer here: http://stackoverflow.com/a/23847018/1717169  (I know, the issue is solved already. Just for reference)
