### ISSUE TITLE
[Help needed] Only getting a black screen

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#243]
_Since I couldn't find a better place to ask for help, I am now opening a new issue - I hope you don't mind..._

I recently discovered NiftyGUI and wanted to try it out in one of my projects. Since it is neither a LibGDX, nor Slick2D, but a LWJGL based game I just imported the lwjgl-renderer into my project.

After trying to run a first "hello world" test, I am only getting a black screen. In fact, it is not rendering anything at all. When I turned on the debug mode though, I showed me that it indeed tried to render the elements (or it did and I just can't see it ...).

To make things a bit easier, I created a UiManger class that holds the nifty instance and prepares the stuff I need (stripped down version):

``` java
public class UiManager {
    private final Nifty nifty;
    private final BatchRenderDevice renderDevice;


    public UiManager() {
        // Create Nifty GUI instance
        renderDevice = new BatchRenderDevice(LwjglBatchRenderBackendFactory.create());

        nifty = new Nifty(
                renderDevice,
                new NullSoundDevice(),
                new LwjglInputSystem(),
                new LWJGLTimeProvider()
        );

        nifty.setDebugOptionPanelColors(true);
        setDebugMode(true);
    }

    public Nifty getNifty() {
        return nifty;
    }

    public void setDebugMode(boolean debug) {
        renderDevice.setDisplayFPS(debug);
        nifty.setDebugOptionPanelColors(debug);
    }

}
```

I am creating my screens like this (using some kind of wrapper for my own code):

``` java
public abstract class Canvas {
    private final UiManager uiManager;
    private final Screen screen;

    private final boolean clearScreen;


    protected Canvas(UiManager uiManager, String id, boolean clearScreen) {
        this.uiManager = uiManager;
        this.clearScreen = clearScreen;

        // Create a screen builder and use the canvas' build method
        this.screen = new ScreenBuilder(id) {
            {
                Canvas.this.build(this);
            }
        }.build(getNifty());
    }

    protected abstract void build(ScreenBuilder builder);

    protected Nifty getNifty() {
        return uiManager.getNifty();
    }

    protected Screen getScreen() {
        return screen;
    }

    public final void render() {
        // Update and render Nifty
        getNifty().update();
        getNifty().render(clearScreen);
    }

}
```

The Hello-World example screen has the following code (the drawScreenMethod is a method that gets called by my original code):

``` java
public class MainMenuScreen extends GuiScreen {
    private final Canvas canvas;


    public MainMenuScreen(UiManager uiManager) {
        this.canvas = new MainMenuCanvas(uiManager);
    }

    @Override
    public void drawScreen(float delta) {
        canvas.render();
    }


    private class MainMenuCanvas extends Canvas {

        private MainMenuCanvas(UiManager uiManager) {
            super(uiManager, "start", true);
        }

        @Override
        protected void build(ScreenBuilder builder) {
            builder.layer(new LayerBuilder("layer") {{
                backgroundColor("#003f");
                childLayoutCenter();

                panel(new PanelBuilder() {{
                    id("panel");
                    childLayoutCenter();
                    height("25%");
                    width("80%");
                    alignCenter();
                    valignCenter();
                    backgroundColor("#f60f");
                    padding("10px");

                    panel(new PanelBuilder() {{
                        childLayoutHorizontal();
                        alignCenter();
                        valignCenter();
                        width("100%");

                        text(new TextBuilder() {{
                            text("Hello World!!!");
                            font("averia-regular.ttf");
                            color("#000f");
                            width("*");
                            alignCenter();
                            valignCenter();
                        }});
                    }});
                }});
            }});
        }

    }

}
```

Like I already stated above, when I try to run the game I am only getting a black screen; this is what the console shows me though:

```
[...]
Jul 13, 2014 1:47:55 PM de.lessvoid.nifty.render.batch.BatchRenderBackendInternal useHighQualityTextures
INFO: Using low quality textures (no filtering).
Jul 13, 2014 1:47:55 PM de.lessvoid.nifty.render.batch.BatchRenderBackendInternal fillRemovedImagesInAtlas
INFO: Not filling in removed images in atlas.
Jul 13, 2014 1:47:56 PM de.lessvoid.nifty.render.batch.BatchRenderDevice createTextureAtlas
INFO: Created a new texture atlas (atlas texture id: 3).
Jul 13, 2014 1:47:56 PM de.lessvoid.nifty.render.batch.BatchRenderDevice nextTextureAtlas
INFO: Switched atlases to atlas texture with id: 3.
[...]
Jul 13, 2014 1:48:07 PM de.lessvoid.nifty.controls.dynamic.ScreenCreator createScreen
WARNING: Missing ScreenController for screen [start] using DefaultScreenController() instead but this might not be what you want.
Jul 13, 2014 1:48:12 PM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [fps.png] uploaded to atlas (atlas texture id: 3).
Jul 13, 2014 1:48:12 PM de.lessvoid.nifty.render.batch.BatchRenderImage uploadImageToAtlas
INFO: Image [AveriaSans-Regular-16-0-256-0] uploaded to atlas (atlas texture id: 3).
FPS: 26 (38.461540 ms), Total Tri: 182 (Text: 182), Total Vert: 364 (Text: 364), Batches: 1
FPS: 32 (31.250000 ms), Total Tri: 182 (Text: 182), Total Vert: 364 (Text: 364), Batches: 1
FPS: 30 (33.333332 ms), Total Tri: 182 (Text: 182), Total Vert: 364 (Text: 364), Batches: 1
FPS: 30 (33.333332 ms), Total Tri: 182 (Text: 182), Total Vert: 364 (Text: 364), Batches: 1
[...]
```

Although I am not seeing anything at all, I am also noticing a very strange "flickering" when I move the window around, almost like the game is lagging. Is there some kind of VSync system in place?"

**_EDIT**_
After some more fiddling around with Nifty, I just tried to use an XML file out of curiosity; its content was just copied over from the manual (It's the very first "hello world" example), and I got the following image:
![screen shot 2014-07-13 at 14 58 51](https://cloud.githubusercontent.com/assets/429147/3564587/c836e2a0-0a8d-11e4-8523-748141f7f6d4.png)
Can it be that I need to clear some openGL stuff before calling Nifty.render()? I thought the library would clear all the bits, and set up the viewport itself? The result looks extremely strange to me; making it all pink and all :)

**Comment by spaceemotion** [comment]
I also noticed that the debug string gets created even if the debug mode is disabled. Is that intended?

**Comment by void256** [comment]
You have to make sure you're in 2D Ortho mode when calling Niftys render() method. Nifty assumes YOU set up everything for rendering 2D stuff.

You can find code how to do that in the examples, like here: https://github.com/void256/nifty-gui/blob/1.4/nifty-examples/src/main/java/de/lessvoid/nifty/examples/LwjglInitHelper.java#L200

If you render other things before or after Nifty then you have to make sure the GL states or saved/restored correctly.

A good way to start is the https://github.com/void256/nifty-gui/tree/1.4/nifty-examples project. It's using LWJGL so it should be familar to you. Maybe get the examples project running first and then start from there?

PS: Asking for help here with an issue is perfectly fine! :)

**Comment by spaceemotion** [comment]
ooookay, I think it is getting weirder and weirder…

I basically added those lines before the render method, but now the pink text only turned into red (magic!):

``` java
glViewport(0, 0, Display.getDisplayMode().getWidth(), Display.getDisplayMode().getHeight());

glClearColor(0, 0, 0, 1);
glClear(GL11.GL_COLOR_BUFFER_BIT | GL11.GL_DEPTH_BUFFER_BIT);

glEnable(GL11.GL_BLEND);
glBlendFunc(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA);
```

Btw, I am currently idling around in the IRC - if you want to give "live support" ;)

**Comment by spaceemotion** [comment]
Fixed by helping out in IRC ;)

**Comment by ghost** [comment]
@spaceemotion When you solve something, you should explain what you did to fix it.

**Comment by spaceemotion** [comment]
Well, turns out it was working after all and it was more like my fault, I just had the projection wrong PLUS i had the debug mode enabled (_facepalm_ - that added the random colours); so I fixed it like this:

``` java
int w = // get this from somewhere
int h = // get this from somewhere

GL11.glViewport(0, 0, w, h);
GL11.glMatrixMode(GL11.GL_PROJECTION);
GL11.glLoadIdentity();
GL11.glOrtho(0.0f, (float) w, (float) h, 0.0f, -9999.0f, 9999.0f);
GL11.glMatrixMode(GL11.GL_MODELVIEW);
GL11.glLoadIdentity();

nifty.update();
nifty.render(true);
```

I also forgot to do `nifty.resolutionChanged();` when I resized a windows - thats all ;)
