### ISSUE TITLE
SizeValue throwing exceptions for floating point percentage values

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#244]
If I interpret this\* snippet of the 1.4 changelog correctly, it says that some elements round SizeValues to get ints, but floats are still used internally. Which makes it a bit paradoxical that SizeValues now throw Exceptions when I attempt to make them take a float percentage, and since I rely on the floating parts to position many elements exactly, this is also quite annoying to me..
- Quote:
  Many classes in the effects and layout packages in nifty-core
  are using a method in the SizeValue class called getValue that returns a
  floating point value. The issue is not with this method itself per se,
  but with callers of the method, who really need an integer value, and
  cast the returned floating point value to an integer, effectively
  discarding everything to the right of the decimal. It can easily be
  verified that calling getValue and then casting to an integer returns
  incorrect values much of the time. This bug is now verified with a
  simple test in SizeValueTest. The bug rears its ugly head the worst when
  converting a simple pixel value of say "212px" from a SizeValue whose
  percent is set to 100, to a floating point pixel value, and then casting
  it to an integer: the result will always be 211 and NOT 212. There are
  countless other values that return a similar result when the SizeValue
  percent is set to 100.
- The solution to this error, which rectifies issues such as creating
  quads at off-by-one pixel sizes, is to change all callers of getValue
  that actually need an integer value to use the preexisting getValueAsInt
  method, BUT since it ALSO simply casts the floating point value of the
  getValue method to an integer, persisting the bug, we modify the
  getValueAsInt method to use Math.round, and round the result returned by
  getValue to the nearest integer instead of casting it. This returns much
  more correct values, and fixes the bug. This solution has been
  integration-tested without noticing the introduction of any other
  regressions.

Just for completion, here's an xml snippet that used to work perfectly in 1.3.2:
        <panel x="65%" y="1.5%" width="17.4%" height="5.67%" childLayout="center" >
          <interact onPrimaryClick="scrollUp()" />
          <text text="${dialog.configureKeys}" color="#000f" style="baby-base-font" />
        </panel>

```
    <panel x="15%" y="78.5%" width="20%" height="9%" childLayout="center" >
      <interact onPrimaryClick="close()" />
      <text text="${dialog.close}" color="#000f" style="baby-base-font" />
    </panel>
    <panel x="69%" y="78.5%" width="20%" height="9%" childLayout="center" >
      <interact onPrimaryClick="acceptChanges()" />
      <text text="${dialog.acceptChanges}" color="#000f" style="baby-base-font" />
    </panel>


    <panel x="65%" y="-6.67%" width="17.4%" height="5.67%" childLayout="center" >
      <interact onPrimaryClick="scrollDown()" />
      <text text="${dialog.settings}" color="#000f" style="baby-base-font" />
    </panel>
```

**Comment by ghost** [comment]
What exception are you getting?

**Comment by ghost** [comment]
You're interpreting the above explanation, which I wrote, incorrectly. `SizeValue` stores the value internally as an `int`. It allows you to **convert** it to a `float` by calling the method `getValue (final float range)`. But that's not the problem you're having anyway because you're not calling those methods in the first place.

If you give me the exception you're actually getting, I might be able to be of further assistance.

**Comment by HariboTer** [comment]
Of course, here you go:
java.lang.IllegalArgumentException: String value [5.67%] does not fit the required format.
    at de.lessvoid.nifty.tools.SizeValue.<init>(SizeValue.java:205)
    at de.lessvoid.nifty.loaderv2.types.apply.Convert.sizeValue(Convert.java:49)
    at de.lessvoid.nifty.elements.Element.initializeFromAttributes(Element.java:308)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyAttributes(ElementType.java:257)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:198)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.Nifty.createPopupFromType(Nifty.java:955)
    at de.lessvoid.nifty.Nifty.createAndAddPopup(Nifty.java:1091)
    at de.lessvoid.nifty.Nifty.createPopupWithStyle(Nifty.java:1083)
    at de.lessvoid.nifty.Nifty.createPopupWithStyle(Nifty.java:1060)
    at de.lessvoid.nifty.Nifty.createPopupWithId(Nifty.java:992)
    at de.lessvoid.nifty.Nifty.createPopup(Nifty.java:982)
...
Caused by: java.lang.NumberFormatException: For input string: "5.67"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.valueOf(Unknown Source)
    at de.lessvoid.nifty.tools.SizeValue.<init>(SizeValue.java:202)

**Comment by ghost** [comment]
@HariboTer The changes that caused your problem are here: https://github.com/void256/nifty-gui/commit/cda25ece363e8fa597751aca72afebc51f7e72b0

@mkaring changed this on December 26th, 2013. Previously, `Float.valueOf` was used for percentage conversions. I have no idea why he changed it to `Integer.valueOf` as the commit notes do not say.

@void256 I don't see any reason why we shouldn't accept `SizeValue` floating point width & height percentages, but I'm hoping that @mkaring can add some insight.

**Comment by ghost** [comment]
@HariboTer Prior to cda25ec, `SizeValue` did store the value as a `float`, so I apologize, as you did interpret that commit message correctly (as it was before Dec 26th, 2013).

**Comment by HariboTer** [comment]
No problem, thanks for your inquirations :-)

Now we just need @mkaring to justify for this crime against humanity (well, at least that part of it that wants to use floating point values for percentages) ;-P

**Comment by mkaring** [comment]
Well.

First off: `SizeValue` never stored floating-point values. It originally stored a `String` that was always parsed in case the value was requested. I changed this to store the actual value instead of the string. Now it happens that I considered a `int` value for both pixel and percent value fine grained enough to suite the general needs. Do you actually need floating point values there? Is the difference between 15% and 15.5% even visible?

If so the internal storage needs to be changed to a floating value without breaking the API.

**Comment by HariboTer** [comment]
- Do you actually need floating point values there? Is the difference between 15% and 15.5% even visible?

Unfortunately, yes, that is the case. My elements are placed on screen level, and considering an average span of 1000 pixels, 0.5% already makes a difference of 5 pixels, an offset that can become painfully visible when the GUI's layout and design is integrated into the background image :-S

**Comment by ghost** [comment]
@HariboTer If you need pixel-precise accuracy, consider using absolute layout values and enable auto scaling. It seems an abuse of relative measurements to demand pixel-precision. The whole point of percentages (as opposed to absolute values) is that they take up whatever space is available at runtime, which may change depending on other constraints.

Does that make sense? Specifying 15% for width, for example, is like saying "I don't care about pixel precision, just fill up 15% of the whatever the total ends up being." Not very precise. Even using a floating point value won't guarantee pixel-for-pixel accuracy, and if your design is based on this, you may have hair-pulling off-by-one pixel errors that appear sometimes but not other times.

Ask me how I know... ;-)

**Comment by HariboTer** [comment]
Actually, I can live with 1 pixel inaccuracy, probably even 2, but the average deviation of 5 would be deadly^^

**Comment by ghost** [comment]
@HariboTer Well that sounds more reasonable. I don't see any reason why we shouldn't have more accurate percentages, especially seeing that we used to have it.

**Comment by mkaring** [comment]
So in that case the internal storage of size value needs to be altered.

Edit: But I'd wait what @void256 has to say in this matter. ;-)

**Comment by ghost** [comment]
@HariboTer There. Sorry for making you wait so long ;-). This wasn't very difficult, I've just been very busy. I didn't add any overloaded SizeValue constructors or other methods to explicitly take a float due to lack of time, but someone should really add that eventually to provide full floating point support. This PR only addresses being able to specify floating point values in strings passed to SizeValue (either directly or via xml, etc), which should be enough to solve your original issue.

**Comment by HariboTer** [comment]
Great, thank you! Only question remaining to me is: Will there be a "hotfix" released (or a reupload of Nifty 1.4)? I wouldn't be much enthusiastic if I had to wait months for the next big Nifty release to get this fix (at least for me it is a fix, because it means that one of my most important screens won't crash any more) :-S

**Comment by void256** [comment]
nope

**Comment by HariboTer** [comment]
Is there any other way to get to it then?

**Comment by void256** [comment]
sure, a nightly 1.4.1-SNAPSHOT build from the maven repository should work pretty good

**Comment by void256** [comment]
http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/nifty/1.4.1-SNAPSHOT/?C=M;O=D

:smile:

**Comment by HariboTer** [comment]
Works like a charm, THANK YOU! :-D

**Comment by ghost** [comment]
@HariboTer You're welcome =).
