### ISSUE TITLE
Change on the nifty.gotoScreen()-initialization-routine

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#245]
Previously, letting nifty goto a screen had immediate effect, so I could work with it afterwards; now I had to put a forced update()-call behind it, which feels dirty, but it seems to work seamlessly and I don't have to quirk around seeking+rewriting all my initialization methods that try to grab a ScreenController after setting nifty to the corresponding screen. But if there is a nicer new approach to this whose declaration I missed, I would like very much to hear about it ;-)

```
    @Override
    public void init(GameContainer gc, StateBasedGame sbg) {
            GameData.getNifty().gotoScreen("mapEditor"); //GameData.getNifty().update(); <-- makes it work
            System.out.println("Current screen is: " + GameData.getNifty().getCurrentScreen().getScreenId()); //prints the id of the previous screen
            niftyInput = (MapEditorNiftyInput)GameData.getNifty().getCurrentScreen().getScreenController(); //throws an Exception - no surprise, since the previous screen controller is a completely different class
            //...
    }
```

**Comment by relu91** [comment]
Can't you init the screen in the onStartScreen method of "mapEditor" ? right? other wise if you need the mapEditor screen in your init method you could always get the screen from nifty instance and then go to that screen.

**Comment by void256** [comment]
There never was any guarantee that the gotoScreen will work immediately. That your code worked was more like a coincidence ..

What about using this new method to get the Screen directly:

``` java
  /**
   * get a specific screen.
   *
   * @param id the id of the screen to retrieve.
   * @return the screen
   */
  @Nullable
  public Screen getScreen(@Nonnull final String id) {
```

The Screen has a getter for the ScreenController too ...

Does that eventually help?

**Comment by HariboTer** [comment]
If it wasn't for some lucky coincidence from time to time, programmers would have a much harder time to get things working, wouldn't we?^^
But the method you named looks just perfectly suited for this issue, thank you! :-)
