### ISSUE TITLE
All my nifty hints have perished

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#246]
It seems like all my nifty hints have vanished out of this universe (they don't seem to think that appearing on the screen would be worth the effort)... all other hover effects survived, however.
Again some example xml that couldn't bear the update from 1.3.2 to 1.4:

```
  <panel id="#mainPanel" width="100%" height="100%" padding="0px,14px" style="baby-button#panel" visibleToMouse="true" focusable="true" controller="controls.DefaultInputHandler" >
        <image filename="$filename" imageMode="$imgMode" id="#buttonImage" />
            <interact onPrimaryClick="$onPrimClick" />
            <effect>
              <onHover name="hint" hintText="$hintText" hintStyle="baby-hint" />
            </effect>
      </panel>
```

**Comment by ghost** [comment]
I don't see any xml...

**Comment by HariboTer** [comment]
Theoretically it was there, but it looks like it wasn't shown because it wanted another linebreak before it. Sorry, it's fixed now.

**Comment by HariboTer** [comment]
Anyone having some insights on this for me? Or is the xml snippet still invisible for everyone except me?

**Comment by ghost** [comment]
I can see the xml but I have no idea what's wrong.

Your best bet is to start with working hint code (think nifty examples) and change one thing at a time to transform it to what you have above. (Make sure you include the xml control definition, the xml style, and the java controller when performing this process.)

That's what I do.

**Comment by HariboTer** [comment]
Sorry for the long silence, I was just too frustrated to get back to this. I just tried again with the most vanilla nifty I can think of.
This is the screen:

``` xml
<screen id="game" controller="main.GameStateNiftyInput" >
    <layer childLayout="center" >
      <panel width="20%" height="6%" align="right" valign="top" style="nifty-panel">
        <interact onClick="openGeneralMenu()" />
        <effect>
          <onHover name="hint" hintText="LALALALALALALA" />
        </effect>
      </panel>
    </layer>
</screen>
```

Simple, vanilla, and: Not working. I can see the panel, it is where it's supposed to be, and when I click it, the method is called, everything seems fine, BUT: there is no hint! Regardless whether I try to tell nifty to start them or let nifty handle it on its own: No hints. Just silence, a deep, hostile, outrageous nothing instead of the hint. And I seriously need these hints, because most of my GUI information is brought to the user via them.

And I have double- and triple-checked the code using the Nifty Examples:
https://github.com/void256/nifty-gui/tree/1.4/nifty-examples/src/main/java/de/lessvoid/nifty/examples/hint
https://github.com/void256/nifty-gui/blob/1.4/nifty-examples/src/main/resources/hint/hint.xml
and even plain copying of that xml doesn't help.

Maybe it's because I use Slick? We've had Slick-rendering getting artifacts before (black rectangles on custom mouse cursors), maybe something went wrong again?

@void256 Do you have an idea of what could cause this? I can only repeat, everything is fine, but even the slightest hint-code just does not appear, although it is (and was! before I updated to Nifty 1.4) perfectly valid xml.

**Comment by relu91** [comment]
Looking in to hint effect implementation there nothing fashion ... the hint will simply added to a layer and then shown when it is active. So it's hard that it could be a renderer issue... your best bet is to debug nifty code and see if the hinteffect is doing right. See the new article in the wiki about how working form source: https://github.com/void256/nifty-gui/wiki/Working-from-Source thanks to @3xp0n3nt .

@void256 by the way why it was used a standard layer ? Popup layer doesn't fit better in this case?

**Comment by ghost** [comment]
@relu91 A popup layer is a modal dialog, meaning it blocks all user input
from reaching anything else. This is not a desirable behavior for hints.

Aaron Mahan
Co-Founder & CEO
Forerunner Games, LLC
http://forerunnergames.com/
Peril: http://perilgame.com/

**Comment by relu91** [comment]
Oh right! nevermind then ;)

**Comment by HariboTer** [comment]
Thanks for your help!

I made an interesting find when I activated the debug panel colors. I remember, "back in ye good olde Nifty 1.3.2 (when things were working :-P)", everytime a new hint was shown, a new color got laid over the whole screen (because a new layer was used for a new hint), so everytime I hovered another element, the screen changed its general color.

This does not happen any more.
Only the first time I hover something, the screen color changes. Then I can hover my mouse cursor to death, the general color overlay does not change any more, and the hints don't appear anyway, no debug panel is visible for them either.

So, chances seem high that the hint might be created and added to the layer correctly, but on its way to the (Slick) renderer or the (Nifty) screen itself, the layer gets eaten (or defaced) by as greedy, insatiable bug that lingers somewhere in the Nifty library.

Do you know somebody who works with Slick2D and NiftyGUI 1.4? I would like to know if this problem can be confirmed for other projects too (because if not, I can go bury my damaged trust in programming altogether).

Unfortunately, while I can work my way with the Nifty API, I'm not familiar with the Nifty Code itself at all and odds are considerable that I would get more problems by trying to work with Nifty from source than I could solve this way, so it would be great if someone who actually <i>knows</i> the internal mechanics of Nifty could take a look at this.

**Comment by ghost** [comment]
@HariboTer I'm hacking on Nifty right now, if you give me an [SSCCE](http://sscce.org/) (basically the bare minimum of code needed to compile and run - because I'm not going to write code to try and approximate yours) I'll check it out. If it's a rendering issue, or a standard controls issue, it shouldn't be too difficult. If it's a Slick issue, well, I don't use Slick, so chances are slim.

Are you not receiving any logging errors or warnings?

**Comment by HariboTer** [comment]
As mentioned above, no errors, no warnings (if I had gotten some, we would probably be a few steps ahead in solving this issue).

I stripped the error down to its bones, here's a link to the source files (zipped to 2.52 KB^^) which don't need any more than the standard Nifty+Slick library environments: https://www.mediafire.com/?f921zamxoa0xqtl

**Comment by HariboTer** [comment]
@3xp0n3nt Can you confirm the hint problem or is my local file system messed up completely?

And thanks a lot for your efforts - so far it's the only chance for my hints to be revived at all :-S

**Comment by ghost** [comment]
@HariboTer I've been super busy, but I'll try and take a look as soon as I can. Sorry.

**Comment by HariboTer** [comment]
@3xp0n3nt No problem, I didn't mean to put you under pressure - luckily there's no deadline for this :-)

**Comment by ghost** [comment]
Well it's officially confirmed that hints are broken in the entire Nifty Gui library, lol. No more info yet.

**Comment by void256** [comment]
I can confirm that o_O Looking into it right now ... very strange

**Comment by ghost** [comment]
Well I've tracked down the specific file and commit that broke this, working on a fix...

**Comment by ghost** [comment]
Well, I've got a fix, but I'm not comfortable submitting it because it's indicative of deeper issues with the element show / hide effect system. @void256 I need to discuss this with you probably in IRC because it's pretty complicated and we need to figure out a sane solution. I don't want to put a bandaid on the hint system which would just be covering up this deeper bug.

**Comment by ghost** [comment]
I went ahead and PR'ed the fix anyway.

**Comment by void256** [comment]
I'm pretty sure this commit c8a6030e78225cb5dc7a4cc3aba22df686339b68 broke that! I knew it was kinda risky to change that :/

@3xp0n3nt Can you make a real pull request out of your commit? I'm not able to apply it otherwise. Or do you want me to pull that from your repository directly?

Solution 3) would be the best but I don't know yet why it's not working ...

**Comment by void256** [comment]
Ok, wait!

This works as well. See the two comments I've marked with "void256". And I've only showing the two methods I had to modify in the Hint effect class:

``` java
public class Hint implements EffectImpl {
...
  @Override
  public void activate(
      @Nonnull final Nifty nifty,
      @Nonnull final Element element,
      @Nonnull final EffectProperties parameter) {
    this.nifty = nifty;
    screen = nifty.getCurrentScreen();

    if (screen == null) {
      log.severe("Can't activate hint effect without a screen that is currently active.");
      return;
    }

    final String hintControl = parameter.getProperty("hintControl", "nifty-default-hint");
    final String hintStyle = parameter.getProperty("hintStyle", null);
    final String hintText = parameter.getProperty("hintText", "hint: add a 'hintText' attribute to the hint effect :)");
    hintDelay = Integer.valueOf(parameter.getProperty("hintDelay", "0"));
    offsetX = parameter.getProperty("offsetX", "0");
    offsetY = parameter.getProperty("offsetY", "0");

    Element hintLayer = getHintLayer();

    ControlBuilder builder = new ControlBuilder(NiftyIdCreator.generate(), hintControl);
    builder.parameter("hintText", hintText);
    if (hintStyle != null) {
      builder.style(hintStyle);
    }
    // ### void256 ### removed that so that the hintPanel will be initially visible
//    builder.visible(false);
    hintPanel = builder.build(nifty, screen, hintLayer);
  }
...
  @Override
  public void execute(
      @Nonnull final Element element,
      final float normalizedTime,
      @Nullable final Falloff falloff,
      @Nonnull final NiftyRenderEngine r) {
    if (nifty == null || screen == null || hintLayer == null || hintPanel == null) {
      log.severe("Can't execute effect. Activation not done or failed.");
      return;
    }
    if (normalizedTime > 0.0) {
// ### void256 ### changed from hintPanel to hintLayer
      if (!hintLayer.isVisible()) {
        // decide if we can already show the hint
        if (nifty.getNiftyMouse().getNoMouseMovementTime() > hintDelay) {
          hintPanel.setConstraintX(SizeValue.px(getPosX(element, hintPanel, r.getWidth())));
          hintPanel.setConstraintY(SizeValue.px(getPosY(element, hintPanel, r.getHeight())));

          // hard remove all old hints, else they only mess with the new ones
          List<Element> hints = hintLayer.getChildren();
          for (int i = 0; i < hints.size() - 1; i++) {
            nifty.removeElement(screen, hints.get(i));
          }

          hintLayer.layoutElements();
          hintLayer.show();
        }
      }
    }
  }

```

This seems to work for me at first glance. What do you think @3xp0n3nt ?

**Comment by ghost** [comment]
@void256 Oops! Thought I submitted the PR. My mistake!

**Comment by ghost** [comment]
@void256 Yes! That works. Funny, I originally changed the `if (!hintPanel.isVisible())` to `if (!hintLayer.isVisible())` when I was debugging, and it did improve things, but for some reason I put it back o_O.

**Comment by ghost** [comment]
I thought @mkaring broke hint effects with bd08f8ce208a2b8e626d1e5f467beb016ac93360, but now I'm betting that it actually worked prior to c8a6030e78225cb5dc7a4cc3aba22df686339b68, lol...

**Comment by ghost** [comment]
@voi256 It works, but it's still masking a deeper problem of why we cannot show a child element directly after showing it's parent. I know why it's not working, but I'd like to discuss possible ideas for solutions in IRC. I'm in there right now for a little while.

**Comment by void256** [comment]
This commit 77059d2544d3825aaa680491683b377aa1b1fb41 is related as well - forgot to mention it.

**Comment by HariboTer** [comment]
It's very reliefing to hear that this issue could be confirmed and resolved! Thanks a lot for your efforts :-)
Is there already a nightly snapshot for this? I'm excited to see my hints again, it's been such a long time ago that we've had our last meeting ;-)

**Comment by void256** [comment]
@HariboTer Thanks to @mkaring there should be a build triggered automatically after each push to the repo which will automatically deploy the snapshot build in the nifty maven repo at sf.net. You can always get these builds from here: http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/nifty/1.4.1-SNAPSHOT/?C=M;O=D

**Comment by ghost** [comment]
@void256 What happened on IRC yesterday? You pulled a ninja-vanish. http://youtu.be/U8WrlTLF_XY?t=15s

**Comment by void256** [comment]
@3xp0n3nt yes, somehow my internet connection suddenly died. At first I thought it's the 24 hour dsl disconnect but the connection didn't came back. I've waited like an hour without success :cry: I'm sorry for the Ninja vanish :/

**Comment by ghost** [comment]
lol...no problem.
