### ISSUE TITLE
Disable texture offset when using subImageDirect

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#248]
If the image mode is "subImageDirect" it will render the image part correctly, but with the offset as it appears on my original texture (which is already a pre-backed texture atlas). If I set it to "subImage" it will render in the correct position, but the image gets streched.

How can I disable the "texture offset" when using "subImageDirect"?

**Comment by void256** [comment]
You can't disable what you call "texture offset" with "subImageDirect". One eventually need a new image mode for that

BUT

Why not use an individual image for simplicity? Nifty will automatically put them into its own texture atlas in the end anyway. So using a pre-baked texture atlas is not as important as it eventually was in the past. (When using one of the new batched renderers, that is, of course).

**Comment by ghost** [comment]
@spaceemotion I don't get it. Why not just use `subImage` and change the size of the parent element (panel or whatever) to match the original size of the image so it doesn't get stretched?

**Comment by spaceemotion** [comment]
~~@3xp0n3nt I am using the code that was added as an example just today: https://github.com/void256/nifty-gui/commit/0963b5f362c81594f6b364184ffe1052381b6984.~~

~~How would you do it in this case?~~

Edit: I think I got it now ;)

**Comment by ghost** [comment]
@spaceemotion Glad that you figured it out.
