### ISSUE TITLE
Custom element (/control (?)) creation

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#249]
I don't know where I have to create a custom control or something else; I basically want to create some custom elements:
1. ~~The first element/control is meant to be as some kind of **group of elements** holding an image and a label. I can basically create this easily in code already, but then I have tons of duplicated + renamed code lines (which I kind of want to reduce to a minimum).~~ **_Done!**_
2. The second is a bit more complex; It should have a **custom element renderer** which I can attach custom object to. It should automatically add a hover effect and a tooltip (if possible).

How can I achieve either one of this using nifty? I looked through the code and found builders, creators and things like that - but a manual on how to create custom controls was nowhere to be found (even googling my problem didn't show anything).

Thanks in advance!

**Comment by relu91** [comment]
Hi, there was a tutorial about custom control creation but I think that @void256 delete that wiki since it was old and it contained deprecated stuff. Fortunately there is still  [this copy](http://hub.jmonkeyengine.org/wiki/doku.php/jme3:advanced:loading_screen) of that tutorial, I'm not sure that it can help you with custom element renderer though .

**Comment by spaceemotion** [comment]
Yeah I noticed that the whole old wiki got deleted. Any chance that we get it as some kind of "legacy pages" here to the github wiki? I'd even add them myself i necessary ;)

**Comment by spaceemotion** [comment]
Okay, now I got these things: The XML addition for the new, custom control, the Controller, the Builder and an interface.

Getting the ImageProgressController through `healthBarElement.getNiftyControl(ImageProgress.class)` works, but it hasn't been initialised (bound) yet, so I am getting NPs when it tries to update stuff.

How come?

**Comment by void256** [comment]
The Nifty Manual has a whole chapter on custom controls ...

I did not delete the sf.net mediawiki! I was surprised like you that it is gone :cry: The mediawiki app was retired from sf.net and somehow I've missed that. Thanks to the internet archive we have a dump tho: https://archive.org/details/wiki-sourceforgenet_apps_mediawiki_nifty_gui   Not sure how to use that though :wink:

**Comment by spaceemotion** [comment]
I think I solved the second one using custom effects. I will re-open this when I got some problems again ;)
