### ISSUE TITLE
Aliasing on images

### ISSUE THREAD

**Issue by WeirdAlien** [nifty-gui/nifty-gui#252]
I there,

I'm trying to render my GUI image properly. Some of my picture are resized with a callback in the XML to fit the screen resolution. The thing is, most of them look cracky and have aliasing issue. Is there sort of a compression on images that I can disable? Or maybe it's a jmonkeyEngine related bug? Does it rings someone's bell?

Thanks

**Comment by WeirdAlien** [comment]
Well, it was pretty simple, I added the filter="true" attributes to my image. :)

**Comment by void256** [comment]
Excellent work! :wink: Thanks for sharing the solution!
