### ISSUE TITLE
Change color effect isn't working

### ISSUE THREAD

**Issue by WeirdAlien** [nifty-gui/nifty-gui#258]
I'm trying to add this effect: 

Hovering the cursor on a rectangle modify it's color and resize it into a square shape while keeping the mouse on it. Hovering off the rectangle will turn it's original color back and resize it into a rectangle again.

I'm really lost with all the effect, some takes four digit color #FFFF and my element have a 6 digit color. I've tried the effect "fade", "renderQuad" and still, nothing works... 

I putted the effect into a  `<image>`  tag because I though it would be more simple. Should I do this on a panel, which has a "backgroundColor" attribute?

``` xml
<image id="#onglet-1" visibleToMouse="true" filename="Interface/images/WhiteBlank.png"  color="#4FCDFF" height="1.6%" width="15%" x="20%" y="28%">
        <effect>
                  <onStartHover name="changeColor" color"#FFFF" neverStopRendering="true"/>
        </effect>
</image>
```

**Comment by ghost** [comment]
@royjeremie Show us the code please.

**Comment by relu91** [comment]
I've updated the comment to show the xml. @royjeremie when you use xml you should use the code highlighting , otherwise the flavored markdown will eat your code.

**Comment by ghost** [comment]
First of all, put `color="#FFFF"` not `color"FFFF"`.

The `#` is required at the beginning of a color element.

You can do colors in the following formats:

`"#FFF"` (RGB, alpha is assumed to be F, or opaque)
`"#FFFF"` (RGBA)
`"#FFFFFF"` (RRGGBB, alpha is assumed to be FF, or opaque)
`"#FFFFFFFF"` (RRGGBBAA)

I used F as an example, but you can use any single hexadecimal digit (0 through 9, A through F).

You can also do lowercase, `"#fff"`, etc (case doesn't matter).

Next time post the error messages you're getting because Nifty should be completely choking on that invalid xml, lol.

**Comment by ghost** [comment]
@royjeremie Please show the entire xml file. I'm sure there's probably other problems elsewhere...

**Comment by WeirdAlien** [comment]
``` java
public class ModifyColor implements EffectImpl {

    private Color color;

    @Override
    public void activate(Nifty nifty, Element element, EffectProperties parameter)
    {
        color = new de.lessvoid.nifty.tools.Color(parameter.getProperty("color", "#ffff"));
        System.out.println("Color: " + color);
    }

    @Override
    public void execute(Element element, float effectTime, Falloff falloff, NiftyRenderEngine r)
    {
        r.setColor(color);
    }

    @Override
    public void deactivate()
    {
        //
    }
}
```

**Comment by WeirdAlien** [comment]
``` xml
<registerEffect name="modifyColor" class="com.certification.renderer.jme3.gui.customEffects.ModifyColor" />


    <screen id="flipMenuScreen" controller="com.certification.renderer.jme3.gui.ScreenJME">
        <layer childLayout="center" id="wrapper">
            <panel childLayout="center" id="innerWrapper" width="${CALL.getWidth(1.3)}" height="${CALL.getWidth(1.3)}">
                <image id="#onglet-1" visibleToMouse="true" filename="Interface/images/WhiteBlank.png" color="#AA4FDD" height="1.6%" width="15%" x="20%" y="28%">
                    <effect>
                        <onClick name="modifyColor" color="#11FFAA" neverStopRendering="true"/>
                    </effect>
                </image>
            </panel>
        </layer>
    </screen>
```

**Comment by WeirdAlien** [comment]
There is no invalid xml message, the color is just not switching.. :/

**Comment by ghost** [comment]
@royjeremie I can't see anything wrong. Try the effect on a panel instead of an image (get rid of the image completely). Just make sure you set `visibleToMouse="true"` on the panel.

**Comment by relu91** [comment]
I've found the trick, as @3xp0n3nt said use a panel because the image element paints the image over the background so the color you are setting is behind the image it self. If you still want a image you could use a panel with backgroundImage , in this case in fact the backgroundColor is painted over the backgroundImage. I hope this finally fix this issue :)

**Comment by WeirdAlien** [comment]
Yeah! The color switching now works fine using the panel. I still have one issue though, I need to resize the height of the panel while hovering it. I can access the height attribute of the element, but I don't know how to animate it to not be instantaneous.

**Comment by WeirdAlien** [comment]
public class Reshape implements EffectImpl {

```
private float startSize;
private float endSize;
private SizeValue imageSize = new SizeValue("100%");
private LinearInterpolator interpolator;

@Override
public void activate(Nifty nifty, Element element, EffectProperties parameter)
{
    startSize = Float.parseFloat(parameter.getProperty("startHeight", "1.0"));
    endSize = Float.parseFloat(parameter.getProperty("endHeight", "2.0"));

    // for hover mode only
    String maxSizeString = parameter.getProperty("maxSize");
    if (maxSizeString != null)
    {
        imageSize = new SizeValue(maxSizeString);
    }
    interpolator = parameter.getInterpolator();
}

@Override
public void execute(Element element, float normalizedTime, Falloff falloff, NiftyRenderEngine r)
{
    float scale = 1.0f;
    if (falloff == null)
    {
        float t = normalizedTime;
        if (interpolator != null)
        {
            scale = interpolator.getValue(t);
        } else
        {
            scale = startSize + t * (endSize - startSize);
        }
    } else
    {
        scale = 1.0f + falloff.getFalloffValue() * imageSize.getValue(1.0f);
    }
    int size = (int) scale;
    element.setHeight(size);
}

@Override
public void deactivate()
{
    //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
}
```

}

**Comment by relu91** [comment]
What do you mean by > I can't access to a height setter of a panel ? . If you implement your own effect in the execute method you have a reference of the element that has your effect.

``` java
@Override
    public void execute(Element element, float effectTime, Falloff falloff, NiftyRenderEngine r)
    {
        element.setHeight(42);
    }
```

beside using setHeight you could use  `setConstraintHeight(SizeValue value);`. I don't remember the difference between them tough, sorry. If for some reason this won't work you should call layoutElements in the element parent. :+1:

**Comment by WeirdAlien** [comment]
yes sorry, I explained myself badly, I corrected my comment. I can access the height but I can't make it look animated as it is too fast or just instantaneous...

**Comment by WeirdAlien** [comment]
Here the xml: 
`<onHover name="reshape" maxSize="500" length="1000" startDelay="2500" startHeight="0.2" endHeight="0.5"/>`

**Comment by WeirdAlien** [comment]
I'll just start a new thread since the title isn't related and the initial issue is fixed

**Comment by ghost** [comment]
@royjeremie Thank you for creating a new issue.
