### ISSUE TITLE
Behavior of ButtonControl & NiftyStandardInputEvent.MoveCursorUp/Down

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#261]
@void256 In the following method from _de.lessvoid.nifty.controls.button.ButtonControl.java_...

<pre>
public boolean inputEvent(@Nonnull final NiftyInputEvent inputEvent) {

...

    } else if (inputEvent == NiftyStandardInputEvent.MoveCursorDown) {
      Element nextElement = focusHandler.getNext(buttonElement);
      <b>if (nextElement.getParent().equals(buttonElement.getParent())) {</b>
        nextElement.setFocus();
        return true;
      <b>}</b>
    } else if (inputEvent == NiftyStandardInputEvent.MoveCursorUp) {
      Element prevElement = focusHandler.getPrev(buttonElement);
      <b>if (prevElement.getParent().equals(buttonElement.getParent())) {</b>
        prevElement.setFocus();
        return true;
      <b>}</b>
    }

...

}
</pre>

...why do `NiftyStandardInputEvent.MoveCursorUp` & `NiftyStandardInputEvent.MoveCursorDown` only set the next element's focus if the current element and the next element both share the same parent element?

I'm asking because I created a design which each button of a menu was in it's own panel, and the up and down arrow keys map to `MoveCursorUp` & `MoveCursorDown`, but you could not use those keys to move the keyboard focus up and down the menu buttons. `TAB` worked just fine, however, because earlier in this same method, `NiftyStandardInputEvent.NextInputElement` & `NiftyStandardInputEvent.PrevInputElement` don't check that the buttons are of the same parent; it doesn't care. So why should `TAB` traverse across different parent panels, but not the arrow keys?

I'd submit a pull request, but I'm sure this is by design; I just can't really understand why we **_need**_ it. It's also a completely **_undocumented**_ "feature" that resulted in much hair pulling to try and track down the cause, so if it's here to stay, it needs to be mentioned in the manual and wiki.

P.S. Another strange thing is that while troubleshooting this, I tried mapping the up & down arrow keys to `NexInputElement` & `PrevInputElement`, but that didn't work either.

**Comment by void256** [comment]
If there was a reason for that I can't remember right now :/ I don't think it makes much sense. Actually, I've checked other controls like the TextFieldControl and they don't do that check. Strange.

I'll remove it.

**Comment by void256** [comment]
Fixed with commit 17acc96d460ea2ca4752565eba57534e29aea497
Ticket will be closed.

**Comment by ghost** [comment]
@void256 Interesting. I would have submitted a PR, I just thought there was a good reason for it. Thanks for the fix!
