### ISSUE TITLE
Something font related

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#269]
I am using nifty with the LwjglRenderDevice, but not on top of pure Lwjgl code, but instead together with Slick2d (I don't use the Nifty SlickRenderer because I'm planning to abandon Slick2d in the near future anyway because of performance issues, and secondly because all Nifty builds are compiled against an older version of Slick2d which causes a Runtime Exception because of some type incompatibility (between "String" and "CharSequence" if I remember right) and I'm to lazy to hust compile Nifty from source :P). I tested (and modeled) the gui, however, in a pure Lwjgl application. After I moved the corresponding .xml file from the test project to the main (Slick-) project, certain images were shown stretched and the space was diverted differently. I'm wondering now what different methods slick calls in contrary to me and how to fix this problem. 
![screenintact](https://cloud.githubusercontent.com/assets/4622438/3954312/eacde70e-26f4-11e4-908b-1b1acf9f13ef.png) This is how it looked in Lwjgl code and how it should look in Slick as well.
![screenbroken](https://cloud.githubusercontent.com/assets/4622438/3954322/097ba6c8-26f5-11e4-93d8-78195adc73ab.png) This is how it looks in Slick. Somehow, the buttons are stretched and everything is slightly shifted to the top.

Here is the corresponding .xml file:

``` xml
<?xml version="1.0" encoding="UTF-8"?>

<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

    <screen id="start" controller="view.gui.controllers.StartScreenController">
        <layer id="background" childLayout="vertical">
            <image filename="res/imgs/ui/bg02.png"/>
        </layer>
        <layer id="foreground" childLayout="vertical">
            <panel id="headlinePanel" align="center" valign="center" childLayout="center" visibleToMouse="false">
                <text id="headline" wrap="true" font="res/fonts/128/airstrikecond.fnt" color="#ffff" text="Oberien"/>
            </panel>
            <panel id="startPanel" align="center" valign="center" childLayout="center" height="25%" visibleToMouse="true">
                <image filename="res/imgs/ui/button.png" childLayout="center">
                    <text id="start" wrap="true" font="res/fonts/32/airstrikecond.fnt" color="#ffff" text="Start"/>
                </image>
            </panel>
            <panel id="settingsPanel" align="center" valign="center" height="40%" childLayout="center" visibleToMouse="true">
                <image filename="res/imgs/ui/button.png" childLayout="center">
                    <text id="settings" wrap="true" font="res/fonts/32/airstrikecond.fnt" color ="#ffff" text="Settings"/>
                </image>
            </panel>
        </layer>
        <layer id="exitLayer" childLayout="horizontal">
            <panel id="exitPanel" align="left" valign="top" childLayout="vertical" visibleToMouse="true">
                <image filename="res/imgs/ui/button.png" align="left" valign="bottom" childLayout="center">
                    <text id="exit" wrap="true" font="res/fonts/32/airstrikecond.fnt" color="#ffff" text="Exit"/>
                </image>
            </panel>
        </layer>
    </screen>

    <screen id="settings">
    </screen>

    <screen id="mapChooser">
    </screen>
</nifty>
```

Any ideas are welcome! Help is greatly appreciated.

**Comment by void256** [comment]
When I understand this issue right, then you're using in both cases the LwjglRenderDevice. Is this correct?

I guess this is a problem in the way the projection matrix is setup when you call nifty.render() in the slick2d version or there is some other difference between the two. If you use the same LwjglRenderDevice in both cases then it really should generate the same output :wink: and the difference must be in some other code, right?

**Comment by oberien** [comment]
Thank you for the reply!

Yes, we use the LwjglRenderDevice, at least that's what he told me and imports (we work together on the same project, where he encountered this issue). He said he directly copied the code from his test project to our project, but running the code he encountered this issue. In his test project, he doesn't implement Slick2d, in the real one we work with it.

At the moment I try to avoid this problem by using relative width/height attributes for all components. But I hope this will only be a temporary workaround until we find out, how to implement/use layouts correctly.

**Comment by ghost** [comment]
@Blackhole16 Just so you know, LwjglRenderDevice is **_ancient**_, **_deprecated**_, and soon to be removed from Nifty. It uses immediate mode rendering, which is ancient OpenGL. So it's kind of funny that you're talking about performance issues with Slick, when you're using these old, poor-performance rendering classes. Slick is dead, and does have many other issues, but anyway, I'm saying this because what you're doing isn't really supported any more. You need to upgrade ASAP ;-).

You really need to read this: https://github.com/void256/nifty-gui/pull/260.

(Not to mention that Lwjgl 3 is in the works: https://github.com/LWJGL/lwjgl3/wiki/1.3.-Roadmap, which I'm itching to get into Nifty, as well as LibGDX's OpenGL ES 3.0 support: https://github.com/libgdx/libgdx/pull/1151).

**Comment by ghost** [comment]
Again, thank you for your reply! 

I tried to implement the BatchRenderDevice, however, in the current build, SlickBatchRenderBackendFactory is not yet implemented and the SlickRenderDevice is still used. However, I built an 1.4.1-Snapshot from the sources. Sadly, this doesn't work either, because of an UnsupportedOperationException in the AbstractNativeSlickMouseCursor class. I would really like to implement the BatchRenderer, so if there's any way or a stable build including it, please let me know.

**Comment by ghost** [comment]
I implemented BatchRenderDevice with a LwjglBatchRenderBackendFactory now, and it works (at least, I can see something and run the program agein ^^). However, a strange bug appeared upon rendering a very large font (128px) whose textures are split up in three different image files. Only certain letters were rendered in proper size, the others were resized to something around 32px: 
![obbatchscreen](https://cloud.githubusercontent.com/assets/4622438/3984252/8607aa24-2886-11e4-96ab-413007e32f80.png)

Also, the previous bugs persist (as you can see). 
I'm open for any ideas/help, as always!

EDIT: After merging the 3 images to one and recompiling the font, all letters were shrinked to 32px.

**Comment by oberien** [comment]
I tried around a bit with bob's code after mine (for the Game Setup) renders the fonts correctly. Trying to apply my code to the bugging code in the first post, I encoutered the following issue/bug:

I tried to implemend own "buttons" by using an image with text and onlick-interact in this xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />

    <screen id="start" controller="view.gui.controllers.StartScreenController">
        <layer id="background" childLayout="vertical">
            <image filename="res/imgs/ui/bg02.png"/>
        </layer>
        <layer id="foreground" childLayout="vertical">
            <panel id="oberienPanel" align="center" valign="center" childLayout="center" height="20%">
                <text id="oberien" wrap="false" font="res/fonts/128/airstrikecond.fnt" color="#fff" text="Oberien" valign="center" height="20%"/>
            </panel>
            <panel id="gameSetupPanel" align="center" valign="center" childLayout="center" height="40%">
                <image id="gameSetupButton" filename="res/imgs/ui/button.png" align="center" valign="center" childLayout="center" width="10%" height="10%">
                    <text id="gameSetupText" wrap="false" font="res/fonts/32/airstrikecond.fnt" color="#fff" text="Game Setup"/>
                    <interact onClick="gameSetup()"/>
                </image>
            </panel>
            <panel id="settingsPanel" align="center" valign="center" childLayout="center" height="40%">
                <image id="settingsButton" filename="res/imgs/ui/button.png" align="center" valign="center" childLayout="center" width="10%" height="10%">
                    <text id="settingsText" wrap="false" font="res/fonts/32/airstrikecond.fnt" color="#ffff" text="Settings"/>
                    <interact onClick="settings()"/>
                </image>
            </panel>
        </layer>
        <layer id="exitLayer" childLayout="horizontal">
            <image id="exitButton" filename="res/imgs/ui/button.png" align="right" valign="top" childLayout="center" width="5%" height="5%">
                <text id="exitText" wrap="true" font="res/fonts/32/airstrikecond.fnt" color="#fff" text="Exit"/>
                <interact onClick="exit()"/>
            </image>
        </layer>
    </screen>
</nifty>
```

I got this result:
![oberien1](https://cloud.githubusercontent.com/assets/4820508/3988503/49c01bee-28b0-11e4-9206-2db188b6609e.png)
Like you can see, the font is bugged again. I worked around the layout bug by setting width and height manually.

I compared it to my own code and the only difference is, that in his codes there are images and in mine I use control-Buttons. So I exchanged the images by controls:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />

    <screen id="start" controller="view.gui.controllers.StartScreenController">
        <layer id="background" childLayout="vertical">
            <image filename="res/imgs/ui/bg02.png"/>
        </layer>
        <layer id="foreground" childLayout="vertical" height="100%">
            <panel id="oberienPanel" align="center" valign="center" childLayout="center" height="20%">
                <text id="oberien" wrap="false" font="res/fonts/128/airstrikecond.fnt" color="#fff" text="Oberien" width="100%" height="20%"/>
            </panel>
            <panel id="gameSetupPanel" align="center" valign="center" childLayout="center" height="40%">
                <control id="gameSetupButton" name="button" label="Game Setup" align="center" valign="center" width="10%" height="10%">
                    <interact onClick="gameSetup()"/>
                </control>
            </panel>
            <panel id="settingsPanel" align="center" valign="center" childLayout="center" height="40%">
                <control id="settingsButton" name="button" label="Settings" align="center" valign="center" width="10%" height="10%">
                    <interact onClick="settings()"/>
                </control>
            </panel>
        </layer>
        <layer id="exitLayer" childLayout="horizontal">
            <control id="exitButton" name="button" label="Exit" align="right" valign="top" width="5%" height="5%">
                <interact onClick="exit()"/>
            </control>
        </layer>
    </screen>
</nifty>
```

This is the result:
![oberien2](https://cloud.githubusercontent.com/assets/4820508/3988549/b0f3d864-28b0-11e4-8b34-ad1119504dbc.png)
As you can see, the font is rendered correctly!

So why isn't font rendered correctly, if there are pictures?

Another interesting thing is the following:
In the background-layer there is the backgroundimage, which doesn't impact the font. But using images in the font-text's layer our layers above, there is this bug. The font will only be rendered correctly again in Example 1, if i remove every image in the layers "foreground" and "exitLayer".

So why does this happen and how can we solve or workaround this issue?

Kind Regards,
BH16

**Comment by ghost** [comment]
If you can somehow provide me the fonts and images used in this example, I'll see what I can do.

**Comment by ghost** [comment]
By the way, the top of your xml file should look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.lessvoid.com/nifty-gui">
```

not

```
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://
www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://niftygui.
sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">
```

The second one is outdated & incorrect. You can't specify the xsd location any more because Nifty now uses the xsd file included in the source code itself (http://nifty-gui.lessvoid.com/?page_id=579).

**Comment by ghost** [comment]
If you have a good IDE (cough_intellij_cough), you should notice some errors come up in your xml.

**Comment by ghost** [comment]
> 3xp0n3nt commented an hour ago
> 
> If you can somehow provide me the fonts and images used in this example, I'll see what I can do.

In the meantime, the code using images with text inside (the first version, no button controls) renders correctly with the stock font aurulent-sans-16, which most likely means your font files are broken.

**Comment by oberien** [comment]
Thanks for your reply and the new header.

Here are all files:
res/imgs/ui/bg02.png:
![bg02](https://cloud.githubusercontent.com/assets/4820508/3992922/dcb42f4a-2904-11e4-8f71-e2949ae20751.png)
res/imgs/ui/button.png:
![button](https://cloud.githubusercontent.com/assets/4820508/3992934/fe90d460-2904-11e4-9363-279cfe9c98e4.png)

and here are the fonts:
res/fonts/32/aristrikecond.fnt:
http://www.file-upload.net/download-9409598/airstrikecond.fnt.html
res/fonts/32/airstrikecond_0.png
![airstrikecond_0](https://cloud.githubusercontent.com/assets/4820508/3992950/1f76fb78-2905-11e4-962a-868948ac0aa7.png)

res/fonts/128/airstrikecond.fnt:
http://www.file-upload.net/download-9409600/airstrikecond.fnt.html
res/fonts/128/airstrikecond_0.png, _1.png und _2.png:
![airstrikecond_0](https://cloud.githubusercontent.com/assets/4820508/3992992/943b52b0-2905-11e4-8c99-337e4de0f9bc.png)
![airstrikecond_1](https://cloud.githubusercontent.com/assets/4820508/3992991/9434ff00-2905-11e4-8e4d-64107f80fba3.png)
![airstrikecond_2](https://cloud.githubusercontent.com/assets/4820508/3992993/943c5624-2905-11e4-976b-7ac985c546cf.png)

By the way on the buttons there is also the font used, but only 32px tall, and it is rendered correctly. Only the taller one (128px) doesn't work...
And shouldn't the font file be broken, if it was rendered correctly in the second example?

Thank's for your help!
Kind Regards,
BH16

**Comment by oberien** [comment]
Ok, the bug has nothing to do with fonts and images! The bug actually only appears, if I use both fonts in one screen. So if I use airstikecond.fnt with 128px and later use airstrikecond.fnt with 32px, this odd bug occurs. I already tried renaming the 128px-files (1x fnt, 3xpng; changed references in the fnt-file), but the bug still persists.

**Comment by oberien** [comment]
I isolated the bug! It has nothing to do with filenames, it's the face's name! Both the 32px- and the 128px-font do have the same face's name. After changing the names in the font-files, the bug was gone.
I also found out, that all crappy letters, which have buggily been displayed in size 32 instead of 128, have been in airstrikecond_0.png of the 128px-font.

My hypothesis what happened is the following, but I have no idea, how nifty actually handles this. It is just one thing, that I think could have happened:

Nifty saves fonts in a HashMap, with it's face's name being the key. After loading both fonts, the picture airstrikcond_0.png of the 128px-font was overwritten by the 32px-font's one. Therefore, all characters being in airstrikecond_0.png of 128px have now been rendered with the 32px one.

Again, I have no idea, how Nifty handles this, but the above explanation seems logical to me.

A way to solve this could be to use the filename as key for the HashMap and not the face's name.

@void256 is something like the explanation above the case or how does this bug come? Can you provide a fix, or should I just workaround by using different names?

Kind Regards,
BH16

PS: For loading the fonts we had to add jglfont-core-1.4.jar to the project's libraries.

**Comment by relu91** [comment]
> For loading the fonts we had to add jglfont-core-1.4.jar to the project's libraries. 

Just for reference I've also didn't know about the dependence of [jglfont](https://github.com/void256/jglfont). So while I was digging in the batch renderers code I've found this strange library. It come out that it's an other project of @void256 so he can give more explanation about how it works :+1: . I'm eager to know the pro and cons of using that library and not giving the responsibility to load fonts only to the renderer backend :) . Also the whole loading font process is kind of a black box to me ^_^ is there some reference where I can study it ? I'm asking because I don't know if a font that works on java2d render will work also in JME for example. I hope that I'm not too out of topic!

**Comment by oberien** [comment]
I actually have no idea how to use jglfont, but the BatchRenderDevice uses this lib to load the fonts, so we just had to implement it, but not directly use it. So I think, that the renderer backend still has the responsibility :)
The thing is, that nifty (and therefore also JME, I think) only supports *.fnt font files, which are very rare on the internet. Therefore BobTP uses BMFont to convert ttfs into fnts. But as I don't use JME I can't tell for sure.

**Comment by void256** [comment]
There is nothing special about jglfont. It just loads bitmap fonts and now actually supports generating bitmap fonts on the fly from .ttf as well (!).

At some point we had the same bitmap font loading code in several NiftyRenderDevice-implementations so it was necessary to extract that code into a separate library OR add it to Nifty core. But since it was general enough to be used outside of the Nifty universe as well, we moved that into a separate project at the expense of an additional dependency.

If you ever feel the need to load and render a bitmap font without Nifty then jglfont will be available!

@Blackhole16 Yes, at the moment you should make sure the "face" attribute of the fonts are different since your "bug" analysis is correct. Using the same "face" name will mess up the font bitmaps internally. I've created a new issue for jglfont to fix the issue: https://github.com/void256/jglfont/issues/4

**Comment by oberien** [comment]
Thanks, I think Bobtp will soon close this issue :)

**Comment by relu91** [comment]
> There is nothing special about jglfont. It just loads bitmap fonts and now actually supports generating bitmap fonts on the fly from .ttf as well (!).
> At some point we had the same bitmap font loading code in several NiftyRenderDevice-implementations so it was necessary to extract that code into a separate library OR add it to Nifty core. But since it was general enough to be used outside of the Nifty universe as well, we moved that into a separate project at the expense of an additional dependency.

So would it be a standard for all renderers? I mean , can I supposed that all the renders could read .ttf files ?

**Comment by void256** [comment]
> So would it be a standard for all renderers? I mean , can I supposed that all the renders could read .ttf files ? 

I think it should be standard for all renderers we maintain in the nifty repository. I don't see any reason  not to use jglfont there. In general, however, a NiftyRenderDevice implementation can support any kind of font formats. So you can't really assume the same font formats being supported in all NiftyRenderDevices especially if we don't maintain it as it currently is the case for the jme-renderer, f.i.

I don't think this is a problem in general because when you use Nifty in your application then you use it with a specific NiftyRenderDevice and you'll be happy with whatever font format it supports.

PS: TTF are still being rendered to a bitmap. So it's just another source of bitmap font data. I'd like to have a more quality version that can directly render TTF like jogamp is doing. But we don't have that ... yet :wink:

**Comment by relu91** [comment]
> I don't think this is a problem in general because when you use Nifty in your application then you use it with a specific NiftyRenderDevice and you'll be happy with whatever font format it supports.

Yep I just need this information to cover a nice support for nityeditor. For example currently the only fonts admitted are the system fonts so when the user will load the gui in his runtime he doesn't see what he expects :smiley: . So support for bitmap fonts in nifty-editor should be enough it's also widely use, but in this case the font size can't be dynamically changed right ?

**Comment by ghost** [comment]
I think that https://github.com/void256/jglfont should emit a warning when it detects a duplicate font face.

@BobTP @void256 Could we change the title of this issue to something font related and then close it? The title is misleading, and the original issue has been resolved.

**Comment by oberien** [comment]
No comment on that title.....  Plase close this crap bob :)
