### ISSUE TITLE
Change Colors onClick

### ISSUE THREAD

**Issue by oberien** [nifty-gui/nifty-gui#271]
How can I change the backgroundcolor of Panels (or the color of any other component or control) with java inside of an onClick interacted method?

This is what I want to achieve:
I try to create an Game Setup where Players can cycle through colors to choose their color ingame. I try to achieve this with a button/panel/any other component, cycling though an array of Colors.

For example in swing there are Component.setBackground(Color col) and Component.setForeground(Color col). Are there equal function in nifty?

Regards,
BH16

**Comment by relu91** [comment]
Yes there is! if you are using a panel you can easily take a panelRenderer instance from your element and call renderer.setBackgroundColor(yourniftycolor).

``` java
   yourelement.getRenderer(PanelRenderer.class).setBackgroundColor(Color.BLACK);
```

I'm not sure but also images could have a panel renderer attached.

**Comment by oberien** [comment]
Thank's man! That's exactly what I was looking for!

Is there also a method to get the current backgroundColor?

Kind Regards,
BH16

**Comment by ghost** [comment]
@Blackhole16 You need to use the Nifty Gui manual for such basic things. You know the pdf comes with the Nifty source code in nifty-core/manual/ right? You can also get it from https://github.com/void256/nifty-gui/tree/1.4/nifty-core/manual - right click on the pdf and choose "Save link as...".

There's not too many people here to help, and most of us are very busy, so please do your research before asking other people.

I'm referring to this entire issue, not just your latest question.

**Comment by oberien** [comment]
I read and worked through the whole manual and still have it open on my secondary display all the time. I searched through the manual and didn't find anything regarding ondemand color changes with java of elements, neither in the manual, nor in the internet. That's why I am asking here. I always look into manuals, javadocs and search the web, before asking dumb questions :)

**Comment by ghost** [comment]
> Blackhole16 commented 16 hours ago
> 
> I read and worked through the whole manual and still have it open on my secondary display all the time. I searched through the manual and didn't find anything regarding ondemand color changes with java of elements, neither in the manual, nor in the internet. That's why I am asking here. I always look into manuals, javadocs and search the web, before asking dumb questions :)

Good to know you're doing all that. =) I checked the manual and while it does have a section on runtime element modification, it doesn't specifically mention changing a panel's background color, so sorry about that ;-). That should really be in the manual. Although the entire manual should be transcribed to the wiki, and then burned, lol...

**Comment by oberien** [comment]
So is there actually a way to get the backgroundColor of a panel? :)
Or do I have to handle it manually in a HashMap in my Controller-class?

**Comment by ghost** [comment]
@Blackhole16 I don't see a way to do it. That's pretty weird...

**Comment by oberien** [comment]
If there really wasn't a way to get the backgroundColor of an element, I think @void256 maybe could implement such a function either directly to the Element or to the PanelRenderer. What do you think?

In my case I think I need to use a HasMap in my Controller-class to save the current backgroundColor of my Elements.

Kind Regards,
BH16

**Comment by relu91** [comment]
> Although the entire manual should be transcribed to the wiki, and then burned, lol...

totally agree! the wiki really needs to be improved. Maybe we should think also about a friendly structure, right now is not to easy to read. At least for now the pages document could be dumped to a doc one so others could be able to contribute with that with PRs . 

About this problem an other trick, which is used also in nifty-editor, it's the use of ElementType class. Althought it's not be designed to be used for elements manipulation it can store all the xml attributes like for example "backgroundColor" attribute. You can read the value from there and then evry time you set it in PanelRenderer you should also set the Element type instance.  If you won't to use Panel renderer but only my mechanism you should make this little method that refresh the element and change the backgroundColor using the value stored in its elementType class.
In practise:

``` java
//Somewhere 
        Attributes att = niftyElement.getElementType().getAttributes();
        att.set("backgroundColor", "yourcolorToString");
        refresh(niftyElement);

      public void refresh(Element nElement) {
        Nifty temp = nElement.getNifty();
        Screen currentScreen = temp.getCurrentScreen();
        Attributes att = nElement.getElementType().getAttributes();
        nElement.initializeFromAttributes(currentScreen, att, temp.getRenderEngine());
        currentScreen.layoutLayers();
    }


```

Maybe this is easier to maintain than the HashMap in your controller class. I hope it works!

**Comment by oberien** [comment]
Thank's for the workaround solution. It works on first-time-use. But for any reason only on the first time i click the panel.
So if i hover over the panel, the hover-effect (black border) will appear. If I click into the panel, the color will change. But after that the whole panel freezes. The hover effect is still on, even though I don't hover over this panel. It also doesn't react to any other mouseEvent. Do you have an idea, why this could happen?

I thought about another maybe possible way of getting and setting the backgroundColor. I think about creating an custom control, having a backgroundColor-attribute inserting an parameter:

``` xml
<controlDefinition id="..." name="..." backgroundColor="$bgColor">
```

Is there a way to get and set parameters of Controls? If this is the case, this solution will work.

Another workaround (don't want to use this one) is to create a style for each backgroundColor. By changing the style (Element.setStyle(String style)) to the desired one, you can achieve setting the backgroundColor. Getting it is also very easy: You just need to use Element.getStyle(). If you choose the stylename correctly (e.g. "backgroundColor#f00f") you can simply substring the last 5 letters and use them in a Color constructor.
But creating all styles for this workaround is nothing I wanted to do just to get/set the bgColor of a Panel...
I didn't test the latter, so I don't know, if it actually works.

Kind Regards,
BH16

**Comment by ghost** [comment]
See https://github.com/void256/nifty-gui/pull/273.

**Comment by relu91** [comment]
> Thank's for the workaround solution. It works on first-time-use. But for any reason only on the first time i click the panel.
> So if i hover over the panel, the hover-effect (black border) will appear. If I click into the panel, the color will change. But after that the whole panel freezes. The hover effect is still on, even though I don't hover over this panel. It also doesn't react to any other mouseEvent. Do you have an idea, why this could happen?

It could be that what the refresh method does it simply breaks the element life-cycle handled by nifty so in a more complex environment than the nifty-editor things going to be wired. Well thanks to @3xp0n3nt now you have a far easier solution! :dart:

**Comment by ghost** [comment]
> relu91 commented 20 hours ago
> 
> About this problem an other trick, which is used also in nifty-editor, it's the use of ElementType class. Althought it's not be designed to be used for elements manipulation it can store all the xml attributes like for example "backgroundColor" attribute. You can read the value from there and then evry time you set it in PanelRenderer you should also set the Element type instance. If you won't to use Panel renderer but only my mechanism you should make this little method that refresh the element and change the backgroundColor using the value stored in its elementType class.
> In practise:
> 
> //Somewhere 
>         Attributes att = niftyElement.getElementType().getAttributes();
>         att.set("backgroundColor", "yourcolorToString");
>         refresh(niftyElement);
> 
> ```
>   public void refresh(Element nElement) {
>     Nifty temp = nElement.getNifty();
>     Screen currentScreen = temp.getCurrentScreen();
>     Attributes att = nElement.getElementType().getAttributes();
>     nElement.initializeFromAttributes(currentScreen, att, temp.getRenderEngine());
>     currentScreen.layoutLayers();
> }
> ```
> 
> Maybe this is easier to maintain than the HashMap in your controller class. I hope it works!
> 
> relu91 commented 38 minutes ago
> 
> ```
> Thank's for the workaround solution. It works on first-time-use. But for any reason only on the first time i click the panel.
> So if i hover over the panel, the hover-effect (black border) will appear. If I click into the panel, the color will change. But after that the whole panel freezes. The hover effect is still on, even though I don't hover over this panel. It also doesn't react to any other mouseEvent. Do you have an idea, why this could happen?
> ```
> 
> It could be that what the refresh method does it simply breaks the element life-cycle handled by nifty so in a more complex environment than the nifty-editor things going to be wired.

When I see such abuse of Nifty with evil hacks:

http://youtu.be/ajUlhaX9hQI?t=8s

**Comment by relu91** [comment]
ahhaha :laughing: I was forced to that .... otherwise nifty-editor would never seen the light.

**Comment by oberien** [comment]
As this is getting quite OT now and the pull request has been made, I think I am going to close this issue now :)
Thank's for the help!
