### ISSUE TITLE
Executable LibGDX Examples Jar Missing From Nifty 1.4.0 Download

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#276]
Steps to Reproduce:
1. Download http://sourceforge.net/projects/nifty-gui/files/latest/download
2. Extract nifty-1.4.0-complete.zip
3. Navigate to extracted nifty-1.4.0-complete folder.
4. Notice that `nifty-examples-libgdx-desktop-1.4.0-jar-with-dependencies.jar` is missing.
5. Double click `nifty-examples-libgdx-desktop-1.4.0.jar`.
6. You will receive an error stating that: "The Java JAR file “nifty-examples-libgdx-desktop-1.4.0.jar” could not be launched. Check the Console for possible error messages." because this Jar is not executable.
7. `git clone https://github.com/void256/nifty-gui.git`
8. `cd nifty-gui`
9. `mvn clean package`
10. Navigate to ".../nifty-gui/nifty-examples-libgdx/desktop/target" in the file system
11. Double click `nifty-examples-libgdx-desktop-1.4.1-SNAPSHOT-jar-with-dependencies.jar`.
12. Notice that the Jar is executable and will run the Nifty Examples after double clicking it.

Solution:

@void256 Please update nifty-1.4.0-complete.zip at http://sourceforge.net/projects/nifty-gui/files/latest/download to include `nifty-examples-libgdx-desktop-1.4.0-jar-with-dependencies.jar`. In fact, you can rename it if you want, to `nifty-examples-libgdx-desktop-1.4.0-executable.jar`. Thanks!

P.S. In fact, I'll even submit a pull request to update this executable jar name in the code to `nifty-examples-libgdx-desktop-1.4.0-executable.jar`.

**Comment by void256** [comment]
Alright! I've added the missing examples jar to the nifty-1.4.0-complete.zip and uploaded it to sf.net.

This made the zip twice as large :wink: For new Nifty releases we might want to find another way so that all the resource files of the examples are not duplicated in each example jar again or something like that.

I'll close this issue now! Thanks for the detailed solution description @3xp0n3nt :wink:

**Comment by ghost** [comment]
>  void256 commented 4 hours ago 
> This made the zip twice as large

Holy cow!

I don't really know of a solution off the top of my head for this. The problem is that an executable jar must contain all the libraries inside of it. I want to make executable jars for all the backends, which could increase the size quite a bit. In my opinion, it's worth the trade off of the size increase. What do you think? Any other ideas?

**Comment by void256** [comment]
I like the idea of a single executable jar file for all the examples for all the backends! We'd just need some bootstrap Main class that you would need to call with a parameter which backend / RenderDevice you want :smile:

Another solution would be to have the executable jar containing only the render backend specifics and add a separate resource jar (with all the examples) to the classpath manually `-cp nifty-examples-stuff.jar` I think this would work too! You probably won't be able to double click the jar directly but it's better to duplicate all the stuff in each and every executable example jar >_<

**Comment by ghost** [comment]
@void256 Doing that method, I think you can create simple script files, like .bat for windows, or .sh for os x / linux, that will execute the appropriate command.
