### ISSUE TITLE
Setting up 1.4 with LWJGL

### ISSUE THREAD

**Issue by blisterfingers** [nifty-gui/nifty-gui#282]
I'm just trying to get set-up and running a simple hello world but adding a new LWJGLRendererDevice, the javadoc tells me it's depreciated. So I try and use the suggested 'new BatchRenderDevice(LwjglBatchRenderBackendFactory.create()); and my program exits, complaining about java.lang.ClassNotFoundException: org.jglfont.spi.ResourceLoader

I noticed that JGLFont is one of Void256's other projects on GitHub, do I need to add this project to my classpath too? I don't use maven but I checked the pom.xml in GitHub sources for nifty and saw no other dependencies.

I have currently, already added the following jars to my classpath;
nifty-1.4.0.jar,
nifty-default-controls-1.4.0.jar
nifty-lwjgl-renderer-1.4.0.jar
nifty-openal-soundsystem-1.4.0.jar
and
nifty-style-black-1.4.0.jar

**Comment by oberien** [comment]
Jglfont is the fontloader for several renderers,  including the batchrenderer. You must include jglfont into your classpath for it to work.

**Comment by blisterfingers** [comment]
Hmm. Thanks for your assistance but after adding in JGLFont, I get errors about EventBus and after adding that I get errors about XMLPull which I can't get to work no matter which version of their oddly named jars I add to the build path.

Now, I'm no expert by a long shot but if I don't even have a list of the needed dependencies, I can't see how I can possibly get this working.

I looked at maven, believing the point of it was to simplify this dependency business but five hours later I can safely say that's not the case and I won't dedicate any more time to learning it just to use nifty so I guess that's that. No nifty for me.

**Comment by blisterfingers** [comment]
Alight. I had a random stab in the dark and added a bunch of XMLPull jars to the build path and it works.. mostly. I'm able to run a simple Hello World. Unfortunately calling nifty.update() never returns true which, when using the example from the manual, causes the app to hang. I'm just calling it once per update tick of my application but I have no idea how acceptable this is. I suspect it would mess with anything time based in the gui..

Anyway; The complete list of jars needed to get this running in an existing lwjgl project is:

nifty-1.4.0.jar
nifty-default-controls-1.4.0.jar
nifty-lwjgl-renderer-1.4.0.jar
nifty-openal-soundsystem-1.4.0.jar
nifty-style-black-1.4.0.jar
eventbus-1.4.jar
jglfont-core-1.4-SNAPSHOT.jar
jglfont-lwjgl-1.4.SNAPSHOT.jar
xxp3_min-1.1.4c.jar
xpp3_xpath-1.1.4c.jar
xpp3-1.1.4c.jar

**Comment by oberien** [comment]
Exactly, forgot about the xmlpull. We only use xpp3-1.1.4c.jar, not the other ones.
If someone else want's to know the libs, don't forget about the underlaying lwjgl jars :)

**Comment by blisterfingers** [comment]
I was damn sure that jar was the first one I tried and it didn't work, but I just removed the other two and it still works so you're absolutely right..Also I'll close this now.

**Comment by void256** [comment]
I've added the missing external dependencies (eventbus-1.4.jar, jglfont-core-1.4.jar, xpp3-1.1.4c.jar) to the nifty-1.4.0-complete.zip and re-uploaded it to sf.net. So if someone downloads that zip, they will now get the external dependencies with the main Nifty download: https://sourceforge.net/projects/nifty-gui/files/nifty-gui/1.4/

Additionally I've added a page with some minimal LWJGL 1.4 example and some screenshots of setting up an Eclipse project without the use of Maven here: 
https://github.com/void256/nifty-gui/wiki/Nifty-1.4-LWJGL-example-%28without-Maven%29
