### ISSUE TITLE
Possible memory leak with popups?

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#286]
When I debugged my code today, I saw that I had over 500 popups - every time I open up a popup "screen" (like the inventory, shops, etc.) I create a new popup instance from a popup type ("inventory", "trader") each time I press the buttons on my keyboard to open they up.

Now; I am using nifty's closePopup function - and while thats good and it closes it, it actually does not remove the popup instance itself. I guess thats why my game lagged after quite some time of playing (probably cause I had like 2k popups or something…).

Is it a forgotten thing? When crawling through the source code I didn't see a single line that removed an entry from the `popup` object in `Nifty`. I thought that I register a popup type once and then just can create new instances each time I need a new popup. Is that a bug inside of nifty or should I not be doing it the way I am doing it now?

Thanks!

**Comment by spaceemotion** [comment]
Anything new?
I just tried reusing popups now and it seems somewhat fine, but still not 100% what I need.

**Comment by void256** [comment]
Yes, this is working a bit odd. You create an instance of the popup type but then you are supposed to reuse that instance! Not create new ones! :)

Basically you're supposed to create your popup instance once and then use `showPopup()` and `closePopup()` on that single instance only!

The 1.3.2 manual on page 44 explains that, I think.

**Comment by spaceemotion** [comment]
Well, I did - but when I "reopen" that popup i just "reopen" it. That means that any additional popups I created afterwards are still under the first one (when I have two open). It doesn't put the newest one back to the top :(

**Comment by void256** [comment]
Can you provide a SSCCE for that issue please?

Because after a quick look at `nifty.showPopup()` it should create a new layer for the popup at the Screen. And this new layer will be added at the end of the existing layers which really should add it on top of the existing layers in that screen.

**Comment by spaceemotion** [comment]
Oh wait, I think you're right. Once I moved my code to a static context it wasn't creating tons of new instances, hehe.

Now I have to do this to show and close popups though:

``` java
Screen currentScreen = nifty.getCurrentScreen();

if (currentScreen != null) {
    currentScreen.addPopup(popupElement, null);
}

// ...

Screen currentScreen = nifty.getCurrentScreen();
if (popupElement != null && currentScreen != null) {
    currentScreen.closePopup(popupElement, null);
}
```

The `Nifty.showPopup` method takes a screen object, so I have to grab the current screen. Just a thought; maybe it could default to the current screen and only fail if we don't have a screen open atm.

**Comment by void256** [comment]
I think the original issue has been explained and this issue can be closed.
