### ISSUE TITLE
Relative element IDs cause strange names

### ISSUE THREAD

**Issue by armingensler** [nifty-gui/nifty-gui#291]
Hi,
Maybe I'm misunderstanding how relative element IDs (e.g. `#foo`) are supposed to work, but the generated names seem to be somewhat strange. As a simple test I defined the following two custom controls and a simple screen using them:

```
<controlDefinition name="LevelControl1">
    <panel childLayout="vertical">
        <control id="#control2" name="TestControl2" />
    </panel>
</controlDefinition>

<controlDefinition name="TestControl2">
    <panel childLayout="vertical">
        <control id="#btn" name="button" label="..." />
    </panel>
</controlDefinition>

<screen id="MainMenuScreen">
    <layer id="mylayer" childLayout="center">
        <panel id="mypanel" childLayout="vertical">
            <control id="control1" name="LevelControl1" />   
         </panel>
    </layer>
</screen>
```

I expected that the button has the actual name `control1#control2#btn` but this is not the case. I printed a recursive list of all elements in the screen and got the following result:

root (de.lessvoid.nifty.elements.Element@4034c28c)
-> mylayer (de.lessvoid.nifty.elements.Element@4516af24)
--> mypanel (de.lessvoid.nifty.elements.Element@4ae82894)
---> control1 (de.lessvoid.nifty.elements.Element@543788f3)
----> control1#control2 (de.lessvoid.nifty.elements.Element@6d3af739)
-----> control1#control2#control2#btn (de.lessvoid.nifty.elements.Element@1da51a35)
------> control1#control2#control2#btn#control2#btn#btn#text (de.lessvoid.nifty.elements.Element@16022d9d)

As you can see, the button in called `control1#control2#control2#btn`. For some reason the `#control2` part was added twice. It gets even more weird for the `#text` element inside the button. I can't even imagine how that name came into existance. I have encountered names like these at multiple occasions. 

Am I right in thinking that this is a bug?

**Comment by ghost** [comment]
I've encountered this as well, most likely a nasty bug. @void256 Good luck...

**Comment by bgroenks96** [comment]
Hi
If you can send me a unit test with your current Nifty XMLs that I can use to reproduce the bug, I would be happy to take a look and try to work out a fix.

**Comment by armingensler** [comment]
Thanks for your help. What exactly do you need? Only the xml files and a simple test program?

Btw: can I somehow attach files to these comments?

**Comment by armingensler** [comment]
I just realized that I was still using nifty version 1.3.3 while there already exists 1.4.
With 1.4 the problem no longer seems to be there. Sorry for not checking versions first. I guess this issue can be closed.
