### ISSUE TITLE
Site is Down

### ISSUE THREAD

**Issue by darkfrog26** [nifty-gui/nifty-gui#296]
The link: http://nifty-gui.lessvoid.com/ is throwing an error 502.

**Comment by bgroenks96** [comment]
Confirmed. Come on @void256 :wink:

**Comment by void256** [comment]
Already forwarded to my provider .. can't do anything myself at the moment :/

**Comment by oberien** [comment]
For me It's working. Close? :)

**Comment by ghost** [comment]
Working for me also. Closing.
