### ISSUE TITLE
XmlPullParser error when packaging project to .jar

### ISSUE THREAD

**Issue by vincaslt** [nifty-gui/nifty-gui#301]
I am trying to package my project to .jar file using JarSplice, however, when I try to run the generated .jar file, I get the following error: 
![capture](https://cloud.githubusercontent.com/assets/944727/5561140/1dc7ce6e-8dc9-11e4-8297-e026adccf5ef.PNG)

Obviously, the file in Manifest/services does not exist after packaging, but how do I go about this?

**Comment by mkaring** [comment]
In that instance JarSplice corrupts the jar and renders it unusable. You need to make sure that it preserves the manifest files. I am sure that works some way, but I can't tell you how.

In any case if you use such jar file mergers there is a good chance that many things that use reflection and the manifest files get into major trouble.

**Comment by bgroenks96** [comment]
This doesn't appear to be a Nifty issue. Would you agree @mkaring ?

**Comment by vincaslt** [comment]
It most definitely isn't, however I expected someone to know a workaround I'm not aware of. I currently manually import the "services" folder into .jar and it seems to fix the problem somewhat.

**Comment by bgroenks96** [comment]
Ok. Well I'm going to go ahead and close this issue then.

As a note though, if anyone does come by and has a specific solution for this JarSplice issue, please do not hesitate to post it and/or revive this issue.
