### ISSUE TITLE
[2.0] Button example not working when showing FPS

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#305]
Like the title already says, the example does not seem to work properly if the FPS statistics are enabled:

![screen shot 2015-01-05 at 15 28 48](https://cloud.githubusercontent.com/assets/429147/5614272/97d31d26-94ef-11e4-988e-953ea1675344.png)

``` patch
public UseCase_c10_ButtonBasic(final Nifty nifty) throws IOException {
+    nifty.showStatistics(NiftyStatisticsMode.ShowFPS);

    niftyNode = nifty.createRootNodeFullscreen(ChildLayout.Center);

    Button button = niftyNode.newControl(Button.class);
    button.setText("Nifty");

    nifty.applyStyle(UseCase_c10_ButtonBasic.class.getResourceAsStream("UseCase_c10_ButtonBasic.css"));
  }
```

**Comment by void256** [comment]
That was a funny bug :smile: The ":root" CSS selector was being applied to all root nodes which includes the root node that Nifty internally created for the FPS counter.

The commit above should fix that.

As a general note: Nifty can support multiple root nodes and the ":root" CSS selector will be applied to all of them.

Thanks for reporting! :smile:

**Comment by spaceemotion** [comment]
no problem ;) thanks for the fix!
