### ISSUE TITLE
ListBox doesn't react to mouse input

### ISSUE THREAD

**Issue by vincaslt** [nifty-gui/nifty-gui#308]
I am sure I'm not doing something right, but the examples really are not helping. When I create listBox control, it works fine with keyboard, but doesn't react to mouse whatsoever, my xml definition:

``` xml
<nifty xmlns="http://nifty-gui.lessvoid.com/nifty-gui">
    <screen id="start">
        <layer childLayout="center">
            <panel id="roomListPanel" width="400px" height="400px" backgroundColor="#090f" childLayout="absolute-inside">
                <control width="300px" x="50px" y="25px" id="roomList" name="listBox"
                         vertical="optional" horizontal="optional" displayItems="10" selectionMode="Single"
                         visibleToMouse="true"/>
            </panel>
        </layer>
    </screen>
</nifty>
```

I ues slick2d, so this is put in prepareNifty:

``` java
nifty.loadStyleFile("nifty-default-styles.xml");
nifty.loadControlFile("nifty-default-controls.xml");
nifty.fromXml("com/darktimes/client/xml_gui/room.xml", "start");
ListBox listBox = nifty.getCurrentScreen().findNiftyControl("roomList", ListBox.class);
listBox.addItem("a");
```

Also, `nifty.loadStyleFile("nifty-default-styles.xml");` and `nifty.loadControlFile("nifty-default-controls.xml");` throw warnings of conflicts, but withouth those lines, listbox doesn't appear at all.

**Comment by bgroenks96** [comment]
I don't see an "onClick" tag in your XML code anywhere. Did you read the documentation for mouse input?

**Comment by vincaslt** [comment]
I immediately assumed, that if it works with keyboard, it should work similarly with mouse. Also, is there any place I can ask for help, as I feel kind of bad spamming issue section, with questions.

**Comment by bgroenks96** [comment]
We can verify with @void256, but I think this is the current method of support for NiftyGUI. It looks like there used to be a SourceForge forum page, but it's now inactive.

**Comment by void256** [comment]
I'm not sure what state the Slick2D renderer is in and if that's supposed to be working at all (I'm refering to Nifty 1.4 build from source). There have been some discussions some time ago to rewrite it? But I can't remember what the result of that discussion was ...

That being said, I've copied your screen xml into the HelloWorldExample and then run the HelloWorldExample in the nifty-examples-slick2d project. This kinda works for me - I have mouse input and I can select items in the ListBox.

However, the strange thing is: every item I add to the ListBox is added twice. This doesn't make any sense to me right now since the actual ListBox implementation is independent from the RenderDevice implementation. I've tried the same example with the LwjglRenderDevice and it works withhout that strange effect. I'm puzzled.

Can some of the Slick2D experts take a closer look to that one please? I don't get it.

@vincaslt Can you provide a SSCCE? Maybe you do other things to the Slick input (in your game or so?) that messes up the way the Slick2D Nifty stuff expects input or so?

@vincaslt Yes, it's kinda strange to create issues for support but it's ok. Here is the best place to ask questions! I don't think a forum or something would make sense. So please feel free to keep creating issues right here.

**Comment by bgroenks96** [comment]
Who are the Slick2D experts might I ask? I am most certainly not one of them :P

**Comment by vincaslt** [comment]
I will try and experiment with my problem tomorrow, I'll try and do an sscce, if I can't find a problem. That is, however, the first I've heard of the problem you described, I add into the listBox, and everything seems to be adding in fine, one element at a time. In the meantime, you could take a look at my actual source code here: https://github.com/vincaslt/DarkTimes/tree/client  Maybe I'm doing something obviously wrong. The class I've pasted my code from is here: https://github.com/vincaslt/DarkTimes/blob/client/src/com/darktimes/client/states/RoomState.java

The only other weird thing, as I said is that adding these `nifty.loadStyleFile("nifty-default-styles.xml"); nifty.loadControlFile("nifty-default-controls.xml");` lines in `prepareNifty()` generates a lot of warnings like this:

```
Sau 13, 2015 12:19:28 AM de.lessvoid.nifty.Nifty registerStyle
WARNING: Style: nifty-panel was already registered. The new definition will override the previous.
Sau 13, 2015 12:19:28 AM de.lessvoid.nifty.Nifty registerStyle
WARNING: Style: nifty-panel-red was already registered. The new definition will override the previous.
```

but omitting some of those lines, leaving only in one place, makes it not working.

**Comment by vincaslt** [comment]
I played around with the problem, but couldn't find any solution. Here's the example of the problem in action:

Libs used are slick2d latest+nifty 1.4.1, the ones I used can be downloaded from here: http://puu.sh/esBTt/7d8adf34d9.rar

rooms.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.lessvoid.com/nifty-gui">
    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />
    <screen id="start">
        <layer id="mainLayer" childLayout="center">
            <panel id="roomListPanel" width="400px" height="400px" backgroundColor="#090f" childLayout="absolute-inside">
                <control width="300px" x="50px" y="25px" id="roomList" name="listBox"
                         vertical="optional" horizontal="optional" displayItems="10" selectionMode="Single"
                         visibleToMouse="true"/>
            </panel>
        </layer>
    </screen>
</nifty>
```

Main.java

``` java
import org.newdawn.slick.AppGameContainer;
import org.newdawn.slick.SlickException;

import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.controls.ListBox;
import de.lessvoid.nifty.slick2d.NiftyBasicGame;

public class Main extends NiftyBasicGame {

    public Main(String gameTitle) {
        super(gameTitle);
    }

    public static void main(String args[]) {
        Main game = new Main("ListBox test");
        AppGameContainer app;
        try {
            app = new AppGameContainer(game, 800, 600, false);
            app.setAlwaysRender(true);
            app.start();
        } catch (SlickException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void prepareNifty(Nifty nifty) {
        nifty.fromXml("room.xml", "start");
        ListBox listBox = getNifty().getCurrentScreen().findNiftyControl("roomList", ListBox.class);
        for (int i = 0; i < 20; i++)
            listBox.addItem("Some element " + i);
    }
}
```

Also, is it possible to have elements with the same name in the list, as simply adding them with `listBox.addItem()` makes a user unable to select them, no matter which one you select, only the first one is highlighted.

**Comment by vincaslt** [comment]
OK, so adding items to the list was explained in wiki, so never mind that question. However, it seems that not only the listBox doesn't receive mouse input, but also textBox and probably all other controls for that matter. Maybe it could be something wrong how nifty detects input in slick renderer or something? Can anyone else confirm that the issue is present in the example I've given?
