### ISSUE TITLE
Incorrect element properties retrieved for getWidth(), getX(), etc

### ISSUE THREAD

**Issue by Davi-DeGanne** [nifty-gui/nifty-gui#310]
When I use getWidth(), getHeight(), getX(), or getY() on any of my Element objects, I get incorrect values. Specifically, they almost all return zero, which is clearly incorrect as I can plainly see my many elements having non-zero widths, heights, and coordinates when I run the program. This issue makes it very difficult to modify the GUI from java after screen-building, and I believe it is the reason my scrollbars and scrollpanels do not function. The only non-zero values I have gotten are for the root elements of each screen, which return a width and height equal to my screen's width and height respectively. 

I am using the Slick2d renderer. I build my screens using ScreenBuilders, and use XML for my custom controls and styles. I have noticed that my elements do not have TextRenderer objects (by using element.getRenderer(TextRenderer.class)) and I believe this may be related.

This example is an excerpt of my program, which is too large to post here, however every bit of code having something to do with nifty is copied below (the cursor and the text in the second screen are rendered using slick, not nifty).

``` java
public class CoolGame extends BasicGame implements InputProviderListener, MouseListener, KeyListener {

    private Nifty nifty;

    public static void main(String[] args) {
        try {
            theCoolGame = new CoolGame();
            AppGameContainer app = new AppGameContainer(theCoolGame);
            app.setDisplayMode(1600, 900, false);
            app.start();
        }
        catch (SlickException e) {
            e.printStackTrace();
        }
    }

    private CoolGame() {
        super("A Cool Game");
    }


    @Override
    public void init(GameContainer container) throws SlickException {

        ...

        Input in = container.getInput();
        inputProvider = new InputProvider(in);
        inputProvider.addListener(this);
        this.setInput(in);

        SlickInputSystem inputSystem = new PlainSlickInputSystem();
        inputSystem.setInput(in);
        in.addListener(inputSystem);
        nifty = new Nifty(
                new SlickRenderDevice(container),
                new NullSoundDevice(),
                new PlainSlickInputSystem(),
                new FastTimeProvider());

        niftySetup();

        nifty.gotoScreen("MAIN_MENU");

        ...
    }

    public void niftySetup() {

        new ScreenBuilder("MAIN_MENU") {{
            layer (new LayerBuilder("coolLayer") {{
                childLayoutCenter();
                backgroundImage("resources/graphics/art/landscape01-1920x1080.png");
                panel(new PanelBuilder("coolPanel") {{
                    width("62%");
                    height("62%");
                    childLayoutVertical();
                    text(new TextBuilder("coolText") {{
                        align(Align.Right);
                        marginBottom("16px");
                        font("resources\\Graphics\\Fonts\\cooperSketched50.fnt");
                        text("A Cool Game!");
                    }});
                }});
            }});
        }}.build(nifty);


        Collection<String> c = nifty.getAllScreensName();
        for (String screenName: c) {
            System.out.println("\n<=============  Screen: " + screenName + "  =============>");
            printAllElementInfo(nifty.getScreen(screenName).getRootElement());
        }
    }

    private void printAllElementInfo(Element e) {
        System.out.println();
        System.out.println("--> Element: " + e.getId());
        System.out.println(e.getElementStateString(""));
        for (Element e2: e.getChildren())
            printAllElementInfo(e2);
    }

    public void render(GameContainer container, Graphics graphics) throws SlickException {

        ...

        nifty.render(false);

        ...

    }

    public void update(GameContainer container, int deltaT) throws SlickException  {

        nifty.update();

        ...

    }
```

Output:

```
<=============  Screen: MAIN_MENU  =============>

--> Element: root
 style [null]
 state [normal]
 position [x=0, y=0, w=1600, h=900]
 constraint [0.0px, 0.0px, 1600.0px, 900.0px]
 padding [0.0px, 0.0px, 0.0px, 0.0px]
 margin [0.0px, 0.0px, 0.0px, 0.0px]
 flags [ enabled(0), visible]
 effects [{}]
 renderOrder [0]
 render order: [coolLayer (0)]

--> Element: coolLayer
 style [null]
 state [normal]
 position [x=0, y=0, w=1600, h=900]
 constraint [d, d, d, d]
 padding [0.0px, 0.0px, 0.0px, 0.0px]
 margin [0.0px, 0.0px, 0.0px, 0.0px]
 flags [ enabled(0), visible]
 effects [{}]
 renderOrder [0]
 render order: [coolPanel (0)]

--> Element: coolPanel
 style [null]
 state [normal]
 position [x=0, y=0, w=0, h=0]
 constraint [d, d, 62.0%, 62.0%]
 padding [0.0px, 0.0px, 0.0px, 0.0px]
 margin [0.0px, 0.0px, 0.0px, 0.0px]
 flags [ enabled(0), visible]
 effects [{}]
 renderOrder [0]
 render order: [coolText (0)]

--> Element: coolText
 style [null]
 state [normal]
 position [x=0, y=0, w=0, h=0]
 constraint [d, d, d[362.0px], d[58.0px]]
 padding [0.0px, 0.0px, 0.0px, 0.0px]
 margin [0.0px, 0.0px, 0.0px, 16.0px]
 flags [ enabled(0), visible]
 effects [{}]
 renderOrder [0]
 render order: 
```

Screens:

![screen](https://cloud.githubusercontent.com/assets/10736422/5949681/99af5760-a70d-11e4-873b-be4af2727c2a.jpg)
![screen2](https://cloud.githubusercontent.com/assets/10736422/5949680/99af0ed6-a70d-11e4-9b24-e11574be2657.jpg)

**Comment by vincaslt** [comment]
Could you provide a code excerpt where this problem happens?

**Comment by void256** [comment]
I've added the following test code to https://github.com/void256/nifty-gui/blob/1.4/nifty-examples/src/main/java/de/lessvoid/nifty/examples/helloworld/HelloWorldStartScreen.java#L23

``` java
  @Override
  public void onStartScreen() {
    System.out.println(nifty.getCurrentScreen().findElementById("panel").getWidth());
    System.out.println(nifty.getCurrentScreen().findElementById("panel").getHeight());
  }
```

and then I've run the corresponding Slick2D startup code for the example: https://github.com/void256/nifty-gui/blob/1.4/nifty-examples-slick2d/src/main/java/de/lessvoid/nifty/examples/slick2d/helloworld/HelloWorldDemoMain.java

And I see in the console:

```
358
192
```

which appears to work for me.

So I'm not sure what causes your problem. I agree with @vincaslt that some example code would help to pinpoint your issue. As always a http://sscce.org would simplify helping you.

**Comment by Davi-DeGanne** [comment]
I updated the first post with an excerpt and debug info from my code. Sorry if it's a bit long, I tried to be concise but wanted to include all the relevant code involving nifty.

**Comment by void256** [comment]
Yes, I think the problem is, that you're trying to output the element positions right after building the screen but at that time the Screen is not laid out yet. So the element positions are not resolved.

Can you try to output/access the element positions later? In a ScreenController method like bind() or onStartScreen() would be best. If that's not possible you could try to call layoutLayers() on the newly created screen ... but I'd prefer using a ScreenController method :smile:

Edit: Oh and btw these screenshots look pretty!

**Comment by Davi-DeGanne** [comment]
Oh wow that definitely fixed my problem. So when are screens laid out then? It seems strange to me that they are laid out after building, but before ScreenController binding... I had assumed that ScreenController binding happened during screen building.

Anyway thank you for the help, and for the amazing GUI! It is helping me make my project look even better :smile:

**Comment by void256** [comment]
Yes, I agree. One of the many odd things in Nifty 1.x :wink:

Currently a screen is initialized when you nifty.gotoScreen() to it which will init a lot of things including the layout of all the elements in a screen. The builders where added later when all of the other mechanism where already in place. I think this is the reason they are not immediately laid out and initialized.
