### ISSUE TITLE
Nifty-GUI won't let OpenGL render

### ISSUE THREAD

**Issue by Tutzen** [nifty-gui/nifty-gui#311]
I'm aware this problem has been talked about already, maybe even multiple times, but I couldn't really use the explanations/solutions provided for me. Basically, nifty-gui seems to hinder my OpenGL code from rendering. The strange thing is that it also occurs when I exit nifty and prevent every code snippet in my while-loop associated with nifty from running. I tested the OpenGL-related code without nifty and it works fine, so I'm pretty sure the problem is that I don't know exactly how to desing my rendering process for both nifty and OpenGL to work together.

This is my Graphics class:

``` Java
public class Graphics implements Runnable {

    private static boolean gameStarted = false;

    @Override
    public void run() {
        try {
            Display.setDisplayMode(new DisplayMode(400, 200));
            Display.setFullscreen(false);
            Display.setTitle("Trappers");
            Display.create();
        } catch(LWJGLException e) {
            System.out.println("[ERROR:] LWJGL display could not be created.");
            System.out.println(e.getMessage());
            System.exit(0);
        }

        UI.initUI();
//        Controls controls = new Controls(ui.getInputSystem());

        while(!Display.isCloseRequested()) {
//            controls.checkInput();
            processMessages();
            if(gameStarted) {
                drawEnvironment();
                UI.getNifty().update();
                glMatrixMode(GL_MODELVIEW);
                glPushMatrix();
                glLoadIdentity();
                UI.getNifty().render(true);
                glPopMatrix();
            } else {
                UI.getNifty().update();
                UI.getNifty().render(true);
            }
            Display.update();
            Display.sync(60);
        }

        Client.setRunning(false);
        Display.destroy();
        synchronized(Client.getLOCK()) {
            Client.getLOCK().notify();
        }
    }

    private static void initOpenGL() {
        glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
        glDisable(GL_DEPTH_TEST);
        glDisable(GL_LIGHTING);

        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        gluOrtho2D(0, 800, 600, 0);

        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
    }

    private static void processMessages() {
        while(!Messages.getMessages().isEmpty()) {
            String message = Messages.getMessages().poll();
            switch(message) {
                case "GAMESTARTS": startGame(); break;
                default: break;
            }
        }
    }

    private static void startGame() {
        UI.getNifty().fromXml("resources/ClientGameScreen.xml", "start", 
                new ClientGameController());
//        UI.getNifty().exit();
        changeResolution();
        initOpenGL();
        gameStarted = true;
    }

    private static void changeResolution() {
        try {
            Display.setDisplayMode(new DisplayMode(800, 600));
            UI.getNifty().resolutionChanged();
        } catch(LWJGLException e) {
            System.out.println("[ERROR:] Resolution could not be changed.");
            System.out.println(e.getMessage());
            System.exit(0);
        }
    }

    private static void drawEnvironment() {
        // Clear the screen and depth buffer
        glClear(GL_COLOR_BUFFER_BIT);  
        glLoadIdentity();

        // set the color of the quad (R,G,B,A)
        glColor3f(0.5f, 0.5f, 1.0f);

        // draw quad
        glBegin(GL_QUADS);
        {
            // Top-left vertex
            glColor3f(0.5f, 0.5f, 1f);
            glVertex2f(0, 500);

            // Top-right vertex
            glColor3f(0.5f, 0.5f, 1f);
            glVertex2f(800, 500);

            // Bottom-right vertex
            glColor3f(0.5f, 0.5f, 1f);
            glVertex2f(800, 600);

            // Bottom-left vertex
            glColor3f(0.5f, 0.5f, 1f);
            glVertex2f(0, 600);
        }
        glEnd();
    }
```

I'd be very thankful for a code snippet that tells me how to setup the rendering process correctly. Best regards!

**Comment by void256** [comment]
I answered a similar question on Stackoverflow: http://stackoverflow.com/a/13425866/1717169 and I've now added this - or at least the beginning - to the wiki: https://github.com/void256/nifty-gui/wiki/How-to-save-OpenGL-state-when-render-with-Nifty

The wiki entry is something I wanted to do since a long time since a lot of people have problems with that. Basically you need to save all the OpenGL state that Nifty changes - which is not really documented somewhere at the moment unfortunately. Can you check the wiki entry above and see if that helps?

**Comment by Tutzen** [comment]
First of all, thanks for answering so quickly again. Unfortunately, this code snippet doesn't work for me. I've already encountered that Stackoverflow question and tried your solution earlier this day, but to no effect. I'm pretty confused because I guess it SHOULD work like this, yet it doesn't - like I said, I tried the complete OpenGL code in a different project just to make sure it works, so I really wouldn't have any idea of what's the issue if it wasn't for some kind of nifty-OpenGL correlation. I hope you can shed some light on it...

**Comment by void256** [comment]
For your example above I would suggest disabling GL_TEXTURE_2D when returning from Nifty since you only want to render untextured Quads? Nifty probably enables Texturing in it's render() method somewhere.

Btw: Which NiftyRenderDevice do you use and which Nifty version?

**Comment by Tutzen** [comment]
My code now looks as follows:

``` Java
drawEnvironment();
UI.getNifty().update();
glPushMatrix();
glPushAttrib(GL_ALL_ATTRIB_BITS);
UI.getNifty().render(false);
glPopAttrib();
glPopMatrix();
glDisable(GL_TEXTURE_2D);
```

Still doesn't work, though. I'm using Nifty 1.4.0 because I had some problems with 1.4.1 and setup the project before 1.4.1 was released, so I didn't want to change the version at this time.

Nifty is set up in my UI class:

``` Java
public class UI {

    /**
     * The nifty object used to interact with the GUI.
     */
    private static Nifty nifty;

    private static LwjglInputSystem inputSystem;

    public static void initUI() {
        inputSystem = initInput();
        nifty = initNifty(inputSystem);
        nifty.fromXml("resources/ClientStartScreen.xml", "start", 
                new ClientStartController());
    }

    /**
     * Initialises the LWJGL Input System that is needed to use Nifty GUI.
     * @return An instance of the LWJGL Input System
     */
    private static LwjglInputSystem initInput() {
        try {
            LwjglInputSystem inputSystemTmp = new LwjglInputSystem();
            inputSystemTmp.startup();
            return inputSystemTmp;
        } catch(Exception e) {
            System.out.println("[ERROR:] Input System could not be"
                    + "initialised.");
            System.out.println(e.getMessage());
            return null;
        }
    }

    private static Nifty initNifty(LwjglInputSystem inputSystem) {
        try {
            return new Nifty(new BatchRenderDevice(
                    LwjglBatchRenderBackendCoreProfileFactory.create()),
                    new NullSoundDevice(), inputSystem, 
                    new AccurateTimeProvider());
        } catch(Exception e) {
            System.out.println("[ERROR:] Nifty could not be initialised.");
            System.out.println(e.getMessage());
            return null;
        }
    }

    public static Nifty getNifty() {
        return nifty;
    }

    public static LwjglInputSystem getInputSystem() {
        return inputSystem;
    }

}
```

If I delete all the UI-related code in the Graphics class and call initOpenGL() just before I enter my while-loop, OpenGL renders the code, just tested it again to make sure it's not a mistake I've made with some other part.

**Comment by void256** [comment]
Yes, that's not going to work :smile:

The problem is this part: `new BatchRenderDevice(LwjglBatchRenderBackendCoreProfileFactory.create())`. You're using a CoreProfile OpenGL 3.2+ Nifty Renderer and mix it with the old immediate mode OpenGL rendering that you are doing on your own.

Can you try to use `LwjglBatchRenderBackendFactory` instead of `LwjglBatchRenderBackendCoreProfileFactory`?

**Comment by void256** [comment]
Btw: Sorry about the long, kinda ugly names :wink: the core profile renderer is supposed to be used when your other OpenGL code is using core profile as well. You can't really mix that with the way you want to render it. With the regular none-core-profile RenderBackend it should work better ...

**Comment by Tutzen** [comment]
I always end up with extremely long and ugly names when I code, probably because I always want to describe everything my methods do in their names instead of their javadoc, so don't worry, I'm used to it. :D 

It works now! Thank you! Replacing the factory was the key to success here. I'd love to use a more modern approach to OpenGL, but I'm afraid I don't have enough time for this current project to learn it completely from scratch.

I only have one problem left now - the square I'm trying to draw to the screen doesn't seem to recognize that the display resolution changes to 800*600 although I'm calling the resolutionChanges() method. Could you tell me whether that's something related to nifty, too or if that's an issue with OpenGL (or, more likely, myself using the wrong code again)?

**Comment by Tutzen** [comment]
Okay, nevermind, I got this. Just destroyed the display and created it again, works like a charm now. Thank you so very much, you saved me the second time now already! It's amazing how fast and on-point your support is, I really appreciate it.

Is there a way to donate for nifty-gui or you in particular?

**Comment by void256** [comment]
You're welcome!

There is a link on the old sf.net page for nifty-gui donations: http://sourceforge.net/p/nifty-gui/donate/?source=navbar

Thanks!

**Comment by Tutzen** [comment]
Hey void, hope you'll notice this post since I don't want to open yet ANOTHER issue...

OpenGL works fine now, like I said - but now I've got problems with the rendering of nifty in my actual game window. It looks like this:

![nifty-text](https://cloud.githubusercontent.com/assets/10613635/5966748/4de2ca10-a807-11e4-9c1f-cfa36aa61e4e.png)

Does that sound (or, to be exact, look) familiar to you? I already tried to mess around a bit with my rendering loop but if I render nifty before OpenGL, it doesn't appear on the screen at all and when I call render(true) instead of render(false), I get a completely black screen.
Can you help me once more with this issue? Didn't find an appropriate answer via Google or another issue right here yet...

Some code excerpts that may be helpful:

The screen:

``` XML
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.lessvoid.com/nifty-gui">
    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />

    <screen id="start" 
            controller="htw.gt3.trappers.client.screens.ClientGameController">
        <layer childLayout="vertical">
            <panel id="playerPointsPanel" height="100%" width="100%" 
                   align="left" childLayout="horizontal">
                <text font="aurulent-sans-16.fnt" color="#000000" 
                      text="Collisions: " textHAlign="left" />
                <text id="playerPoints" font="aurulent-sans-16.fnt" 
                      color="#000000" text="0" textHAlign="left" />
            </panel>
        </layer>
    </screen>

</nifty>
```

The rendering loop:

``` Java
while(!Display.isCloseRequested()) {
      Controls.checkInput();
      processMessages();
      if(prepares) {
            createSegment();
            createTraps();
            player.setSpeed(player.RUNNINGSPEED);
            prepares = false;
      }
      if(started) {
            Graphics.render();
            UI.getNifty().update();
            glPushMatrix();
            glPushAttrib(GL_ALL_ATTRIB_BITS);
            glEnable(GL_BLEND);
            UI.getNifty().render(false);
            glDisable(GL_BLEND);
            glPopAttrib();
            glPopMatrix();
            glDisable(GL_TEXTURE_2D);
       } else {
             UI.getNifty().update();
             glEnable(GL_BLEND);
             UI.getNifty().render(true);
             glDisable(GL_BLEND);
       }
       Display.update();
       Display.sync(60);
}
```

I hope it doesn't have anything to do with the new render factory I'm using? It works fine in screens without actual OpenGL objects where I don't render OpenGL at all, the issue only starts when there is OpenGL drawn onto the screen.
