### ISSUE TITLE
Can't pass element controller instance using element builders

### ISSUE THREAD

**Issue by Davi-DeGanne** [nifty-gui/nifty-gui#316]
When using a ScreenBuilder, you can set the screen's ScreenController instance by passing it to the controller() method. You can also pass a Controller to any ElementBuilder using the same syntax. This is deceiving, however, because the Controller instance passed to the ElementBuilder is not used, instead, the name of it's class is stored, and later an entirely new instance is created from that class.

It would be far more useful if the ElementBuilder kept the Controller instance you gave it and attached it to the resultant Element.

If that isn't feasible, then I suggest the controller() method in ElementBuilder take a class that extends Controller, rather that an actual Controller object; it is cumbersome to have to declare a variable just to tell the ElementBuilder what class to use for its controller.

**Comment by JurgenCruz** [comment]
I ended up using the NiftyEventSubscriber annotation and forget the controllers
