### ISSUE TITLE
wrap="true" does not work in Java2D renderer

### ISSUE THREAD

**Issue by barefists** [nifty-gui/nifty-gui#317]
Hi there,

I'm working on a game in Processing, and using Nifty with the Java2D renderer to display the GUI for it. Everything works perfectly, except for wrapping - I can't for the life of me figure out how to get it to work. So I've tried out the following example, modified slightly from the 1.3.2 pdf manual.

``` xml
<nifty>
    <screen id="start">
        <layer id="layer" childLayout="center">
            <panel width="50%" height="50%" backgroundColor="#33af" childLayout="horizontal">
                <text width="100%" height="100%" font="verdana-smallregular.fnt" wrap="true" textHAlign="left" textVAlign="top" text="very long text very long text very long text very long text very long text very long text very long text very long text "/>
            </panel>
        </layer>
    </screen>
</nifty>
```

But the screen turns out like this:
![Screenshot of issue](https://dl.dropboxusercontent.com/u/23443863/issue-screenie.jpg)

Would appreciate any help with the issue.

Regards,
XM

**Comment by void256** [comment]
That's a bit odd! Your example code works for me using the current master branch (1.4.1-SNAPSHOT) and the Java2D renderer!

I've just took your xml copied it into "nifty-gui/nifty-examples/src/main/resources/helloworld/helloworld.xml" and run "nifty-gui/nifty-examples-slick2d/src/main/java/de/lessvoid/nifty/examples/slick2d/helloworld/HelloWorldDemoMain.java".

Which Nifty version do you use?
Do you miss to call update() somewhere or so? It looks to me as if there is an internal layout pass missing or something ...

**Comment by barefists** [comment]
Thanks for the fast reply!  I'm using nifty 1.4.1. I'll check if I missed anything during the integration into Processing. Though it's puzzling cause everything else works fine (effects are rendering, etc)

If you think of anything that might possibly be the cause, please lemme know. :)

EDIT:
Hmm update() and render(false) is called every frame (set at 30 fps) and looks to be updating all the elements fine. Canvas is cleared by Processing before each render call. Those 2 should be the only regularly called functions for the healthy running of nifty right? I'll look around to see if there is anything else I'm missing.

XM

**Comment by barefists** [comment]
Made TextRenderer spit out some numbers for investigation.
maxWidth is 320px.
font.getWidth(originalText) is 648px.
Both lineWrapping and isCalculatedLineWrapping is set to "true" at this point.

Despite this, textLines remain as a single entry:
[0] "very long text very long text very long text very long text very long text very long text very long text very long text"

Still utterly lost as to where the issue is. Sigh. Will take a break and return to this tomorrow.

**Comment by barefists** [comment]
Okay, finally found  a method that works - if I change the text using setText, the text wraps, but not if it's set from the XML. Seems like it's missing the initial layout call or something.

**Comment by void256** [comment]
I'm sorry for your trouble and I'm glad you found a workaround! Trust me, I've been there too - Nifty can be a real ****\* sometimes, unfortunately :-/

Yes, calling update() and render() each frame should be enough. There might be issues if you call update() multiple times each frame so in general one should be careful to call both methods only once (for each frame).

However, I don't think this is the problem in your case. I think you're right and it's some initialisation error, maybe the order of calls is slighly different when you call it from processing? What you could eventually do is to check the order of calls to Nifty and compare the order to the example projects. Especially the time when you call loadFromXml() or you construct your Screen from code. I suspect there might be some subtile difference when you call Nifty in your processing application compared to the pure Java examples.

So if you still have some mood left (but I'd understand if you dont ;-) this might be worth a look! In case your applications source is available I could take a look as well! In the best case you could provide a minimal SSCCE too!?

Eventually we could help others or fix the actual problem then!

**Comment by barefists** [comment]
Be honored to help! Processing is an excellent tool that I hope gets used in larger projects more, so I would love to get Nifty working on it for more people.

You might be right about the loadFromXml() call, I'll shuffle around the place where I call it and see if it makes a difference. Will update you when I get results. :)

EDIT: So I "fixed" the issue by calling render() once just after the Nifty constructor. Calling fromXml() after that wraps fine. I have no idea why, but as long as it works I guess haha!

**Comment by barefists** [comment]
I've extracted all the Nifty bits from my project and put them into a simplified Processing sketch that runs the nifty examples. It's a little messy right now - all the classes are written within the Processing sketch. Moving forward I'll probably clean it up into an external library, but that's for a later date.

You can download the example sketch [here](https://dl.dropboxusercontent.com/u/23443863/nifty_processing_example.rar). You will need the latest [Processing](https://processing.org/) IDE to view and run the code.

**Comment by void256** [comment]
Thanks for your example! :smile: There was indeed a problem in the Java2D-Renderer which I've explained in the commit above!

In general the Java2D renderer has other issues and is not really maintained right now, unfortunately :/ One issue is the lack of bitmap font support. Internally your font is not being used and defaults back to Arial 17 or something. There is a strange mechanism to register Fonts with the Java2D-Renderer as well. I think it's original author Ariel didn't have the time to finish it and since everyone uses the OpenGL based renderers no one saw the need to fix that.

Processing supports OpenGL too maybe one could write a RenderDevice-Implementation that directly interfaces with the Processing rendering API someday too. This would be cool :)

But anyway can you try to use the 1.4.2-SNAPSHOT of the Java2D-Renderer jar? I think this will fix your issue :)

PS: It's great that you made Nifty work with Processing! Keep up the good work! Maybe we can someday have a RenderDeviceProcessing implementation to make integrating Nifty even more easy as well :D

**Comment by barefists** [comment]
No problem! :) The fonts issue isn't that much of a problem - just needs more documentation I think. I'm adding in my own fonts by creating my own FontProvider and adding fonts directly to it. I think most people like bitmap fonts better because of the fancy effects they can do with the png file. It doesn't affect me as much because I'm making a pixel art game, so my fonts are supposed to look [low res and 80s arcade machine like](https://dl.dropboxusercontent.com/u/23443863/riz.jpg).

Processing has an OpenGL canvas that's rendered with JOGL, making Nifty work on that shouldn't be that much of a problem - I'll look into in my spare time. Theoretically we just need an adapter to run the Java2D or JOGL renderers in Processing, the ones that need actual code written will be the Input and Audio devices.

Will try out the 1.4.2-SNAPSHOT later and let you know the results!

EDIT: 1.4.2-SNAPSHOT works perfectly now. Thanks for the fix! :)

**Comment by bgroenks96** [comment]
The bitmap font thing is supposed to be dealt with in my Java2D renderer refactoring project. Unfortunately, I ran into some problems a while ago when working on it, and I haven't resumed work yet. Hopefully, if it ever gets finished, it will help with some of the issues here.

**Comment by barefists** [comment]
Awesome! I am now working on a RenderDeviceProcessing implementation of the code (but wrapping it around the Java2D renderer to save time) Will send a pull request when I'm ready. This new version uses Processing's native Bitmap font format .vlw. Since it's targeted at Processing users, they will be more familiar with this format.

Once you are ready on your side, I'll make the RenderDevice auto detect the font format used and swap font renderers when necessary.

EDIT: @bgroenks96 , can you make your AwtToNiftyKeyCodeConverter class public? I'm hoping to use it in my InputSystem as well.
