### ISSUE TITLE
Slick2D, Nifty GUI interaction problem, Nifty does not get any Input

### ISSUE THREAD

**Issue by raLaaa** [nifty-gui/nifty-gui#323]
Hey guys,

I'm currently trying to let my Game interact with my GUI, but somehow I'm encountering a problem. Slick is not forwarding any Input towards Nifty, or maybe it is but Nifty does not receive any incoming Input.
The only thing I could find on the Internet was this:

http://www.gamedev.net/topic/619545-slick2d-nifty-gui-interaction-problem/

I'm encountering except the same problem, my code is quite the same as stated in the thread above:

ScreenController:

```
    class MyScreenController implements ScreenController {
public void bind(Nifty nifty, Screen screen) {}
public void onEndScreen() {}
public void onStartScreen() {}
public void next() {
 System.out.println("next() called from MyScreenController");
   }
       }
```

XML File:
![issue](https://cloud.githubusercontent.com/assets/11082042/6825683/94d18824-d2fc-11e4-9b68-e930324142c4.jpg)

MainClass:

```
     public class MainGameState extends BasicGame {
       public Nifty nifty;
     public MainGame() {
       super("Test");  
    }
      public void init(GameContainer container, StateBasedGame game) throws SlickException {
    nifty = new Nifty(new SlickRenderDevice(container), new NullSoundDevice(),                        new        plainSlickInputSystem(), new AccurateTimeProvider());              
     nifty.fromXml("/xml/MainState.xml");
 nifty.gotoScreen("start");
      }

          public void update(GameContainer container, StateBasedGame game, int delta) throws                            SlickException {
    nifty.update();
     }

public void render(GameContainer container, StateBasedGame game, Graphics graphics)    throws  SlickException {
nifty.render(false);
```

   }

```
   public static void main(String[] args) throws SlickException {
 AppGameContainer app = new AppGameContainer(new MainGame());
 app.setAlwaysRender(true);
 app.setDisplayMode( 1260 , 720, false); //window size
 app.start();   
   }
  }
```

EDIT: xml code is not shown correctly somehow, I attached an image. But the xml file should be right anyway in my opinion, atleast I'm not encountering any Exceptions while validating the xml.

**Comment by bgroenks96** [comment]
The problem may be with how you're calling `nifty.update()` and `nifty.render(false)` - I'm not 100% sure on that though, will need verification from @void256 on that.

Try lowering the Log level to fine in log.properties to see what Nifty is saying under the hood. It might give you an indication of whether or not any input is being received at all.

**Comment by raLaaa** [comment]
Am I right if I want to switch the Log level that I do it via:
Logger.getLogger("de.lessvoid.nifty").setLevel(Level.FINE); ?
I called it in my init method after initiliazing the nifty object, the console is not printing out any additional information tho.

**Comment by bgroenks96** [comment]
I think you have to pass in a log configuration file to let the JVM know you want the logging system to submit log events at or below a certain level.

http://www.javapractices.com/topic/TopicAction.do?Id=143

**Comment by raLaaa** [comment]
Alright, it took me a while how to figure out how to load the propertie file exactly but I think I've done it right now.

   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice disableClip
   FEIN: disableClip()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice  setBlendMode
   FEIN: setBlendMode()
    Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderImage
   FEIN: renderImage2()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice renderFont
   FEIN: renderFont()
   Mär 26, 2015 8:13:29 PM de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice setBlendMode
   FEIN: setBlendMode()

That's a bit of the stuff I get, doesn't look like any Input is recognized. :/

Update:

I was playing a bit around and testing some stuff and found this in a the log:
If I disable the nifty.render I'm just receiving this all the time:

Mär 26, 2015 8:21:44 PM de.lessvoid.nifty.Nifty update
FEIN: 
focus element (mouse):    ---
focus element (keyboard): null (de.lessvoid.nifty.elements.Element@d9b808)
focus element size: 5 [null, charInfoButton, null, inventoryButton, null]

Note: I've changed the GUI a bit, thats why it's referring to something called charInfoButton for example, just in case u are surprised.

**Comment by bgroenks96** [comment]
What exactly are you doing with the mouse? Just clicking on the element?

**Comment by raLaaa** [comment]
Nothing, I just started my programm. As soon as nifty update starts I'm getting this feedback.

**Comment by raLaaa** [comment]
No one has a clue or something I could try out? :(

**Comment by mkaring** [comment]
The problem is that you are not using the facilities that come along with
the Slick renderer that do all the initialization for you. This means you
have to do the initialization yourself and you missed doing just that.

Now the Problem is that the PlainSlickInputSystem is forwarding the events
to Nifty, but it is not receiving any events from Slick. What you need to
do, is to add the instance of the PlainSlickInputSystem as a listener to
the Slick input provider that is accessible from the
GameContainer.getInput() function.

In any way I highly recommend you using the Game(state) implementations
that are provided with the SlickRenderer to get around problems like this,
as these classes do the proper initialization for you.

Regards

raLaaa notifications@github.com schrieb am Mi., 1. Apr. 2015 um 12:22 Uhr:

**Comment by raLaaa** [comment]
That worked :) Thanks a lot!
