### ISSUE TITLE
Slick renderer mouse cursor change crash

### ISSUE THREAD

**Issue by lawallet** [nifty-gui/nifty-gui#324]
I probably missed something simple, but any example that uses NiftyMouse's enableMouseCursor method to change the mouse cursor throws the exception " java.lang.UnsupportedOperationException: Use enableCursor(GameContainer container).". I've looked at the source for it and see that all the method does is throw that exception, but see no mention of how to use enableCursor. Do I use Slick's built in cursor change or is there a different object I instantiate to make it work?

**Comment by bgroenks96** [comment]
What exactly are you calling enableMouseCursor on? I only know of that method existing for RenderDevices, and as far as I can tell from [this source file](https://github.com/void256/nifty-gui/blob/1.4/nifty-renderer-slick2d/src/main/java/de/lessvoid/nifty/slick2d/render/SlickRenderDevice.java#L135), it should work fine for SlickRenderDevice.

**Comment by lawallet** [comment]
the conflicting code code comes from HelloWorldStartScreen class:

NiftyMouse niftyMouse = nifty.getNiftyMouse();
    try {
      niftyMouse.registerMouseCursor("mouseId", "nifty-cursor.png", 0, 0);
      niftyMouse.enableMouseCursor("mouseId"); //offending code statement
...

The last line is what causes the error as it eventually goes down to de.lessvoid.nifty.slick2d.render.cursor.AbstractNativeSlickMouseCursor and calls enable which causes the throw

**Comment by ghost** [comment]
@lawallet You're not doing anything wrong. I've submitted a bugfix, and I actually caused this bug from an old refactoring that I performed.

After @void256 merges this, all you will have to do now is change the way you're instantiating Nifty to include the GameContainer instance:

new Nifty(new BatchRenderDevice(SlickBatchRenderBackendFactory.create(gameContainer)), new SlickSoundDevice(), new SlickSlickInputSystem(this), new LWJGLTimeProvider());

Or you can use NiftyGameState#initGameAndGUI, and this will be done automatically.

**Comment by ghost** [comment]
@lawallet @void256 Can someone please test the bugfix now that it's merged? Thanks!
