### ISSUE TITLE
Add JOGL 2.3.1 support

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#327]
Hi

Please update the JOGL renderer so that it uses the very latest version of JOGL (currently 2.3.1). You just have to set jogamp.version to 2.3.1 here: 
https://github.com/void256/nifty-gui/blob/1.4/nifty-renderer-jogl/pom.xml#L10

Replace "javax.media" by "com.jogamp" in the renderer and the examples. A few constants have been moved to other GL subclasses.

**Comment by ghost** [comment]
@bgroenks96 Maybe you can look at this issue if you have some time.

**Comment by bgroenks96** [comment]
Sure thing, I'll take care of that today.

Thanks for reminding me about that!
