### ISSUE TITLE
link from components to application

### ISSUE THREAD

**Issue by harlock76** [nifty-gui/nifty-gui#330]
hello,

one can create a screencontroller and pass info to its constructor
but what about components/controls themselves ? like a setUserData or something

regards

**Comment by void256** [comment]
A Nifty Control is any class that implements [NiftyControl](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/controls/NiftyControl.java) and a NiftyControl is just something like a "view" onto a collection of Nifty Elements working together to provide a more abstract control representation, like a button or a textfield.

In fact, every Nifty Control is backed by an actual Nifty element which you can access using this method here: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/controls/NiftyControl.java#L22

And once you have the underlying Element you can use this nifty method here, which is actually called setUserData: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/elements/Element.java#L2748

:smile:

I think this will help and I close this issue now. If not then feel free to reopen it!

**Comment by harlock76** [comment]
yes, but it is more a problem of how do you do it when controls are defined in the xml file and instanciated internaly

**Comment by void256** [comment]
You use [findNiftyControl()](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/screen/Screen.java#L448) to get the NiftyControl from the screen using it's id and once you have it you can do whatever you want with it?

**Comment by harlock76** [comment]
yes, whatever one can use to parse new created controls, and give them userdata
but everytime a new element/control is created, I would have to do that check
would be neat to have userdata passed to new controls automaticaly

**Comment by harlock76** [comment]
so far I dont even use setUserData, when a button is clicked it directly acces an Appstate.getInstance().dosomestuff

**Comment by void256** [comment]
You mean like the [Parameters](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/controls/Parameters.java#L10) class that a control will be given as a parameter in the [bind](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/controls/Controller.java#L32) method?

```
   * @param parameter this contains all attributes of the controlDefinition as well as attributes from the control tag
   *                  (where you actually placed the control). Please note that the controlDefinition parameters are
   *                  applied first. Which
   *                  means that attributes in the control tag can overwrite the defaults of the controlDefinition.
```

All attributes you apply to a control in XML are available to the NiftyControl implementation class via the Parameters class.

What else do you need? :grinning:

**Comment by harlock76** [comment]
not string parameters
more like objects instances(like gameappstate instance or the main application instance, so that controls can communicate withthe main application),

**Comment by void256** [comment]
We don't have that and I'm not sure how that could ever work using XML.

And if you create the controls from Java (using the builder pattern f.i.) then - right now - there is no way to allow existing object instances to be used as parameters. You'll have to do that on your own using maybe some Singelton inside the Control or so.

Nifty 2.0 has a more direct way of creating controls and allowing object instances as parameters for controls would be a lot easier to be added there as it would be right now for 1.4.x, unfortunately.

I'm afraid, right now, there are only the ways mentioned above to get parameters into an control.

**Comment by harlock76** [comment]
ok, thanks for your explanations
I'll do it with singletons :-)
