### ISSUE TITLE
try to use console

### ISSUE THREAD

**Issue by harlock76** [nifty-gui/nifty-gui#332]
hello

I try to create a console but 
- I get missing componens errors
- the console shows up but hack the tab key for some reason(I use it in my game)
- I can enter a command, but pressing enter dont do anything
  
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [6] for requested control class             [de.lessvoid.nifty.controls.Console]
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [7] for requested control class [de.lessvoid.nifty.controls.Console]
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [8] for requested control class [de.lessvoid.nifty.controls.Console]
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [9] for requested control class [de.lessvoid.nifty.controls.Console]
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [10] for requested control class [de.lessvoid.nifty.controls.Console]
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [11] for requested control class 
  ...
  avr. 18, 2015 9:47:38 PM de.lessvoid.nifty.elements.Element getNiftyControl
  WARNING: missing element/control with id [console] for requested control class     [de.lessvoid.nifty.controls.Console]
  [/java]
  
  ```
  <controlDefinition name="consoleComponent" controller="mygame.gui.CommandButtonController" >
      <effect> 
          <onShow name="move" mode="fromOffset" offsetY="100" length="300" inherit="true"/> 
          <onHide name="move" mode="toOffset" offsetY="100" length="200" inherit="true"/> 
      </effect>
      <control id="console" name="nifty-console" lines="10" width="70%" valign="top" backgroundColor="#6874" visible="true"/>
  </controlDefinition>
  ```

the event is never reached if I press enter

```
@NiftyEventSubscriber(id="console")
    public void onConsoleCommand(final String id, final ConsoleExecuteCommandEvent command)
    {
        HideCommand hideCommand = new HideCommand();
        hideCommand.setController(this);
....
    }
```

what do I do wrong ?

thanks

**Comment by harlock76** [comment]
sh... I cant paste xml tags

**Comment by harlock76** [comment]
??

**Comment by bgroenks96** [comment]
It seems your GUI element isn't bound correctly to your controller; can you post additional, relevant XML code?

**Comment by harlock76** [comment]
```
    <!-- CONSOLE COMPONENT - - - - - - - - - - - - - - - - - - - - - - - - - - -->  
    <controlDefinition name="consoleComponent" controller="mygame.gui.CommandButtonController" >
        <effect> 
            <onShow name="move" mode="fromOffset" offsetY="100" length="300" inherit="true"/> 
            <onHide name="move" mode="toOffset" offsetY="100" length="200" inherit="true"/> 
        </effect>
        <control id="console" name="nifty-console" lines="10" width="70%" valign="top" backgroundColor="#6874" visible="true"/>
    </controlDefinition>
```

...

```
        <!-- CONSOLE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
        <layer id="consoleLayer" childLayout="center" backgroundColor="#0000">
            <control name="consoleComponent"/>
        </layer>
```

**Comment by bgroenks96** [comment]
Does your input input method in your controller have `@NiftyEventSubscriber(id = "consoleComponent")`? And it is it handling the right event type?

Check that, and if you have problems, go ahead and post the Java code for your controller.

**Comment by harlock76** [comment]
nop, the id of the console is console
"consoleComponent" is the name of the component

```
<!-- CONSOLE COMPONENT - - - - - - - - - - - - - - - - - - - - - - - - - - -->  
<controlDefinition name="consoleComponent" controller="mygame.gui.CommandButtonController" >
    <effect> 
        <onShow name="move" mode="fromOffset" offsetY="100" length="300" inherit="true"/> 
        <onHide name="move" mode="toOffset" offsetY="100" length="200" inherit="true"/> 
    </effect>
    <control id="console" name="nifty-console" lines="10" width="70%" valign="top" backgroundColor="#6874" visible="true"/>
</controlDefinition>
```

**Comment by harlock76** [comment]
I removed CommandButtonController, and now it works, silly of me

**Comment by harlock76** [comment]
but how do I change key bindings ? they are conflicting with mine...

**Comment by bgroenks96** [comment]
What do you mean? Can you be more specific?

**Comment by harlock76** [comment]
well I use TAB key binding and it seems the console too, becos, as it is displayed, all keys go to the console input,
if I press TAB then my game gets back his inputs, so how do I change the TAB binding for the tilde ~ ?
or any other key

**Comment by void256** [comment]
To change the key mapping you can provide a class that implements [NiftyInputMapping](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/input/NiftyInputMapping.java) as the `inputMapping` attribute of an control. The NiftyInputMapping translates actually key events into [NiftyInputEvent](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/input/NiftyInputEvent.java) which are processed by the control later.

If you don't provide your own then [DefaultInputMapping](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/input/mapping/DefaultInputMapping.java) is used which maps the TAB key in combination with shift to toggle the input focus from one control to the other.

You could disable that with your own NiftyInputMapping but I'm not sure if that really helps you because using ~ to toggle the console and using TAB to change the focus to the next control (which is happening in your case, I think?) is not the same. 

Maybe it would be better to set the `inputMapping` at the `<screen ...` level and let it toggle your console on and off? The DefaultInputMapping uses the KEY_F1 to generate the NiftyStandardInputEvent.ConsoleToggle event. I think one of the controls examples used this to toggle the console on or off with the KEY_F1.

**Comment by harlock76** [comment]
ok ,that makes sens,  I'll check it out, thanks

**Comment by harlock76** [comment]
I cant make it work, 
I tried with buttons, TAB always pass from one button to the other

first, if I want to setup an inputMapping to my screen, I need the screen controller to implement KeyInputHandler otherwise I get some error, it does not make any sens, but whatever....

```
    <screen id="Hud" controller="mygame.appstates.HudAppState" inputMapping="mygame.gui.MyNiftyInputMapping">
```

then it just dont work at all, I return a null object, so nifty should not bother wit inputs anymore but it does
    for some reason it creates NiftyInputEvent from thin air

```
   public NiftyInputEvent convert(KeyboardInputEvent inputEvent) 
    {
        return null; <<<<<<<< to make sure nifty dont process events
    }
```

convert() is called AFTER the buton focus is switched to the next one

TAB keeps focusing buttons after buttons

```
<controlDefinition name="keyBindingComponent">
<panel childLayout="horizontal" backgroundColor="#ffffff33" padding="5px" height="30">
    <control width="20%" id="#bindingButton" name="button" label="$bindingText">
        <interact onClick="$action"/>
    </control>
</panel>
```

</controlDefinition>

```
    <layer id="settingsLayer" childLayout="center" backgroundColor="#0000">
        <panel width="400" height="400" childLayout="vertical">
            <control name="keyBindingComponent" bindingDesc="forward" bindingText="???" action="DefineKeyBinding(forward)"/>
            <control name="keyBindingComponent" bindingDesc="backward" bindingText="???" action="DefineKeyBinding(backward)"/>
            <control name="keyBindingComponent" bindingDesc="left" bindingText="???" action="DefineKeyBinding(left)"/>
            <control name="keyBindingComponent" bindingDesc="right" bindingText="???" action="DefineKeyBinding(right)"/>
        </panel>
    </layer>
```

**Comment by harlock76** [comment]
ok, I made it work assigning it to the buttons instead of the screen

**Comment by bgroenks96** [comment]
Great to hear that you got it working. Please be sure to close the issue once your question has been resolved.
