### ISSUE TITLE
TODO Remove this debugging statement

### ISSUE THREAD

**Issue by cuchaz** [nifty-gui/nifty-gui#337]
First of all, I just wanted to say I really like nifty-gui and really appreciate all the work you've saved me. =)

Some of the log messages were confusing to me though. I kept getting warnings about textures, but I couldn't figure out what I was doing wrong. After glancing at the source, it looks like there are a few warnings that aren't really warnings at all in the [batch rendering system](https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/core/BatchRenderBackendCoreProfileInternal.java#L388). It looks like these warnings might never have been intended to be released at all. They're all marked with comments like: "TODO Remove this debugging statement."

Should these warnings be removed? I can send a PR to remove them if that would make it easier for you.

**Comment by bgroenks96** [comment]
Yes, please. Just comment them out though, in case they are needed later during development.

Go ahead and submit that PR when you have a chance and I'll merge it.

Thanks!

**Comment by cuchaz** [comment]
Would it be better to just comment them out, or change them to debug level?

**Comment by bgroenks96** [comment]
Up to you, either is OK. If changing them to debug level solves your issue, then by all means, do that.
