### ISSUE TITLE
Can't get 1.3.3 version of nifty-lwjgl-slick-renderer

### ISSUE THREAD

**Issue by SwiTool** [nifty-gui/nifty-gui#340]
Hi,

i added the repo 

```
    <repositories>
        <repository>
            <id>nifty-maven-repo.sourceforge.net</id>
            <url>http://nifty-gui.sourceforge.net/nifty-maven-repo</url>
        </repository>
    </repositories>
```

but I can't get the version 1.3.3. I can only get the version 1.3 which does not include the method `setResourceLoader` in the `LwjglInputSystem`.

```
        <dependency>
            <groupId>lessvoid</groupId>
            <artifactId>nifty-lwjgl-slick-renderer</artifactId>
            <version>1.3</version>
        </dependency>
```

So if I run : 

```
    LwjglInputTest inputSys = new LwjglInputTest();
    input.startup();
    nifty = new Nifty(new LwjglRenderDevice(), new NullSoundDevice(), inputSys, new AccurateTimeProvider());
```

It just crash, I must use `new NullInputSystem()`...

Any solution ?
Thanks

**Comment by void256** [comment]
I honestly can't remember what the lwjgl-slick renderer was used for :frowning: Is there anything super special about it that the regular lwjgl or slick renderer can't do?

I'm sorry o_O any hints for me? :wink:

**Comment by bgroenks96** [comment]
I'm not seeing any artifacts by that name in the 1.4 or 1.3 branch. Where is that even coming from? It sounds like it might have been just an old name for the Slick2D renderer, since slick is based on LWJGL.

**Comment by SwiTool** [comment]
Indeed sorry I should have posted the reference link.

Here is the instructions I followed. https://github.com/void256/nifty-gui/wiki/Getting-Started

As an additionnal info, take a look at the repository here : http://nifty-gui.sourceforge.net/nifty-maven-repo/lessvoid/nifty-lwjgl-slick-renderer/

I can't tell you why I don't use something else. All tutorials seem to be 2012 dated.. :laughing:

**Comment by SwiTool** [comment]
Wow ok.. I just removed the dependency from lwjgl-slick-renderer and it doesn't crash anymore...
That was... crazy.

My mouse still does not work, but I guess that is because I don't handle it. Where can I find a good tutorial from this version of Nifty GUI ?

Thanks

**Comment by void256** [comment]
Waaaah ... my appologies for the outdated wiki :disappointed: 

Have you tried the manual pdf yet? https://github.com/void256/nifty-gui/tree/1.4/nifty-core/manual

**Comment by SwiTool** [comment]
No, thanks :) 
I'll reopen if there's a problem but I think that should be good.

:smiling_imp:
