### ISSUE TITLE
Hint effect does not set visibleToMouse; Hint layer not deactivating

### ISSUE THREAD

**Issue by dominic-jones** [nifty-gui/nifty-gui#341]
On upgrading to 1.4.1 that Hint hover text had ceased displaying a hover layer. It appeared as if the UI element had no hint effect at all.

Some searching led me to http://sourceforge.net/p/nifty-gui/bugs/53/, and on the surface this is a regression of that.

In testing similarity with that bug, I tried enabling visibleToMouseEvents. The hint layer activates correctly but then fails to deactivate.

**Comment by dominic-jones** [comment]
I have investigated this locally and have a fix I will submit as a pull request.

**Comment by void256** [comment]
I've applied the merge request and guess it's ok to close this issue now! Please re-open if I've missed something.
