### ISSUE TITLE
Is it possible to have a visibleToMouse Panel that doesn't consume mouse events ?

### ISSUE THREAD

**Issue by lyrgard** [nifty-gui/nifty-gui#345]
I'm making a game using jme3 and nifty-gui.
My 3D word (in jme3) can be moved using either the mouse or the keyboard.
I also have some nifty controls (like scrollbars, chatbox) that can get focus and capture keyboard.

What I want to do is to remove focus from any nifty controls if the user click somewhere on the 3D world (outside of any nifty control), so that any keyboard input is transfered to jme and not consumed anymore.

I am able to do that by addind a transparent panel with size 100% under all the control, making it visibleToMouse. I add a clickHandler on my screen :

```
@NiftyEventSubscriber(pattern="gameArea")
public void onClick(String id, NiftyMousePrimaryClickedEvent event) {
    screen.getFocusHandler().resetFocusElements();
}
```

When I click anywhere outside another nifty element, the focus is being reset, and keyboard event are transfered to jme, as I want.

But now my problem is that this panel blocks mouse click event and hide them from jme. Is there a way to mark the event as not consumed, or send it back to jme ?

Or is there a better way to do it ? All I want is basically to be able to "focus" my 3D world by click on it.

**Comment by void256** [comment]
Yes! There is a better way! :smile:

You can call `nifty.setIgnoreMouseEvents(true)` and/or `nifty.setIgnoreKeyboardEvents(true)` to disable event processing in Nifty completely. Doing so will make Nifty ignore all events which basically makes them available to your game.

This is explained in the manual, see: https://github.com/void256/nifty-gui/tree/1.4/nifty-core/manual on page 78 "NIFTY EVENT CONSUMING AND DISABLING EVENT PROCESSING (NIFTY 1.3.2)".

You can disable event processing for individual elements as well, if you want using the same methods but call it on the Nifty Element class.

**Comment by lyrgard** [comment]
Thanks for the answer, void256.

However, I don't think it solves my problem. I don't want my control to ignore Mouse or Keyboard events (I have chat control, and I want the rigth and left key to move the text cursor when this control has focus, for instance). In fact, what I want is that any nifty control that has focus loose it when I click somewhere outside any nifty control. 

I finally solved it, by listening for mouse click in jme, and calling `nifty.getCurrentScreen().getFocusHandler().resetFocusElements();` when a click go through to remove focus from all nifty control.

Then all keyboard and mouse event are transfered to jme.

My 3D world now works as if it was `visibleToMouse="true"` and `focusable="true"` (only it is only focusable by mouse click, but it is the intended behavior for me)

Anyway, once more, thanks a lot for your answer. Nifty it really really cool !
