### ISSUE TITLE
Single EventSubscriber method for multiple ID's?

### ISSUE THREAD

**Issue by arakash92** [nifty-gui/nifty-gui#346]
When you create an element, programmatically, how do you respond to events (like DropDownSelectionChangedEvent)?

I know I can simply add a @NiftyEventSubscriber(id="theId")

But then I can't differentiate the element from the others because they all need to be different.

Also, the number of elements that I create is variable/dynamic. So, I can't really add several event subscriber methods.

I must be missing something, but what?

**Comment by spaceemotion** [comment]
you can use the wildcard IDs and check them against your IDs whenever you retreive the event instance (when the method is called).

**Comment by arakash92** [comment]
Wildcard IDs?

**Comment by spaceemotion** [comment]
You can use a star inside an ID, like this: "button-*" to match all IDs that start with "button-"

**Comment by arakash92** [comment]
Ok, can I do "button-*-something" as well?

**Comment by arakash92** [comment]
Ok, so I'm trying to get this working:

I have a dropdown control with an id of "hello_world" and the following method in my ScreenController:

``` java
@NiftyEventSubscriber(id="hello_*")
public void hello(String id, NiftyEvent event) {

}
```

But the method isn't being called.

**Comment by void256** [comment]
https://github.com/void256/nifty-gui/blob/e98a90c493811cc8d0eb9042f0a42b4610678131/nifty-core/src/main/java/de/lessvoid/nifty/NiftyEventSubscriber.java

try: `@NiftyEventSubscriber(pattern="hello_.*")`

and remember it's a regexp ..

**Comment by arakash92** [comment]
Ah, sweet!

**Comment by spaceemotion** [comment]
Oh, yeah there was a different field for that…
Seems like it's fixed, so this can be closed, right?

**Comment by arakash92** [comment]
Yes, thanks for helping :)
