### ISSUE TITLE
Disable "tab key" behavior?

### ISSUE THREAD

**Issue by arakash92** [nifty-gui/nifty-gui#348]
Nifty uses the tab key to traverse through elements and set their focus. Any way to disable this? I need to use the tab key for my game itself.

**Comment by bgroenks96** [comment]
Hmm. From a quick look at the source, it looks like this behavior is fairly burned into the behavior of the Nifty controls.

You may want to try extending whichever input system you are using (LwjglInputSystem if it's LWJGL) and maybe redirecting 'TAB' input events. That's the only solution I can think of off the top of my head. Let me know if that works for you.

**Comment by bgroenks96** [comment]
You also might be able to override the controls themselves individually... but that might get tedious. What do you think @void256 ?

**Comment by void256** [comment]
Yes, @bgroenks96 is right. You could override it for each control but there is currently no easy way to disable that behaviour completely.

The `de.lessvoid.nifty.input.mapping.DefaultInputMapping` is used by default and is responsible for that. If you don't provide your own InputMapping then the DefaultInputMapping is used.

However, there is one line responsible for that. It is this: https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/loaderv2/types/ElementType.java#L243

If we would find a way to allow a user to configure the default input mapping class to use (his own implementation of https://github.com/void256/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/input/NiftyInputMapping.java) at this line then we could solve that pretty easily :smile:

Anyone care to do that? The brute force way would be to provide a classname as a system property. A more better approach would be some setter on the main Nifty class to set the default input mapping class prior to loading a XML or building a GUI.

**Comment by bgroenks96** [comment]
I'm trying to see if it could be done on a per Screen or per ScreenController basis... since that kind of makes sense (to me at least). The problem is that ElementType doesn't have a Nifty instance available to it.
