### ISSUE TITLE
Definition and handling of Node Adapters

### ISSUE THREAD

**Issue by mkaring** [nifty-gui/nifty-gui#358]
I wrote some initial examples how those adapters/views of nodes could look like. While they are very similar they do not share a interface yet.

We need to define how the adapter is handled inside the tree and how the user is able to retrieve it.

The user will be looking for the definition of the adapter if searching in the tree so there should be a way to expose this one. For the storage of the adapter two ways come to mind: Either the tree itself stores the adapter or the NiftyNode is able to create it's adapter on demand (and expose the class of it's adapter for more efficient searching).

We just need to define it clearly.

Also we need a definitive name for those "Adapters"

**Comment by void256** [comment]
Yes, I'm on it. Just some more hours of patience please. After moving things around the whole morning I think I've figured a solution out that makes me happy. Not sure if you totally like it tho :wink:

I just need a little more time.

**Comment by mkaring** [comment]
No worries. If I do not like it you are the first to know. :D

**Comment by mkaring** [comment]
This issue can be considered to be resolved I think. @void256?
