### ISSUE TITLE
Event subscription never removed for screenControllers

### ISSUE THREAD

**Issue by BorealFeast** [nifty-gui/nifty-gui#363]
Hi!
I'm currently migrating from 1.3.2 to 1.4.1 and i found an issue with the NiftyEventSubscriber annotation. To be short, I have two screenControllers subscribing with the NiftyEventSubscriber annotation with the same pattern. This worked well in 1.3.2 since only the current screen received the event. Now in 1.4.1, the event is thrown in both of my screenControllers. What If found is the went I move from Screen1 to AnotherScreen2, the Screen1 controller is never unsubscribed from the eventBus, which seems to be related to the next piece of code in the ThreadSafeEventService.class of EventBus. With the latest commit related to issue #55, the Subscriber private class no longer implements ProxySubscriber. The next piece of code then always returns null. 

```
private ProxySubscriber getProxySubscriber(List subscribers, Object subscribedByProxy) {
      for (Iterator iter = subscribers.iterator(); iter.hasNext();) {
         Object subscriber = iter.next();
         if (subscriber instanceof WeakReference) {
            WeakReference wr = (WeakReference) subscriber;
            subscriber = wr.get();
         }
         if (subscriber instanceof ProxySubscriber) {
            ProxySubscriber proxy = (ProxySubscriber) subscriber;
            subscriber = proxy.getProxiedSubscriber();
            if (subscriber == subscribedByProxy) {
               return proxy;
            }
         }
      }
      return null;
   }
```

And at the line 84 of NiftyEventAnnotationProcessor, this will always return false:  

```
77  private static void patternProcess(final Object obj, final Method method, final boolean add, @Nonnull final String topicPattern, final Class<?> eventClass, @Nonnull final EventService eventService) {
78    Pattern pattern = Pattern.compile(topicPattern);
79    if (add) {
80      Subscriber subscriber = new Subscriber(obj, method, eventClass);
81      eventService.subscribeStrongly(pattern, subscriber);
82      log.fine("-> subscribe [" + pattern + "] -> [" + subscriber + "]");
83    } else {
84      eventService.unsubscribe(pattern, obj);
85      log.fine("<- unsubscribe [" + pattern + "] -> [" + obj + "]");
86    }
87  }
```

**Comment by cuchaz** [comment]
I just ran into this problem too. Glad to see there's already an issue for it. Looks like one simple change fixes it. Try this:

```
private static void patternProcess(final Object obj, final Method method, final boolean add, @Nonnull final String topicPattern, final Class<?> eventClass, @Nonnull final EventService eventService) {
  Pattern pattern = Pattern.compile(topicPattern);
  Subscriber subscriber = new Subscriber(obj, method, eventClass);
  if (add) {
    eventService.subscribeStrongly(pattern, subscriber);
    log.fine("-> subscribe [" + pattern + "] -> [" + subscriber + "]");
  } else {
    eventService.unsubscribe(pattern, subscriber);
    log.fine("<- unsubscribe [" + pattern + "] -> [" + obj + "]");
  }
}
```

Oh, the same change is needed for idProcess() too.

**Comment by void256** [comment]
I think commit c6e0b12 should fix this issue.

Thanks for your suggestion @cuchaz and the pull request @Teencrusher as well as @bgroenks96 for checking and merging!

I'll close this issue now. If you think this is wrong, then please feel free to re-open and yell at me :smile:
