### ISSUE TITLE
Screen goes white when using Nifty 1.4.1 (LWJGL renderer)

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#380]
I am currently trying to get Nifty work with a LWJGL application.
The current rendering is set to a 3D mode, and as one might have guessed, nifty has to be on top of that.

But even if there is no 3D models being drawn, I still get a blank (in this case white) screen – And yes, the clear color is indeed BLACK. From further googling and searching it seems like its an OpenGL issue, but the console isn't returning anything.

This is how the application is currently rendered without any 3D stuff (please don't blame me, its not mine - except the prepare nifty part as I am currently trying to add it to an existing system):

``` java
glPushMatrix();
glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
// (Some weird frame buffer switching + viewport setting)
glEnable(GL_TEXTURE_2D);

glViewport(0, 0, displayWidth, displayHeight);
glMatrixMode(GL_PROJECTION);
glLoadIdentity();
glMatrixMode(GL_MODELVIEW);
glLoadIdentity();
glClear(GL_DEPTH_BUFFER_BIT);
glMatrixMode(GL_PROJECTION);
glLoadIdentity();
glOrtho(0.0D, width, height, 0.0D, 1000.0D, 3000.0D);
glMatrixMode(GL_MODELVIEW);
glLoadIdentity();
glTranslate(0.0F, 0.0F, -2000.0F);

// Preparing Nifty code
glDisable(GL_DEPTH_TEST);
glDisable(GL_LIGHTING);
glEnable(GL_TEXTURE_2D);
nifty.update();
nifty.render(clearScreen);

glPopMatrix();
glPushMatrix();
// (again, rendering the framebuffer)
glPopMatrix();

Display.update()
```

For anybody that is interested in the details, here is a full OpenGL profiler callstack dump (or however one calls that): http://pastebin.com/g2zusLk9

**Comment by bgroenks96** [comment]
Try putting the `nifty.update()` and `nifty.render(clearScreen)` AFTER `glPopMatrix()` but BEFORE `glPushMatrix()`.

**Comment by spaceemotion** [comment]
Okay, so I finally got an initial state to work - The debug FPS counters are being drawn, but now its background is a plain white, although I do not have any nifty screens open.

I also had to add the following OpenGL calls before the nifty.update method:

``` java
GL11.glDisable(GL11.GL_DEPTH_TEST);
GL11.glDisable(GL11.GL_CULL_FACE);
GL11.glEnable(GL11.GL_BLEND);
GL14.glBlendFuncSeparate(GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA, GL11.GL_ONE, GL11.GL_ZERO);
GL11.glEnable(GL11.GL_ALPHA);
```

**_Edit:**_ Okay, fixed it by re-enabling Texture2D and blend mode, as Nifty disabled them after being called.

**Comment by bgroenks96** [comment]
Erm... where did Nifty disable GL_TEXTURE_2D? I'm not sure that should really happen... at least not by default.

**Comment by spaceemotion** [comment]
I am using the batched render device, as stated by the deprecation comment on the LWJGL renderer. The `BatchRenderBackendInternal#endRendering` method has the following content:

``` java
gl.glDisableClientState(gl.GL_TEXTURE_COORD_ARRAY());
gl.glDisableClientState(gl.GL_COLOR_ARRAY());
gl.glDisableClientState(gl.GL_VERTEX_ARRAY());
gl.glDisable(gl.GL_BLEND());
gl.glDisable(gl.GL_TEXTURE_2D());
```
