### ISSUE TITLE
[2.0] Use slf4j for logging

### ISSUE THREAD

**Issue by void256** [nifty-gui/nifty-gui#394]
We've decided to use slf4j because it's more simple to log with it and it eventually makes using it on Android easier. The 33kb memory overhead and the new dependency is acceptable

**Comment by bgroenks96** [comment]
@void256 take a look at 8bcd123 to verify changes. Everything compiles, but I haven't tested the example logging yet.

**Comment by void256** [comment]
Looks great! Just polished it a bit with 98a0c2f
Thanks!
