### ISSUE TITLE
NiftyGUI 1.41, only draws a black rectangle

### ISSUE THREAD

**Issue by dustContributor** [nifty-gui/nifty-gui#395]
Hi! Honestly I don't know where else to ask this, this is my issue:

I'm using the OpenGL core renderer batch backend for NiftyGUI, trying to show a panel with two buttons, my rendering works fine but from Nifty I only get a black rectangle where the panel 
is supposed to be.

This is the XML schema:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<nifty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://nifty-gui.lessvoid.com/nifty-gui" xsi:schemaLocation="https://raw.githubusercontent.com/void256/nifty-gui/1.4/nifty-core/src/main/resources/nifty.xsd https://raw.githubusercontent.com/void256/nifty-gui/1.4/nifty-core/src/main/resources/nifty.xsd">
    <useControls filename="nifty-default-controls.xml"/>
    <useStyles filename="nifty-default-styles.xml"/>
    <screen id="start">
        <layer id="layer0" childLayout="absolute">
            <panel id="panel0" childLayout="absolute" width="370px" x="285px" y="139px" style="nifty-panel-simple" height="180px">
                <control name="button" id="btnOk" childLayout="center" x="72" width="100px" y="76" label="Ok" height="35px"/>
                <control name="button" id="btnCancel" childLayout="center" x="196" y="82" label="Cancel" height="35.0px"/>
            </panel>
        </layer>
    </screen>
</nifty>
```

Loading it like:

``` java
// The xml is in the folder /res/nifty/test.xml
this.nifty.fromXml( "res/nifty/test.xml", "start" );
```

Just in case I do the following state tracking when drawing:

``` java
this.nifty.update();

boolean blending = GL11.glIsEnabled( GL11.GL_BLEND );
int blendSrcFactor = GL11.glGetInteger( GL11.GL_BLEND_SRC );
int blendDestFactor = GL11.glGetInteger( GL11.GL_BLEND_DST );
boolean depthTest = GL11.glIsEnabled( GL11.GL_DEPTH_TEST );
boolean culling = GL11.glIsEnabled( GL11.GL_CULL_FACE );

GL11.glBlendFunc( GL11.GL_SRC_ALPHA, GL11.GL_ONE_MINUS_SRC_ALPHA );

GL11.glEnable( GL11.GL_BLEND );

GL11.glDisable( GL11.GL_DEPTH_TEST );
GL11.glDisable( GL11.GL_CULL_FACE );

this.nifty.render( false );

if ( !blending ) {
    GL11.glDisable( GL11.GL_BLEND );
}

GL11.glBlendFunc( blendSrcFactor, blendDestFactor );

if ( depthTest ) {
    GL11.glEnable( GL11.GL_DEPTH_TEST );
}

if ( culling ) {
    GL11.glEnable( GL11.GL_CULL_FACE );
}
```

But having it there or not makes no difference sadly :disappointed: Honestly this needs some documentation, exactly what state Nifty touches, in what state it needs OpenGL to be, etc.

I need it to draw on top of my back buffer, after I've done all the rendering, right before calling swapBuffers.

Any ideas?

**Comment by void256** [comment]
From a quick look I think enabling GL_TEXTURE_2D might be missing?
But I agree this really needs more documentation in the wiki. Actually I thought I already did but couldn't find it. However, since we've been there before, I've found a similar issue and a comment of mine: https://github.com/nifty-gui/nifty-gui/issues/216#issuecomment-33885117  Maybe you can check the states there as well?

**Comment by bgroenks96** [comment]
Like @void256 said, check GL_TEXTURE_2D and make sure it's enabled before calling `nifty.render()` and make sure you also aren't accidentally enabling GL_STENCIL_TEST or something.

If that doesn't work, please post your code for initializing both your Nifty instance (with the batch renderer) and any relevant OpenGL initialization calls.

**Comment by dustContributor** [comment]
As I mentioned, I'm using a core profile (OpenGL 3.3 core profile precisely). glEnable(GL_TEXTURE_2D) is deprecated in core. Neither I can use the matrix functions nor GL_ALPHA_TEST. Disabling GL_STENCIL_TEST makes no difference.

Ahh found it while I was writting this. I use sampler objects, and set them to default texture units (units 0 to 15 get one sampler, 16 to 31 get another).

The default sampler had mipmap linear filtering, whereas it seems Nifty expects nearest or linear filtering. Nifty sets the filtering options directly in the texture, but when used through a texture unit that has a sampler object bound to it, the sampler overrides the texture settings.

I think that in the 'saveCore' method that saves the OpenGL state, it also should store the sampler bound to whatever texture units nifty uses (only one I think).

So after saving the active texture state, [after this line](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/core/CoreProfileSaveGLState.java#L46) 

``` java
// Activate the tex unit Nifty uses.
gl.glActiveTexture(gl.GL_TEXTURE0());
// Store current sampler bound.
this.texUnit0SamplerBinding = gl.getIntegerv(gl.GL_SAMPLER_BINDING(), params);
// Now to unbind the sampler from tex unit 0.
gl.glBindSampler(0, 0);
```

Then restore it before [this line](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/core/CoreProfileSaveGLState.java#L69)

``` java
// Activate the tex unit Nifty uses.
gl.glActiveTexture(gl.GL_TEXTURE0());
// Rebind the sampler to tex unit 0.
gl.glBindSampler(0, this.texUnit0SamplerBinding);
```

Then again, it wouldn't be necessary for Nifty itself to track anything if there was a detailed list of the state needed by Nifty before rendering, what state it touches in the middle, and what state it leaves OpenGL in. I could do it myself with my already existing state tracking classes (and save up some state reading/swapping in the process).

Hmm maybe I can jury rig it by overriding beginFrame/endFrame on the batch renderer now that I think of it, I have the good luck that you don't have the 'final class' obsession I have :smile:

**Comment by void256** [comment]
Sorry, completely overlooked that you mentioned OpenGL Core here >_<

Yes, we should also save/restore the sampler state exactly like you've mentioned! And you're right, Nifty does not use Sampler Objects yet. Have you already verified if this fixes the panel rendering for you?

I can add the save/restore for the sampler binding tonight. But why don't you send a pull request? :smile:

PS: The class you've found that does all the state saving for the core renderer [CoreProfileSaveGLState](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/render/batch/core/CoreProfileSaveGLState.java) is meant to save ALL the GL state that Nifty might modify. So when it does its job properly you shouldn't need a documentation of all the GL state Nifty modifies, right?

You can set and use GL in any way you like and Nifty makes sure it will leave the states (only the ones it modified!) the way they were before its rendering.

Since you call nifty.render() usually just once per frame I think that the eventually redundancy introduced by that state saving is negligible or am I missing something?

I would favour a solution with as little intervention by Nifty users as possible since usually no one reads documentation anyway :wink:

**Comment by bgroenks96** [comment]
It should be Nifty's job to clean up its own state changes. This is a bug; the onus doesn't fall on the user.

I can take care of this @void256. Not even sure why you're awake at the moment... unless you just woke up? ;)

**Comment by dustContributor** [comment]
> Have you already verified if this fixes the panel rendering for you?

Yup. Unbinding the sampler before rendering Nifty fixes it.

> Since you call nifty.render() usually just once per frame I think that the eventually redundancy introduced by that state saving is negligible or am I missing something?

Yes. Google around for "glGet performance". glGet calls can produce driver sync points with the application, which means that it will stall the driver until it can answer the call. Thats not good, and its the sole reason of doing so called "state shadowing" from the application (ie, simply store the state changed instead of asking the driver for it).

The OpenGL driver, at least for nVidia, is implemented with two threads, one shim thread that interacts with your application and returns as fast as it can, and a thread that does the workload. Sync points stall both threads. So no GPU commands get sent until the call is done. This is no bueno.

In any case I think I can do it anyway, by overriding a couple of methods, wont be pretty but as long as I'm able to there is no problem if the default behavior is to store/restore state.

> I can add the save/restore for the sampler binding tonight. But why don't you send a pull request? 

Gotta go sleep, I make no promises :smile:

**Comment by bgroenks96** [comment]
@dustContributor Good night. I got it for you! :smile:
