### ISSUE TITLE
DSLification

### ISSUE THREAD

**Issue by toolforger** [nifty-gui/nifty-gui#41]
I'm currently preparing a pull request that has modified `*Builder` classes that allow stuff like
    `new ButtonBuilder().widthPx(102).text("Cancel").build(nifty, screenId, parent)`
Existing classes still have an identical API, with the following exceptions:
- All builders have a parameterless constructor now, so people can do `new ButtonBuilder().id("someId")`. This allows using builder-creating functions to generate a control template that can have its id filled in by the caller, i.e. it decouples builder construction from id assignment. (It also plays better with frameworks that use reflection, though I don't have a use case for that.)
- The `build()` functions return the control created. I.e. `ButtonBuilder#build()` returns a `Button`, etc. The obvious exceptions being `LayerBuilder`, `PanelBuilder` etc, which return just the `Element`.
- Possibly remaining silly mistakes.

I'd be happy to hear what you think about that.

I also have some further plans and would appreciate feedback:
1) I'd like to make a `build(parent)` function that picks up the Nifty and the screenId from parent. For that purpose, would it be okay to add a `getScreen()` to Element, and a `getNifty()` to screen?
2) I'd like to make `onShow()`, `onClick()`, ..., etc. functions in `ElementBuilder` and subclasses. The parameter should be something executable (i.e. a Runnable or an EventTopicSubscriber). This would allow writing DSL code like this (not tested):

``` java
Panel parent = ... .build();
TextField characterName = new TextFieldBuilder(). ... .build(parent);
Button button =
  new ButtonBuilder().widthPx(150).text("OK").onClick(
    new Runnable(){public void run() {
      gameCharacter.setName(characterName.getRealText());
    }}
  ).build(parent);
```

What's the best API that the onXxx routines should use? Set up an `EventTopicSubscriber` (that would have to be postponed until build() time I guess), or is that already available somewhere? I have seen the `interactOnXxx` functions, but Strings can contain typos and aren't properly updated during refactoring, so I don't want to use these.

**Comment by void256** [comment]
Thanks for your effort. This looks pretty good.

Just make sure to make these changes in the 1.4 branch. Even though they seem to be pretty compatible it's probably too late for 1.3.2.

1) Adding getScreen() and getNifty() sounds ok to me.

2) I don't think that's going to work without changing a lot. The interact onClick() and so on methods are all meant to be called on a controller or ScreenController. So maybe that's more like something for 2.0? ;)

**Comment by toolforger** [comment]
Is 1.4 ready for production until end of year?
I'd be unable to use 1.4 otherwise, and that DSLification stuff is just a by-product.

On events: I already had something working, it was just built on top of Creator classes and suffered from being overly complicated to code and maintain. I think that approach should be transferrable to Builder classes, I just was checking whether I'm overlooking some obvious way that would have been even simpler.

**Comment by void256** [comment]
The current 1.4 branch is still very close to 1.3.x. But yes, there might be API changes while it is in development, that's true. There is no fixed timeline for a 1.4 release yet...

On the other hand 1.3.2 is going to be released any day now. I think there are only two or so bug reports left in the sf.net tracker that I'd like to add before a release (which is quite overdue already really). So I don't want to introduce any new code there anymore.

**Comment by toolforger** [comment]
Just don't forget to pull the request I sent ;-)

On 1.4: I just checked the diffs between 1.3 and 1.4 and it seems there aren't any difference that would affect my current code.
I'll give it a try and let you know what happened.

**Comment by toolforger** [comment]
Interleaving Builder construction and Control creation as in the code example above doesn't work, it hits an NPE in `screen.getRootElement().getElementType()` in line 2 of `Nifty#createElementFromTypeInternal(Screen, Element, ElementType, LayoutPart)`.

This affects just code that interleaves Builder construction and control creation, like the example Button creation above.

However, the whole effort has started to become too much work for an application programming project anyway, and this isn't going to help me build an ID-less control construction process, so I'm just giving up.
If you wish, I can send a pull request so you can study what I did and decide what you wish to salvage.

**Comment by toolforger** [comment]
No interest it seems... dropping that work then.

**Comment by relu91** [comment]
I find this feature really cool , also it could be more userfriendly for the new users and it will effect also issue #129 . We could implement only the DSLification part without refectot onXxx method and still I think it worth. What about to reopen ?

**Comment by toolforger** [comment]
Feel free to salvage what you can. I have dropped using Nifty in general, and I'd recommend looking for alternatives (truth be said, the alternatives have problems of their own).
