### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by marko-lazic** [nifty-gui/nifty-gui#410]
We need clear road map and what has been done. i suggest taking the structure from lwjgl 3 guys. They have great structuring for this kind.

**Comment by bgroenks96** [comment]
You can see the following issues for discussion on where 2.0 is going:
#349
#350 
#334
#398

You can also see the [current development branch](https://github.com/nifty-gui/nifty-gui/tree/2.0) for example code and early API documentation. Just be advised that nothing is currently stable or guaranteed to stick around.

Other than that, there's not much else we can tell you right now. Nifty 2.0 is still somewhat early in development. It's a complete rebuild from the ground up. You can keep checking to see where things are going in the meantime.

**Comment by void256** [comment]
I've created a roadmap in the wiki [Nifty 2.x Roadmap](https://github.com/nifty-gui/nifty-gui/wiki/Nifty-2.x-Roadmap).

However, this is still work in progress and in no way complete. But eventually it's a start and might make it more transparent what we're working on.

**Comment by relu91** [comment]
Thank you void! ^^ the page looks perfect and really useful !!!!

**Comment by spaceemotion** [comment]
Looks solid, especially the world domination part :+1:
