### ISSUE TITLE
Nifty BundleInfoResourceBundle doesn't support default bundles

### ISSUE THREAD

**Issue by tonihele** [nifty-gui/nifty-gui#414]
Hi,

I'm migrating our JME project from Nifty 1.3.2 to 1.4.1. The resource bundles broke and I just happen to know why, Nifty BundleInfoResourceBundle doesn't support default bundles. This was introduced in #303. The problem is that we load resource bundles that belong to ROOT locale and Nifty tries to find one from the hash that uses default locale. It is in conflict how JAVA treats these.

If we have the following resource bundles:
LabelsBundle.properties
LabelsBundle_de.properties
LabelsBundle_fr.properties

My default locale is English. And I try to get bundle by Locale.getDefault(), I get LabelsBundle.properties. But when this bundle is asked to which locale it belongs to, it says Locale.ROOT instead of returning the default.

**Comment by tonihele** [comment]
I don't know if there is a cleaner solution to this, but one would be (de.lessvoid.xml.tools.BundleInfoResourceBundle.java):
Instead of:
resourceBundles.put(resourceBundle.getLocale(), resourceBundle);

Do:
resourceBundles.put((Locale.ROOT.equals(resourceBundle.getLocale())  ? Locale.getDefault() : resourceBundle.getLocale()), resourceBundle);

**Comment by tonihele** [comment]
Or better yet, handle "exactly" like JAVA. Only put the bundle to "defaultResourceBundle" when it is the ROOT locale. Then when getting the bundle, if locale is null or can't find one, then give out the defaultResourceBundle. Which in turn is the ROOT one.

**Comment by bgroenks96** [comment]
@void256 You submitted the fix for #303. Can you take a look at this?

**Comment by void256** [comment]
Does 0574a270214693976d478b48525aac22c2bc986e help?

You just need to make sure that the very first ResourceBundle you add to Nifty is the default ResourceBundle you want to use as the fallback but that was already the case before this latest commit.

**Comment by tonihele** [comment]
Yes, I believe that would work for us. Thank you!

**Comment by bgroenks96** [comment]
Closing since 0574a27 appears to have addressed this issue. Re-open again if necessary.
