### ISSUE TITLE
working from source

### ISSUE THREAD

**Issue by teamblubee** [nifty-gui/nifty-gui#415]
I might be a bit dense here but how exactly do I work with nifty-gui from source?
1) cloned the git repo
2) cd to cloned directory mvn clean package

A bunch of things downloaded, now how do I actually run nifty-gui to edit layouts?

**Comment by bgroenks96** [comment]
I'm not sure what you mean by "run nifty-gui to edit layouts."

Nifty is a library. It provides the software API for you to create a GUI via Java/XML in much the same way you would with Swing, SWT, JavaFX, etc. It's not in itself a GUI front-end for actually creating those UI layouts.

It does so happen that @relu91 was kind enough to create such a tool, however :smile: 

You can head over to the [NiftyEditor](https://github.com/relu91/niftyeditor) repository to find out more about getting started with that.

**Comment by teamblubee** [comment]
oh, it is the link you provided, [to this](https://www.youtube.com/watch?v=4iTVPYMEtH0) 
so I can just use this library to create my layouts in java, xml or use the editor you linked to do it visually. Then load those files in my application, correct?

**Comment by bgroenks96** [comment]
That is correct!

**Comment by teamblubee** [comment]
okay, thank you.
