### ISSUE TITLE
Events being sent twice

### ISSUE THREAD

**Issue by drawig** [nifty-gui/nifty-gui#42]
I have a custom control which publishes an event when clicked on.  The same event is being caught in a different control.
The event publishing and catching works fine. When I put my control inside a window it initially works fine as well.
However, once I drag the window and after that I click on my custom control again, the same event is suddenly being caught twice. The control catching the event is inside the window as well.

If the problem cannot be reproduced, I can provide the full code.

**Comment by void256** [comment]
Which version of Nifty do you use?

This looks like something we've fixed some time ago. See this commit for details https://github.com/void256/nifty-gui/commit/71239e7e65720272d98d256257c2c08a381cb618

Can you try with a 1.3.2-SNAPSHOT?

**Comment by void256** [comment]
I think this issue timed out now! :)

Please reopen / create a new issue if the problem surfaces again.
