### ISSUE TITLE
Using height(SizeValue.max(x)) on TextField+Label (+other elements) causes NumberFormatException

### ISSUE THREAD

**Issue by dominic-jones** [nifty-gui/nifty-gui#424]
Minimal example is as follows, will post SSCCE

```
    layer(new LayerBuilder("TestLayer") {{
      panel(new PanelBuilder("TestPanel") {{
        control(new LabelBuilder("TestLabel", "TestText") {{
          height(SizeValue.max(50));
        }});
      }});
    }});
```

This will produce a stack trace similar to

```
Caused by: java.lang.NumberFormatException: For input string: "m[50.0px]"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
    at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
    at java.lang.Float.parseFloat(Float.java:451)
    at java.lang.Float.valueOf(Float.java:416)
    at de.lessvoid.nifty.tools.SizeValue.<init>(SizeValue.java:181)
    ... 35 more
```

Stepping into the code shows that ElementBuilder#208 calls SizeValue.toString, which provides the computed value string "m[50.0px]". Element#311 uses this string in SizeValue's constructor, which does not attempt to parse that format and eventually treats it as a raw integer at the location of the above exception.

**Comment by dominic-jones** [comment]
SSCCE here https://github.com/dominic-jones/nifty-gui-issues/tree/master/src/main/java/de/lessvoid/issues/issue424

**Comment by bgroenks96** [comment]
Verified. Thanks for the SSCE. Looking into it now.

**Comment by bgroenks96** [comment]
Found the issue. `ElementBuilder` is violating the `SizeValue` spec by passing in the value returned by `toString` to the ctor. The `toString` javadoc event explicitly says the value is NOT parseable. Easy fix is to add a method that returns a valid SizeValue format string and use that instead. Will submit a fix shortly.

**Comment by bgroenks96** [comment]
It's worse than I thought.... `SizeValue.toString()` is being used in quite a few places as an attribute value, which means it will end up being processed by the `SizeValue` constructor. Best course of action then seems to be to force `toString` to comply with the `SizeValue` constructor formatting spec and then add an auxillary string representation method for debugging. I don't see a better way really. Not sure why the `SizeValue.toString()` documentation has been ignored in so many places... @void256 >_<

**Comment by bgroenks96** [comment]
I ended up going for my original plan and just replacing all of the illegal uses of `toString` with `getValueAsString`.

@dominic-jones Please verify that 376b4a1 fixes the issue before I push the changes upstream.

**Comment by void256** [comment]
@bgroenks96 I don't know for sure but it looks like that someone "cleaned up" the SizeValue class and modified the toString() method to log the calculated value - which makes probably a lot of sense for logging SizeValues. Unfortunately the existing calls to toString() for methods that require a parsable SizeValue String have not been adapted. But your solution looks reasonable since I don't see another way to get a parsable String out of SizeValue. Thanks!

For 2.0 we need more unit tests to prevent or at least reduce the chances of something like that happening again :disappointed: I'll look into Jenkins (and maybe talk to @mkaring) if we're able to let builds fail if the test coverage is getting lower on new builds, kinda forcing us to write more tests :yum: I think we used something like that at work for some time.

**Comment by bgroenks96** [comment]
GitHub Blame puts it on @mkaring :stuck_out_tongue_winking_eye:

**Comment by dominic-jones** [comment]
I'd have looked into a fix myself as well, but the uses of SizeValue and the documentation (as you pointed out) did not add up, so was interested in your view.

I think @void256 has the heart of it - it smells of a naive refactor. @bgroenks96's fix seems like the right one to me - I've never been comfortable personally with using toString for much more than logging.

All I can do is run my last test and see that the code no longer fails like above. I am uncertain if SizeValue.max() is behaving as intended though - I was only exploratorily using the api to examine its effects in the first place! :)

**Comment by void256** [comment]
no, not naive .. just something that was easily overlooked. using toString() in that way probably shouldn't have been there from the beginning. And additionally the SizeValue evolved quite a bit over the years as well.

I guess the lesson is that one shouldn't use toString() for other things then debug output of object state.

**Comment by void256** [comment]
yep - https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#toString()

```
Returns a string representation of the object. In general, the toString method
returns a string that "textually represents" this object. The result should be a
concise but informative representation that is easy for a person to read. It is
recommended that all subclasses override this method.
```

It says 'to be easy for a person to read' and not 'valid to be parsed as a SizeValue' :wink:

blame me :yum:

**Comment by dominic-jones** [comment]
That's what I meant - couldn't find another single word that fit situation better.

And yes, agree with that use of toString :) Didn't expect core Java to make that claim though. It doesn't help that other parts of the api use toString directly - e.g. StringBuilder. But then again... when your contract uses terms like "in general"...

**Comment by bgroenks96** [comment]
So is the fix verified @dominic-jones ?

**Comment by dominic-jones** [comment]
It doesn't fall over when using the computed values.

I do not know what the expected behaviour is though, so I cannot tell if it is 'working as intended'. (As I said, I was simply exploring at the time).

**Comment by bgroenks96** [comment]
Thanks!
