### ISSUE TITLE
Nifty with a java applet?

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#431]
Is there any possibility to use Nifty-Gui with a java applet, tried to google alot about this subject, couldn't find any usefull information about this..

My Gui class:
http://pastebin.com/ncWpkiA5

Sorry, if it isn't really an "issue". (I just want to know if there is a way to do this or give up on this.)

**Comment by bgroenks96** [comment]
Your best bet would be to use the JogAmp backend and use JOGL's GLCanvas to render in the AWT context. You can find instructions on how to use JOGL with applets [here](https://jogamp.org/wiki/index.php/Using_JOGL_in_a_Java_applet)

**Comment by ghost** [comment]
Alright thanks :-)

**Comment by bgroenks96** [comment]
Feel free to re-open this issue if you encounter any more issues.
