### ISSUE TITLE
Lock screen mute / upgrade does not work

### ISSUE THREAD

**Issue by hakankocyigit** [nifty-gui/nifty-gui#433]
Lock screen mute / upgrade keys do not work when I press 
Build #576

**Comment by bgroenks96** [comment]
You need to be more specific. Which renderer are you using? What do you mean when you say they "don't work"? Your application isn't receiving input signals from them? Or your phone isn't locking/changing volume?

The latter quite obviously has nothing to do with nifty-gui.

**Comment by hakankocyigit** [comment]
I could tell my English is not so good. But the second one I tried the phone lock screen mute / upgrade does not work when I press. (Only the lock screen)
Tested: Xperia Z3C, Xperia Z2

**Comment by hakankocyigit** [comment]
Build #585 fixed the problem
