### ISSUE TITLE
ScrollPanel does not draw image / background colour

### ISSUE THREAD

**Issue by raLaaaa** [nifty-gui/nifty-gui#435]
Hey guys,

I'm not sure whether this is intended. But I'm currently using a ScrollPanel to draw Items in my inventory. From my investigation I think that this should be possible but it's not working for me. I'm trying to add an image next to a text inside a ScrollPanel. The ScrollPanel is shown inside of a popup.

This is my XML:
http://pastebin.com/FWzGZrMA

Inside the myScrollStuff I want to add the images via java code:
http://pastebin.com/ya8pUJKj

For clarification, next to the tomatoe should be rendered an image:

![issue](https://cloud.githubusercontent.com/assets/12799722/21741470/bccf466c-d4d6-11e6-8937-f15165956348.jpg)

I tried to add a panel with background color as well to the myScrollStuffPanel inside of the ScrollPanel control but it doesn't get rendered as well.

Is this intended or is it a flaw in the code? Or am I doing something wrong?
(I used pastebin because github messed up my code somehow)

**Comment by bgroenks96** [comment]
Hi,
Sorry for the delay in getting back to you. Could you put together an SSCE for this issue and submit a pull request to [our issue repo](https://github.com/nifty-gui/nifty-gui-issues)? That would help a lot!

I don't think this is intended behavior. It looks like the scroll panel is being rendered over top of the image. Which renderer and backend are you using?

**Comment by raLaaaa** [comment]
Hey. no worries! Thanks for the reply.

Unfortunately I'm not familiar with an SSCE.
Did I get it right that it's basically a demo of my code which can reproduce the issue? I think I can do that. I already have a simple version to reproduce the issue, but it's a mavenproject with dependencies to slick2d, nifty, as well as lwjglnatives. So I'm not quite sure how to put it in that repo that you can run simply run it by commandline.

Yep, that was my guess as well. For instance, if i draw a huge panel with bgcolor instead of an image this color is not rendered as well, but the panel is definitly loaded and "drawn" by nifty since the label next to the panel is not shown anymore because the panel is so huge.

I'm using the slick2d extension with NiftyStateBasedGame etc. running on Windows 8 with Java 8.
So the renderer should be nifty-slick-renderer on version 1.4

**Comment by bgroenks96** [comment]
Yes, it stands for "Short Self-contained Correct Example" ... it saves the project maintainers a huge amount of time by giving us the ability to reproduce the issue much faster.

To submit an issue to the ssce repo, fork/clone the nifty-issues repo I linked you to above, create a new source package called 'issue435' with your nifty source code. The issues project includes maven dependencies for Nifty and all of the relevant backends (as well as native libs), so you shouldn't have to worry about that. Just include the relevant nifty source code and layout files. You can then commit/push those changes to your fork and submit a PR.

**Comment by raLaaaa** [comment]
Hey, sorry for the late reply! Last week was quite busy for me.

I just cloned the repository and encountered some problems.

The pom.xml says:

"If you use this pom.xml with eclipse m2e plugin you'll need to install the maven natives eclipse plugin from http://code.google.com/p/mavennatives/ to make the error message go away. It's as simple as installing it using the following update site: http://mavennatives.googlecode.com/svn/eclipse-update/. This plugin detects if you have the maven plugin configured, and if you do it executes the unpacking of natives, and configures the Native Library Location. This will allow  you to run the examples from within eclipse without any more setup of LWJGL required! Just execute the individual examples like any other Java application from eclipse. Done!"

Unfortunately http://mavennatives.googlecode.com/svn/eclipse-update/ which is referred to, is not available. http://code.google.com/p/mavennatives/ is still live tho. Due to the missing plugin, eclipse can't resolve all dependencies.

Another question would be whether it's better for you if I push the whole Slick2D ApplicationGameContainer for error reproducing? That would be one class, just to start the application. Or do you want me just to reproduce the issue by using the JoglNiftyRunner  (I guess that's the one I'd have to use to reproduce the issue for Slick2D, correct me if I'm wrong).

**Comment by bgroenks96** [comment]
I've pushed a commit that includes a link by the same comment to an alternative update site for the eclipse maven natives plugin.

I'd like you to try to reproduce the issue with the JOGL backend first, i.e. put all of your nifty code/resources in the issue project and run it to see what happens (no Slick2D dependent code). If the issue doesn't arise, we'll know it's a Slick2D renderer bug. Otherwise, it's a nifty core bug.

**Comment by raLaaaa** [comment]
I added the SSCE to the repo and created a pullrequest. (Hopefully I got that all right :D )
Using the JoglRunner and my XML directly without a popup it works fine.
Using the LWJGL/GL example of issue 417 and starting the popup directly after niftyInit it works as well.

I did not test calling the popup by a button because I always get an exception somehow, but I doubt that it matters if i call the popup directly by code or by button pressing.

So I guess this is related to the Slick2D extension?

PS: I used the new update site for the plugin of the xml but the error message did not get resolved somehow, that's why I added the lwjgl native manually to the build path of java. But that should be no problem for you since the plugin is working for you.

**Comment by bgroenks96** [comment]
>the error message did not get resolved somehow

I also get an error message about the plugin execution lifecycle (or something like that), but if you try running the example from Eclipse, it should work regardless.

>So I guess this is related to the Slick2D extension?

Yes, most likely. I will look into it as soon as I get a chance to confirm the issue. In the meantime, please double/triple check your Slick2D application setup/configuration to make sure nothing is missing or erroneously set (i.e. alpha blending modes, clipping, etc).

**Comment by raLaaaa** [comment]
Alright. If I can support the confirmation process or something else please let me know.

I'm running a basic Slick2D NiftyStateBasedGame. 
I didn't do changes to blending modes or clipping etc.

I'll double check the code though, maybe something else is messing things up.

**Comment by bgroenks96** [comment]
I started writing the boiler-plate code in the issues library for initializing and running Slick2D examples, but I've run into a number of issues getting it working. Unfortunately, I don't have time at the moment to keep investigating.

One thing we need to bear in mind here is that Slick2D is a very old and largely unsupported library. It's riddled with bugs and design flaws (there's a decent chance the bug we're looking at here is actually an issue with Slick). Likewise, the Nifty Slick backend will suffer from the same issues.

There are no plans to continue supporting Slick2D in future releases of Nifty, so I'm hesitant to dedicate a huge amount of effort to it here.

As for your project, if you're still early in development, I would highly suggest switching to a more full-featured and modern library like [LibGDX](http://libgdx.badlogicgames.com/). Nifty has a backend for GDX too which will continue to get support. Long-term, GDX will serve you far better than Slick. That's just the nature of working with old software.

If you are still determined to stick with Slick, I'll spend some more time on this issue when I can. But I can't guarantee a fix, especially if the problem turns out to be with Slick itself.

**Comment by raLaaaa** [comment]
I was expecting the answer to be honest and totally agree with you.
It's just because I started this project in Slick2D and wanted it to finish. 
After that I wanted to use LibGDX.

I was hoping that maybe  the issue would not be too hard to fix.
In case you are able to provide a fix that would be great, if not that's fine too.
I really appreciate the time you already invested into that and I'm sure i'll find another way to create an inventory GUI.

**Comment by bgroenks96** [comment]
Are you using the SlickBatchRenderBackend or the SlickRenderDevice for nifty's renderer?

**Comment by raLaaaa** [comment]
I'm using the LwjglRenderDevice().

I've good and bad news though.

So good news first, I was able to fix this issue, thanks to your help. I tried using te SlickBatchRenderBackend and figured out that this one is not covered by my Nifty Maven dependency. 
I checked versions and figured out that the SlickBatchRenderBackend is only covered in version 1.4.2 but not in the one I was using (1.4) 

So I switched to 1.4.2 which covers the SlickBatchRenderBackend and it worked for me.

Bad news I probably wasted your time and I'm really sorry for that, apparenty this got fixed with version 1.4.2 

Really appreciated your help!

**Comment by bgroenks96** [comment]
`LwjglRenderDevice` is meant for the LWJGL backend. For Nifty/Slick apps, you should be using `SlickBatchRenderBackend` (NOT `SlickRenderDevice`; all *RenderDevice implementations are obsolete as of 1.4.x).

I'm glad to hear that switching to the right backend fixed your issue. No issue is a waste of time; happy to be of help!
