### ISSUE TITLE
Bug in Lwjgl3RenderImage prevents use

### ISSUE THREAD

**Issue by TheDestroyer19** [nifty-gui/nifty-gui#436]
In the method `createTexture()` there is this line:
    
    GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, 4, width, height, 0, srcPixelFormat, GL11.GL_UNSIGNED_BYTE, textureBuffer);
    
The `4` is not a valid format. It should be something like `GL11.GL_RGBA` or another pixel format.  -- see [https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml)
This occurs at [line 126](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-renderer-lwjgl3/src/main/java/de/lessvoid/nifty/renderer/lwjgl3/render/Lwjgl3RenderImage.java#L126)
Also, in the `checkGLError()` function it attempts to call `GLUtil.getErrorString(error);` which is no longer present in  LWJGL 3.1.1

**Comment by bgroenks96** [comment]
Thanks for reporting. I'll take a look at this ASAP.

**Comment by bgroenks96** [comment]
@TheDestroyer19 Please verify that  fb23eda fixes the issue. See #437 for the other issue you mentioned.
