### ISSUE TITLE
Can I use gradient instead of background-image for button?

### ISSUE THREAD

**Issue by Genhis** [nifty-gui/nifty-gui#440]
Hello,

the default implementation of button style uses `background-image` attribute, but I'd like to use gradient.

I've seen `Gradient` class, but I can't find any documentation how to use it. I'm using XML for style structure.

Is it possible to use it that way?

If yes, how?
If not, would you consider implementing this in the future?

**Comment by Genhis** [comment]
I did a mistake, and that was ignoring `onActive` tag and replacing it with `onHover` or `onEnabled`.

When I use it with `onHover`, a button does not render at all; when it's used with `onEnabled`, nothing happens. Later I realized that I could try using `onActive`, and that worked.

Can I somehow use gradient with `onHover` or it's not possible?

My code:
```
<onHover name="gradient">
    <value offset="0%" color="#5000" />
    <value offset="100%" color="#A22f" />
</onHover>
```

**Comment by void256** [comment]
Hi,

I don't see a reason why it shouldn't be possible to use gradient in onHover.

**However** :wink: there are some things to consider:

- The order in which effects are rendered is fixed. You can find that hard-coded in the [EffectManager](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-core/src/main/java/de/lessvoid/nifty/effects/EffectManager.java#L24) class. So it's easily possible that some other effects might actually be rendered after your onHover effect.
- You could try to use the `post="true"` parameter as described in the wiki [here](https://github.com/nifty-gui/nifty-gui/wiki/Effects#Standard_Effect_Parameters). The standard button effect is using this for example in the [standard button style](https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-controls-style-black/src/main/resources/button/nifty-button.xml#L7
).

In case this doesn't explain it a SSCCE is always welcomed for further assistance :smile:
void

**Comment by Genhis** [comment]
I modified the default button style and I have this:
```
<?xml version="1.0" encoding="UTF-8"?>
<nifty-styles xmlns="http://nifty-gui.lessvoid.com/nifty-gui">
    <style id="button_mainmenu#panel">
        <attributes paddingLeft="7px" paddingRight="7px" width="100px" height="23px" childLayout="center"  visibleToMouse="true"/>
        <effect>
        	<onActive name="gradient">
			    <value offset="0%" color="#359d35ff" />
			    <value offset="50%" color="#55e554ff" />
			    <value offset="100%" color="#359d35ff" />
			</onActive>
			<onActive name="border" color="#196819ff"/>
        	<onHover name="gradient" post="true">
			    <value offset="0%" color="#000f" />
			    <value offset="100%" color="#ffff" />
			</onHover>
        </effect>
    </style>
    <style id="button_mainmenu#text" base="button-font">
        <attributes align="center" valign="center" textHAlign="center" textVAlign="center" visibleToMouse="false"/>
        <effect>
            <onEnabled name="textColorAnimated" startColor="#8886" endColor="#eeef" post="false" length="150"/>
            <onDisabled name="textColorAnimated" startColor="#eeef" endColor="#8886" post="false" length="150"/>
        </effect>
    </style>
</nifty-styles>
```

I tried using `post="true"` - with no success. I'm using Slick2D renderer if that matters.

I've attached two pictures - first, without `onHover` tag; second, with `onHover` tag. As you can see, in the second picture there is no black-to-white gradient showed and also the text disappeared.

![1](https://cloud.githubusercontent.com/assets/11155942/26523418/7968671e-4317-11e7-9995-737f2ef4ccaa.png)
![2](https://cloud.githubusercontent.com/assets/11155942/26523417/795fd626-4317-11e7-8086-ddf3c57570bf.png)

Is there something else I could try?

By the way, can I make corners of a button rounded or do I need to use an image?

**Comment by void256** [comment]
There was a bug preventing to configure the gradient parameters specifically for any hover effect :smile: Commit bd9388e should fix this issue.

> By the way, can I make corners of a button rounded or do I need to use an image?

That's currently not possible without images in Nifty 1.4
