### ISSUE TITLE
copyrighted songs in nifty-examples?

### ISSUE THREAD

**Issue by jjYBdx4IL** [nifty-gui/nifty-gui#441]
Couldn't find any documentation regarding the licensing issues.

**Comment by void256** [comment]
Everything in the nifty-examples is licensed under creative commons attribution license. The attribution is publicly visible .. however, one needs to actually start the demo/examples to see that. So for example https://github.com/nifty-gui/nifty-gui/blob/1.4/nifty-examples/src/main/resources/all/intro.xml contains all the names of the sound sources and the licenses but it's not obvious to look in this file if one doesn't know to compile and run the examples.

In retrospect (6 years later :wink:) it would have been better to add a LICENSE file next to the sound files. I think I'll add a LICENSE file to be safe here and make it more easy for the authors of sound files to verify the LICENSE.

**Comment by jjYBdx4IL** [comment]
I would rather add a LICENSE.other or something similar to the root of the package for documenting stuff that is not under the primary license.
