### ISSUE TITLE
onHide effect postpones hiding an element

### ISSUE THREAD

**Issue by Genhis** [nifty-gui/nifty-gui#448]
I want to call a method whenever is an element hidden or shown. I've managed to get it done by using two effects, onShow and onHide. However, when I added onHide effect, the element was shown about 5 seconds longer after the setVisible(false) function was called.

Firstly, I tried it with Console, then I tested the effects on plain panel, just to be sure there's nothing wrong with the console control.

Why is it taking so long to hide the element after using onHide effect? Can it be fixed?

Relevant XML code:
```
<effect>
	<onShow name="nop" onStartEffect="start()" onEndEffect="end()" />
	<onHide name="nop" onStartEffect="start()" onEndEffect="end()" />
</effect>
```

**Comment by bgroenks96** [comment]
Please post an SSCE in the [Nifty issues repository](https://github.com/nifty-gui/nifty-gui-issues). There shouldn't be any significant timing difference (afaik) between `onHide` and `setVisible`.

**Comment by Genhis** [comment]
I've figured it out. An element is hidden when `onHide` effect ended, and because effects have default length of 1000ms, there was a delay.

So, it doesn't require fix in the nifty library but users need to set `length="0"` when using `nop` effect.
