### ISSUE TITLE
Is there any way to apply spritesheet imageMode to niftyImage dynamically?

### ISSUE THREAD

**Issue by raLaaaa** [nifty-gui/nifty-gui#451]
Hey I'd like to know whether there is a chance to apply an spritesheet imageMode to a niftyImage?
Documentation says that it is possible to apply an imageMode to an niftyImage but only normal, subimage, repeat etc. ([source (old though)](http://nifty-gui.sourceforge.net/projects/1.3/nifty/apidocs/de/lessvoid/nifty/render/NiftyImageMode.html))

How ever it was not possible for me to get it working with the spritesheetimagemode.

My code is looking like the following:

```
public void test() {
		NiftyImage ni = CoreGameState.nifty.createImage("test.png", false);
		ImageMode apply = ImageModeFactory.getSharedInstance().createImageMode("sprite:32,32","1");
		ni.setImageMode(apply);
		ni.reload();
	}
```

But the image is just getting displayed as if there would be no imagemode applied

My problem is that I'm trying to change an image (or backgroundImage of an element) at runtime.
I also tried to apply an ImageBuffer which contains the right Image to my nifty element but I could not get this working either.

So I can either load an niftyImage from my disc and apply the imageMode or create an empty niftyImage (or something else) where I can apply my ImageBuffer to. Another possible solution might be converting a Slick2D image to a Nifty image at runtime, but i believe that this would be done via the ImageBuffer as well.

Any hints on how either one of these are achievable? 

------
I'm using Nifty 1.4.2 with Slick2D and this is my nifty init code (just in case..):
```
BatchRenderBackend renderer = SlickBatchRenderBackendFactory.create(arg0);
BatchRenderDevice batchRenderDevice = new BatchRenderDevice(renderer);			
nifty = new Nifty(batchRenderDevice, new NullSoundDevice(),psis, new AccurateTimeProvider());
```

**Comment by bgroenks96** [comment]
I believe this *should* be possible, but it could be that the Slick backend simply doesn't implement it. Could you maybe try doing this with the LWJGL or JOGL backends and see if you still have the same difficulties?

**Comment by raLaaaa** [comment]
Gonne check it out, thanks! Gonna respond as soon as I can provide any updates on this.

**Comment by raLaaaa** [comment]
Unfortunately it was not possible for me doing this changing the backend. 
I again tried to use imageMode and applying an ImageBuffer to a niftyImage.

Any other hints? Do I maybe need to consider something when using the LWJGL backend for instance?

**Comment by Genhis** [comment]
I believe your `AreaProvider` (the first parameter in `createImageMode()`) should be `"sprite:32,32,1"`.

From [the manual](https://sourceforge.net/projects/nifty-gui/files/nifty-gui/1.3.2/nifty-gui-the-manual-1.3.2.pdf/download):

> **imageMode=“sprite:w,h,index"**
This will treat the given image as a sprite sheet. The "w" and "h" properties specify the size of a
single sprite and the image is being interpreted as being fragmented into w*h sized boxes. This
means you have "original width of image / w parameter" sprites on the x-axis and "original height
of image / h parameter" sprites on the y-axis. The index property will specify which sprite you‘ll
want to draw.

I am not sure about the second one though.

**Comment by raLaaaa** [comment]
Ah! I could have seen this as well, damn. This works perfectly. Thanks for your help! I just leave the second parameter empty for now and it looks like it's working.
