### ISSUE TITLE
Memory Leak in style event service

### ISSUE THREAD

**Issue by Jeddic** [nifty-gui/nifty-gui#461]
So I had a few users complain about a performance problem in my game in an area that was adding and removing a lot of nifty elements. After looking into it I found the following call in element construction with no corresponding call when removed:

`nifty.getEventService().subscribeStrongly("style-refresh:" + getStyle(), styleListener);`

This method basically loops through every single element that is subscribed with the same style name.  After adding and removing elements after an hour+ of gameplay this causes some pretty major performance issues. This listener doesn't appear to be used unless you are trying to change a style by hand since I removed it in a local nifty build and haven't had any negative effects. 

Is there a reason to have a subscription service to update styles as opposed to just walking the scene graph? It seems like a hefty performance hit for adding items in order to update styles.

**Comment by void256** [comment]
This feature was added in commit 0e97cb9859f0346e4bd6c370d5a1454690d40ec6 and it looks like the commiter missed to unsubscribe from the event bus when the element is removed. I think we should simply add an unsubsribe when the element is being removed. This should fix your issue, I suppose?

Using the event bus for internal communication is a bit of overkill in this case indeed. However,  in case you ever would like to know when a style changes in application code you could use the same feature and it should not hurt performance that much if the listener is properly unregistered from the eventbus when the element is gone.

**Comment by Jeddic** [comment]
It fixes the long term memory leak, however, the original reason I figured it out was because I was investigating a performance problem with this piece of code. In my UI I have a section where if you mouse over an icon it removes / adds up to 4 other icons to show crafting requirements. On my dev pc it causes up to about a 2ms delay and I have some players were it is significantly worse and makes the game stutter. Some of the arrays it checks against have 10k-20k elements in them (such as null styles) and when you attach some control that has 4-5 elements in them it adds up quick. Adding the unsubscribe actually doubles the performance problem here since it does the same check when you unregister a listener.
