### ISSUE TITLE
nifty-lwjgl3-renderer isn't in the Maven repo

### ISSUE THREAD

**Issue by The-Fireplace** [nifty-gui/nifty-gui#462]
I am trying to set up nifty gui with my LWJGL3 project, and found that nifty-lwjgl3-renderer does not appear to be in the [Maven](https://search.maven.org/search?q=g:com.github.nifty-gui). Looking at the [comments on the pull request that added it](https://github.com/nifty-gui/nifty-gui/pull/426#issuecomment-227008920), it appears that it was slated for 1.4.3, which was never released. I realize that there is a big, 2.0 update coming at some point, but is there any chance we could get a minor update released adding LWJGL3 support?

**Comment by void256** [comment]
1.4.3 has been released today and should be available in the maven central by now.
