### ISSUE TITLE
Parameter not resolved correctly for nested controls

### ISSUE THREAD

**Issue by Tasemo** [nifty-gui/nifty-gui#465]
Currently, if you define nested controls with different parameters, the parameter is resolved with the value declared on the outer most control. This effectively prevents the use of individual parameter for nested controls, which is not very nice if one wants to create some kind of tree structure (like a proper menu). Debugging shows that de.lessvoid.nifty.loaderv2.types.ElementType#resolveParameters passes the attributes down to child elements and merges them with existing attributes. If the attribute is already present, it is silently rejected. Wouldn't it be better if new declarations override existing ones,  so that the described scenario would work? Would that break something I´m not aware of? I´m also happy to submit a pull request if the change is desired.

**Comment by Genhis** [comment]
Hi,
Can you post an example code (XML/Java), and explain what it does and what it should do?

**Comment by Tasemo** [comment]
``` xml
    <controlDefinition name="treeMenu" controller="SomeController" childRootId="#content">
        <panel childLayout="horizontal">
            <panel childLayout="center">
                <control name="label" text="$caption"/>
            </panel>
            <panel id="#content" childLayout="center"/>
        </panel>
    </controlDefinition
    <layer childLayout="vertical">
        <control id="test1" name="treeMenu" caption="Test1">
            <control id="test2" name="treeMenu" caption="Test2"/>
            <control id="test3" name="treeMenu" caption="Test3"/>
        </control>
    </layer>
```
As far as I understand, this should create 3 labels with the captions of "Test1", "Test2" and "Test3", but currently, it just creates labels all with a caption of "Test1". The parameter "caption" is not correctly resolved for each control.

**Comment by Genhis** [comment]
For clarity, here is a runnable example: https://github.com/nifty-gui/nifty-gui-issues/pull/9
Notice that the background color changes but the caption does not (issue with custom attributes?).

A pull request would be welcome I believe, but please test if all controls work correctly with your fix (hope it won't end up like one of my attempts to fix attribute merging in setStyle - https://github.com/nifty-gui/nifty-gui/issues/450#issuecomment-396898431).

Thanks!
