### ISSUE TITLE
parents of nested controls receive incorrect onStartEffect and onEndEffect events

### ISSUE THREAD

**Issue by Tasemo** [nifty-gui/nifty-gui#467]
Hello guys, I have been playing around with nested controls some more and noticed that parents of nested controls receive the same effect events their children receive. You can view the SSCCE  [here](https://github.com/Tasemo/nifty-gui-issues/commit/1382e47957f686c90e56bb66b3840421b6a6a28e). When one, for example, starts hovering over the "Test4" label, then the onHoverStart() methods of "Test4", "Test3" and "Test1" are executed in that order, even tho the mouse is just hovering over "Test4". The same happens for example with onClick effects. I´m trying to debug it but have not made much progress so far, the only thing I can say is that de.lessvoid.nifty.elements.Element#buildMouseOverElements adds the correct elements to the mouseOverHandler.

**Comment by Tasemo** [comment]
Welp, after wasting some time debugging I finally read the manual and it clearly states:
> The Controller, if present, will be the target for all events that the element generates (more about
interact events below) and the **event will travel the tree upwards calling the Controller of other
elements** all the way up to the ScreenController.

So I guess I´m turning this issue into a feature request then as I would really like to have a way to stop this behavior. What do you guys think about adding a new parameter to the ControlDefinitionBuilder? My use case is that I would like to create a menu (that you see in almost every program) that expands its child menus once you hover over specific elements. I currently see no other way than building a tree structure for that (need to know which elements are childs of which). As stated previously, I´m happy to implement it, but I´m not sure if it will be accepted.

**Comment by Genhis** [comment]
Have you thought of other ways to do that?
What is the problem with current event delegation? I mean, if **B** is child of **A** and receives an `onHoverStart` event, **A** would get `onHoverStart` as well, right? Does it matter that **A** was previously hovered and would call `onHoverStart()` again?

Anyway, I believe that adding a new parameter wouldn't be an issue if it doesn't break anything else.

**Comment by Tasemo** [comment]
Yeah, I though about other ways of doing that, mainly by trying to remove the need for nested controllers. For example having a single controller for the whole tree or moving the controller to its own leaf without direct descendants (the second one worked decent, but I had no access to the control parameters and I had to walk the tree up and down constantly to get to the intended elements, having to place the controller on a wrong element just to get around the event delegation seems wrong in general).

My problem exists with the onHoverEnd() event, where I intend to hide all children, unless any child or the parent is currently hovered. So lets say for example that **B** and **C** are children of **A** and I´m moving the mouse from **B** to **C**. Since I´m not hovering over the parent or any child, it should hide all children of **B**. But that´s not whats happening, since **A** also received the onHoverStart() event as soon as **C** received it and so the parent of **B** is marked as hovered.
There could also be some performance problems when the tree gets somewhat larger as every parent and their parents and so on receive the events and have to check all parents and children themselves.

Edit: In case some one wants to try it out (or maybe find the mistake in my implementation), I have posted the relevant code [here](https://pastebin.com/FFcNbf5v).

**Comment by Genhis** [comment]
What if you used `caption` as a unique identifier and ignored all method calls not intended for current element?

    <onHover name="nop" onStartEffect="onHoverStart($caption)" onEndEffect="onHoverEnd($caption)" />

P.S. Don't wait for Nifty 1.4.4, compile it yourself.

EDIT: Nevermind, it looks like attribute values are not supported inside method calls.

**Comment by Tasemo** [comment]
Yeah I just found the following piece of documentation:
```
Changing the return value of an interaction method to boolean and returning true prevents calling
any other methods.
```
Can´t believe I made the same mistake again by not reading the manual properly... @Genhis I´m sorry for wasting your time, I´m closing this issue. Thanks for your help with my problem anyway!
