### ISSUE TITLE
visibleToMouse not set automatically when onClick effect is added

### ISSUE THREAD

**Issue by Tasemo** [nifty-gui/nifty-gui#469]
Hey guys,
I noticed that the visibleToMouse attribute is automatically set to true when a \<interact> tag or an \<onHover> effect is attached to an element. This is not the case for the \<onClick> effect, even though this is always required to make the effect work. The following examples work and set the attribute automatically:
``` xml
<panel childLayout="center">
    <effect>
        <onHover name="nop" onEndEffect="effectExecuted()"/>
    </effect>
</panel>
<panel childLayout="center">
    <interact onClick="effectExecuted()"/>
</panel>
```
The following example does not work without setting visibleToMouse to true:
``` xml
<panel childLayout="center">
    <effect>
        <onClick name="nop" onEndEffect="effectExecuted()"/>
    </effect>
</panel>
```

**Comment by Genhis** [comment]
If `onHover` effect sets `visibleToMouse` automatically and `onClick` doesn't, it seems to me like a bug.

Can you submit a pull request?
