### ISSUE TITLE
how can change font Size?

### ISSUE THREAD

**Issue by qq1053831109** [nifty-gui/nifty-gui#476]
how can change font Size?

**Comment by Genhis** [comment]
There are two options to change the font size:
1) You can create your own fonts (in various sizes) with bitmap fonts generator, such as [FontBuilder](https://github.com/andryblack/fontbuilder).
2) You can use [`textSize`](https://github.com/nifty-gui/nifty-gui/wiki/Effects#textSize) effect on any font to change its size. See [the effect implementation](https://github.com/nifty-gui/nifty-gui/blob/338ffe2182ed58d02f550120d04a444411adfa46/nifty-core/src/main/java/de/lessvoid/nifty/effects/impl/TextSize.java) for details. This would, however, make your font look pixelated.
