### ISSUE TITLE
No "how to get started" section in the README.md file

### ISSUE THREAD

**Issue by fabrice-ducos** [nifty-gui/nifty-gui#489]
This is more a newbie question than an issue (though it could be considered an issue of lack of explanations in the README.md file. There is no  "how to get started" section).
How do people run those examples? I mean, I am far from being a Java expert, but I know how to run a jar (at least if a main class is defined in the manifest, that doesn't seem to be the case here), or to use maven goals or gradle tasks.

Once the code is built and all tests pass, how can one run those tests?

Here, I can see only .jnlp files.

After successfully building the package (all tests passed with Maven), I tried to launch one on Linux (with the ` icetea-plugin` installed in Firefox, the open source replacement for Oracle JavaWebStart):

`$ firefox ./nifty-examples-lwjgl3/nifty-tutorial-1.1.jnlp`

It does launch the application, but quickly fails with the following error:

`/tmp/netx-native-36458/liblwjgl.so: /tmp/netx-native-36458/liblwjgl.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)`
Both versions (32 and 64 bits) are built on the fly by icetea though, as one can check when looking at the tmp directory:

```
-rw-------  1 ducos ducos  13776 août  25 18:09 libjinput-linux64.so
-rw-------  1 ducos ducos  10604 août  25 18:09 libjinput-linux.so
-rw-------  1 ducos ducos 346360 août  25 18:09 liblwjgl64.so
-rw-------  1 ducos ducos 277580 août  25 18:09 liblwjgl.so
-rw-------  1 ducos ducos 177410 août  25 18:09 libopenal64.so
-rw-------  1 ducos ducos 158152 août  25 18:09 libopenal.so
```
Of course, my system is 64-bits, but I see no way to tell the system to load the 64-bits version of the native libraries. Has anyone met and solved this problem before?

Eventually, is there a simple way to test the examples from the console without relying on a web browser and without hacking the code (or doing clumsy copy-and-paste of example codes in a standalone program)?

Any help or guidance would be much appreciated.

**Comment by void256** [comment]
The jnlp files are outdated and should have been deleted years ago.

The examples are mostly meant to be executed from your IDE. That being said, there was a time where [this information in the wiki](https://github.com/nifty-gui/nifty-gui/wiki/Examples) would have worked to get you started from the commandline but it's probably outdated as well.

**Comment by fabrice-ducos** [comment]
Dear @void256, thank you very much for your reply and your hint. Even outdated, the information in the wiki should hopefully be a good starting point for me. Hats off to you and all the team for a great library. I am especially impressed by the elegance of the Java Builder API, and the natural mapping between XML and Java Builder syntax.
