### ISSUE TITLE
lwjgl rendering issues: not everything is properly moving with the viewport

### ISSUE THREAD

**Issue by joshcutler** [nifty-gui/nifty-gui#64]
It appears that when using NiftyGui 1.3.2 with LWJGL, as the viewport moves, text and controls within a panel are translated to the correct coordinates, but not the panel itself.  Both the debug coloring as well as simply setting a backgroundColor on the panel are relative to the origin and don't respect viewport translations.

For example, the below:

``` xml
<layer childLayout="vertical">
  <panel childLayout="horizontal" width="100%">
    <panel id="x" width="300px" height="100%" backgroundColor="#F00F" childLayout="vertical" visible="false">
      <text text="test" style="my-font" />
    </panel>
  </panel>
</layer>
```

Shows the correct red background panel at (0,0) but the text "test" moves with the viewport.

Is there anything I can do to get the panels themselves to translate?  I can provide more info as needed.

**Comment by void256** [comment]
What do you mean by "the viewport moves"? How do you actually move it? Do you refer to the "Move" effect inside of Nifty or do you change the OpenGL viewport?

**Comment by void256** [comment]
Yes, I want more info :)

**Comment by joshcutler** [comment]
Hey, thanks for the quick response.  I am talking about calling glTranslate(x, y, z)--so chanigng the openGL viewport.  It appears that the controls have some problems too (though the text still gets its coordinates translated).  I'm thinking that I am doing something wrong here and just never noticed because up until now I have only ever rendered text.

**Comment by void256** [comment]
I've tried modifying the ModelView Matrix with glTranslate() prior of calling nifty.render() and I get the exact same opposite result :) In my case the text is rendered at a fixed position on the screen and does not respect the glTranslate() modification. The panels however move according to the values set by glTranslate() :)

I can explain the behaviour I'm seeing (but not yours but I might simply misunderstood your explanation). Here is what is happing:

The Nifty LWJGL renderer will reset the ModelView Matrix stack to the identity matrix when it renders text:

``` java
GL11.glMatrixMode(GL11.GL_MODELVIEW);
GL11.glPushMatrix();
GL11.glLoadIdentity();
...
GL11.glPopMatrix();
```

So your change with glTranslate() is simply ignored when rendering text. On the other hand when rendering panels and images there is no reset so the transformation you put on the ModelView stack with glTranslate() is indeed applied.

In general Nifty has not been designed to allow you that sort of manipulation of the matrix stack and I think we could even go so far and say it is a bug that you actually _can_ manipulate it. In other words, the text rendering is correct and the image and panel rendering is kinda wrong.

When Nifty someday switches to core profile this kind of modification won't be possible at all :) Edit: Maybe there will be other tricks you could do like rendering Nifty to a texture by changing the rendering target prior of calling nifty.render() but that's something I need to think a bit more for Nifty 2.0 anyway ;)

Can you explain why you are trying to move Niftys viewport around? Maybe there is another way to solve what you're trying to do?

**Comment by joshcutler** [comment]
Ok, that makes sense.  I don't actually want to move Nifty's viewport around... I wanted it to just sit nicely on top of the game that is being rendered in the background.  I guess I had assumed that the identity matrix was getting loaded internally (since the text followed me around).  If I just load the identity before calling nifty.render() that fixes everything.

Thanks for your help!
