### ISSUE TITLE
Make Element.findElementByName() deprecated

### ISSUE THREAD

**Issue by fleather** [nifty-gui/nifty-gui#82]
The method Element.findElementByName() should better be named Element.findElementById(), because that's what it is.

Element.findElementByName() could be made deprecated and not deleted for compatibility reasons.

 The function of the new method shall be exactly the same.

**Comment by void256** [comment]
This has already been fixed by @floyd1982 in commit 2bf94cba6353cb3a7feadd20c9670e730b3dba72

I'll close this issue.
