### ISSUE TITLE
Mouse events also occur for covered elements.

### ISSUE THREAD

**Issue by fleather** [nifty-gui/nifty-gui#83]
Obtaining mouse events via @NiftyEventSubscriber annotation has the issue, that events occur even for elements, which lie "behind" other elements.

This behaviour seems to be different to obtaining events via the "<interact...." way, but should be work exactly the same so that using either @NiftyEventSubscriber or "<interact...." is interchangeable.

**Comment by fleather** [comment]
This seems to be fixed in 1.4, could someone please confirm that?

**Comment by void256** [comment]
Seems to work for me in 1.4. I've added a simple example too.
I'll close this issue now.
