### ISSUE TITLE
More flexible solution in using control definition paramters

### ISSUE THREAD

**Issue by fleather** [nifty-gui/nifty-gui#84]
Currently control definition parameters work this way:

``` xml
<controlDefinition name="myInventoryControl">
    <image filename="$myFilenameParameter" />
</controlDefinition>

<control name="myInventoryControl" myFilenameParameter="inventory_items/redherring.png" />
```

A more flexible way would be like in Java Expression Language (EL):

``` xml
<controlDefinition name="myInventoryControl">
    <image filename="inventory_items/${inventoryItemName}.png" />
</controlDefinition>

<control name="myInventoryControl" inventoryItemName="redherring" />
```

Through the curcly braces ${parameterName} it should be possible to differentiate the two parameter using styles. Passing the parameter would be exactly the same. But it could be used in two different ways...

**Comment by HariboTer** [comment]
I agree, this would be a nice organization helper.

**Comment by void256** [comment]
Please note that the syntax had to be changed slightly from curly braces to round braces. The reason for this is that curly braces are already used for localisation support. Additionally only a single $() value will be detected as a parameter. I think it would be possible to add support for several parameters as well but someone else should add that if needed :wink:

A working example has been added as well:

https://github.com/void256/nifty-gui/blob/1.4/nifty-examples/src/main/java/de/lessvoid/nifty/issues/issue84/Issue84Main.java
https://github.com/void256/nifty-gui/blob/1.4/nifty-examples/src/main/resources/issues/issue84/issue84.xml
